---------------------------------------------------------
-- Create Auth_Pkg's Specification
---------------------------------------------------------
CREATE OR REPLACE PACKAGE AUTH_PKG AS

    PROCEDURE REGISTER_USER (
        P_USERNAME       IN USERS.USERNAME%TYPE,
        P_EMAIL          IN USERS.EMAIL%TYPE,
        P_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE,
        P_FULL_NAME      IN USERS.FULL_NAME%TYPE,
        P_USER_ID        OUT USERS.USER_ID%TYPE
    );

    PROCEDURE LOGIN_USER (
        P_USERNAME      IN USERS.USERNAME%TYPE,
        P_PASSWORD_HASH IN USERS.PASSWORD_HASH%TYPE,
        P_IP_ADDRESS    IN LOGIN_HISTORY.IP_ADDRESS%TYPE,
        P_USER_ID       OUT USERS.USER_ID%TYPE,
        P_STATUS        OUT USERS.STATUS%TYPE
    );

    PROCEDURE CHANGE_PASSWORD (
        P_USER_ID            IN USERS.USER_ID%TYPE,
        P_OLD_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE,
        P_NEW_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE
    );

    PROCEDURE LOCK_USER (
        P_USER_ID IN USERS.USER_ID%TYPE
    );

    PROCEDURE UNLOCK_USER (
        P_USER_ID IN USERS.USER_ID%TYPE
    );

END AUTH_PKG;
/

---------------------------------------------------------
-- Create Auth_Pkg's Body
---------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY AUTH_PKG AS

    PROCEDURE REGISTER_USER (
        P_USERNAME       IN USERS.USERNAME%TYPE,
        P_EMAIL          IN USERS.EMAIL%TYPE,
        P_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE,
        P_FULL_NAME      IN USERS.FULL_NAME%TYPE,
        P_USER_ID        OUT USERS.USER_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO USERS (
            USERNAME,
            EMAIL,
            PASSWORD_HASH,
            FULL_NAME,
            STATUS
        ) VALUES (
            P_USERNAME,
            P_EMAIL,
            P_PASSWORD_HASH,
            P_FULL_NAME,
            'ACTIVE'
        )
        RETURNING USER_ID INTO P_USER_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20001, 'USERNAME OR EMAIL ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR REGISTERING USER: ' || SQLERRM);
    END REGISTER_USER;


    PROCEDURE LOGIN_USER (
        P_USERNAME      IN USERS.USERNAME%TYPE,
        P_PASSWORD_HASH IN USERS.PASSWORD_HASH%TYPE,
        P_IP_ADDRESS    IN LOGIN_HISTORY.IP_ADDRESS%TYPE,
        P_USER_ID       OUT USERS.USER_ID%TYPE,
        P_STATUS        OUT USERS.STATUS%TYPE
    ) AS
        V_PASSWORD_HASH USERS.PASSWORD_HASH%TYPE;
        V_FAILED_LOGIN  USERS.FAILED_LOGIN%TYPE;
    BEGIN
        SELECT USER_ID, PASSWORD_HASH, STATUS, FAILED_LOGIN
        INTO P_USER_ID, V_PASSWORD_HASH, P_STATUS, V_FAILED_LOGIN
        FROM USERS
        WHERE USERNAME = P_USERNAME;

        IF P_STATUS = 'LOCKED' THEN
            INSERT INTO LOGIN_HISTORY (
                USER_ID, USERNAME, LOGIN_STATUS, IP_ADDRESS
            ) VALUES (
                P_USER_ID, P_USERNAME, 'FAILED', P_IP_ADDRESS
            );

            RAISE_APPLICATION_ERROR(-20003, 'USER ACCOUNT IS LOCKED.');
        END IF;

        IF P_STATUS <> 'ACTIVE' THEN
            INSERT INTO LOGIN_HISTORY (
                USER_ID, USERNAME, LOGIN_STATUS, IP_ADDRESS
            ) VALUES (
                P_USER_ID, P_USERNAME, 'FAILED', P_IP_ADDRESS
            );

            RAISE_APPLICATION_ERROR(-20004, 'USER ACCOUNT IS NOT ACTIVE.');
        END IF;

        IF V_PASSWORD_HASH = P_PASSWORD_HASH THEN
            UPDATE USERS
            SET FAILED_LOGIN = 0,
                LAST_LOGIN_AT = SYSTIMESTAMP,
                UPDATED_AT = SYSTIMESTAMP
            WHERE USER_ID = P_USER_ID;

            INSERT INTO LOGIN_HISTORY (
                USER_ID, USERNAME, LOGIN_STATUS, IP_ADDRESS
            ) VALUES (
                P_USER_ID, P_USERNAME, 'SUCCESS', P_IP_ADDRESS
            );
        ELSE
            V_FAILED_LOGIN := V_FAILED_LOGIN + 1;

            UPDATE USERS
            SET FAILED_LOGIN = V_FAILED_LOGIN,
                STATUS = CASE
                            WHEN V_FAILED_LOGIN >= 5 THEN 'LOCKED'
                            ELSE STATUS
                         END,
                UPDATED_AT = SYSTIMESTAMP
            WHERE USER_ID = P_USER_ID;

            INSERT INTO LOGIN_HISTORY (
                USER_ID, USERNAME, LOGIN_STATUS, IP_ADDRESS
            ) VALUES (
                P_USER_ID, P_USERNAME, 'FAILED', P_IP_ADDRESS
            );

            RAISE_APPLICATION_ERROR(-20005, 'INVALID USERNAME OR PASSWORD.');
        END IF;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGIN_HISTORY (
                USERNAME, LOGIN_STATUS, IP_ADDRESS
            ) VALUES (
                P_USERNAME, 'FAILED', P_IP_ADDRESS
            );

            RAISE_APPLICATION_ERROR(-20006, 'INVALID USERNAME OR PASSWORD.');

        WHEN OTHERS THEN
            RAISE;
    END LOGIN_USER;


    PROCEDURE CHANGE_PASSWORD (
        P_USER_ID            IN USERS.USER_ID%TYPE,
        P_OLD_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE,
        P_NEW_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE
    ) AS
        V_PASSWORD_HASH USERS.PASSWORD_HASH%TYPE;
    BEGIN
        SELECT PASSWORD_HASH
        INTO V_PASSWORD_HASH
        FROM USERS
        WHERE USER_ID = P_USER_ID
          AND STATUS = 'ACTIVE';

        IF V_PASSWORD_HASH <> P_OLD_PASSWORD_HASH THEN
            RAISE_APPLICATION_ERROR(-20007, 'OLD PASSWORD IS INCORRECT.');
        END IF;

        UPDATE USERS
        SET PASSWORD_HASH = P_NEW_PASSWORD_HASH,
            UPDATED_AT = SYSTIMESTAMP
        WHERE USER_ID = P_USER_ID;

        INSERT INTO PASSWORD_HISTORY (
            USER_ID,
            PASSWORD_HASH
        ) VALUES (
            P_USER_ID,
            P_NEW_PASSWORD_HASH
        );

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20008, 'ACTIVE USER NOT FOUND.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20009, 'ERROR CHANGING PASSWORD: ' || SQLERRM);
    END CHANGE_PASSWORD;


    PROCEDURE LOCK_USER (
        P_USER_ID IN USERS.USER_ID%TYPE
    ) AS
    BEGIN
        UPDATE USERS
        SET STATUS = 'LOCKED',
            UPDATED_AT = SYSTIMESTAMP
        WHERE USER_ID = P_USER_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20010, 'USER NOT FOUND.');
        END IF;
    END LOCK_USER;


    PROCEDURE UNLOCK_USER (
        P_USER_ID IN USERS.USER_ID%TYPE
    ) AS
    BEGIN
        UPDATE USERS
        SET STATUS = 'ACTIVE',
            FAILED_LOGIN = 0,
            UPDATED_AT = SYSTIMESTAMP
        WHERE USER_ID = P_USER_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20011, 'USER NOT FOUND.');
        END IF;
    END UNLOCK_USER;

END AUTH_PKG;
/
