---------------------------------------------------------
-- Create Permission_Pkg's Specification
---------------------------------------------------------
CREATE OR REPLACE PACKAGE PERMISSION_PKG AS

    PROCEDURE ADD_PERMISSION (
        P_PERMISSION_CODE IN PERMISSIONS.PERMISSION_CODE%TYPE,
        P_DESCRIPTION     IN PERMISSIONS.DESCRIPTION%TYPE,
        P_PERMISSION_ID   OUT PERMISSIONS.PERMISSION_ID%TYPE
    );

    PROCEDURE UPDATE_PERMISSION (
        P_PERMISSION_ID   IN PERMISSIONS.PERMISSION_ID%TYPE,
        P_PERMISSION_CODE IN PERMISSIONS.PERMISSION_CODE%TYPE,
        P_DESCRIPTION     IN PERMISSIONS.DESCRIPTION%TYPE,
        P_STATUS          IN PERMISSIONS.STATUS%TYPE
    );

    PROCEDURE ASSIGN_PERMISSION_TO_ROLE (
        P_ROLE_ID       IN ROLES.ROLE_ID%TYPE,
        P_PERMISSION_ID IN PERMISSIONS.PERMISSION_ID%TYPE
    );

    PROCEDURE REMOVE_PERMISSION_FROM_ROLE (
        P_ROLE_ID       IN ROLES.ROLE_ID%TYPE,
        P_PERMISSION_ID IN PERMISSIONS.PERMISSION_ID%TYPE
    );

    PROCEDURE GET_ROLE_PERMISSIONS (
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    );

    PROCEDURE GET_USER_PERMISSIONS (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    );

END PERMISSION_PKG;
/

---------------------------------------------------------
-- Create Permission_Pkg's Body
---------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY PERMISSION_PKG AS

    PROCEDURE ADD_PERMISSION (
        P_PERMISSION_CODE IN PERMISSIONS.PERMISSION_CODE%TYPE,
        P_DESCRIPTION     IN PERMISSIONS.DESCRIPTION%TYPE,
        P_PERMISSION_ID   OUT PERMISSIONS.PERMISSION_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO PERMISSIONS (
            PERMISSION_CODE,
            DESCRIPTION
        ) VALUES (
            UPPER(TRIM(P_PERMISSION_CODE)),
            P_DESCRIPTION
        )
        RETURNING PERMISSION_ID INTO P_PERMISSION_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20201, 'PERMISSION ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20202, 'ERROR ADDING PERMISSION: ' || SQLERRM);
    END ADD_PERMISSION;


    PROCEDURE UPDATE_PERMISSION (
        P_PERMISSION_ID   IN PERMISSIONS.PERMISSION_ID%TYPE,
        P_PERMISSION_CODE IN PERMISSIONS.PERMISSION_CODE%TYPE,
        P_DESCRIPTION     IN PERMISSIONS.DESCRIPTION%TYPE,
        P_STATUS          IN PERMISSIONS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE PERMISSIONS
        SET PERMISSION_CODE = UPPER(TRIM(P_PERMISSION_CODE)),
            DESCRIPTION     = P_DESCRIPTION,
            STATUS          = UPPER(TRIM(P_STATUS)),
            UPDATED_AT      = SYSTIMESTAMP
        WHERE PERMISSION_ID = P_PERMISSION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20203, 'PERMISSION NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20204, 'PERMISSION CODE ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20205, 'ERROR UPDATING PERMISSION: ' || SQLERRM);
    END UPDATE_PERMISSION;


    PROCEDURE ASSIGN_PERMISSION_TO_ROLE (
        P_ROLE_ID       IN ROLES.ROLE_ID%TYPE,
        P_PERMISSION_ID IN PERMISSIONS.PERMISSION_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO ROLE_PERMISSIONS (
            ROLE_ID,
            PERMISSION_ID
        ) VALUES (
            P_ROLE_ID,
            P_PERMISSION_ID
        );

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20206, 'PERMISSION ALREADY ASSIGNED TO THIS ROLE.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20207, 'ERROR ASSIGNING PERMISSION: ' || SQLERRM);
    END ASSIGN_PERMISSION_TO_ROLE;


    PROCEDURE REMOVE_PERMISSION_FROM_ROLE (
        P_ROLE_ID       IN ROLES.ROLE_ID%TYPE,
        P_PERMISSION_ID IN PERMISSIONS.PERMISSION_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM ROLE_PERMISSIONS
        WHERE ROLE_ID = P_ROLE_ID
          AND PERMISSION_ID = P_PERMISSION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20208, 'ROLE DOES NOT HAVE THIS PERMISSION.');
        END IF;
    END REMOVE_PERMISSION_FROM_ROLE;


    PROCEDURE GET_ROLE_PERMISSIONS (
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                P.PERMISSION_ID,
                P.PERMISSION_CODE,
                P.DESCRIPTION,
                RP.ASSIGNED_AT
            FROM ROLE_PERMISSIONS RP
            INNER JOIN PERMISSIONS P
                ON RP.PERMISSION_ID = P.PERMISSION_ID
            WHERE RP.ROLE_ID = P_ROLE_ID
              AND P.STATUS = 'ACTIVE'
            ORDER BY P.PERMISSION_CODE;
    END GET_ROLE_PERMISSIONS;


    PROCEDURE GET_USER_PERMISSIONS (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT DISTINCT
                P.PERMISSION_ID,
                P.PERMISSION_CODE,
                P.DESCRIPTION
            FROM USER_ROLES UR
            INNER JOIN ROLES R
                ON UR.ROLE_ID = R.ROLE_ID
            INNER JOIN ROLE_PERMISSIONS RP
                ON R.ROLE_ID = RP.ROLE_ID
            INNER JOIN PERMISSIONS P
                ON RP.PERMISSION_ID = P.PERMISSION_ID
            WHERE UR.USER_ID = P_USER_ID
              AND R.STATUS = 'ACTIVE'
              AND P.STATUS = 'ACTIVE'
            ORDER BY P.PERMISSION_CODE;
    END GET_USER_PERMISSIONS;

END PERMISSION_PKG;
/
