---------------------------------------------------------
-- CREATE STUDENT_PKG SPECIFICATION
---------------------------------------------------------
CREATE OR REPLACE PACKAGE STUDENT_PKG AS
    PROCEDURE ADD_STUDENT (
        P_STUDENT_CODE    IN STUDENTS.STUDENT_CODE%TYPE,
        P_FIRST_NAME      IN STUDENTS.FIRST_NAME%TYPE,
        P_LAST_NAME       IN STUDENTS.LAST_NAME%TYPE,
        P_EMAIL           IN STUDENTS.EMAIL%TYPE,
        P_PHONE           IN STUDENTS.PHONE%TYPE,
        P_GENDER          IN STUDENTS.GENDER%TYPE,
        P_DATE_OF_BIRTH   IN STUDENTS.DATE_OF_BIRTH%TYPE,
        P_ADMISSION_DATE  IN STUDENTS.ADMISSION_DATE%TYPE,
        P_STUDENT_ID      OUT STUDENTS.STUDENT_ID%TYPE
    );
    PROCEDURE UPDATE_STUDENT (
        P_STUDENT_ID      IN STUDENTS.STUDENT_ID%TYPE,
        P_FIRST_NAME      IN STUDENTS.FIRST_NAME%TYPE,
        P_LAST_NAME       IN STUDENTS.LAST_NAME%TYPE,
        P_EMAIL           IN STUDENTS.EMAIL%TYPE,
        P_PHONE           IN STUDENTS.PHONE%TYPE,
        P_GENDER          IN STUDENTS.GENDER%TYPE,
        P_DATE_OF_BIRTH   IN STUDENTS.DATE_OF_BIRTH%TYPE,
        P_ADMISSION_DATE  IN STUDENTS.ADMISSION_DATE%TYPE,
        P_STATUS          IN STUDENTS.STATUS%TYPE
    );

    PROCEDURE DELETE_STUDENT (
        P_STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE
    );

    PROCEDURE GET_STUDENT_BY_ID (
        P_STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_STUDENTS (
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE SEARCH_STUDENTS (
        P_SEARCH_TEXT IN VARCHAR2,
        P_RESULT      OUT SYS_REFCURSOR
    );
END STUDENT_PKG;
/

---------------------------------------------------------
-- CREATE STUDENT_PKG BODY
---------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY STUDENT_PKG AS

    PROCEDURE ADD_STUDENT (
        P_STUDENT_CODE    IN STUDENTS.STUDENT_CODE%TYPE,
        P_FIRST_NAME      IN STUDENTS.FIRST_NAME%TYPE,
        P_LAST_NAME       IN STUDENTS.LAST_NAME%TYPE,
        P_EMAIL           IN STUDENTS.EMAIL%TYPE,
        P_PHONE           IN STUDENTS.PHONE%TYPE,
        P_GENDER          IN STUDENTS.GENDER%TYPE,
        P_DATE_OF_BIRTH   IN STUDENTS.DATE_OF_BIRTH%TYPE,
        P_ADMISSION_DATE  IN STUDENTS.ADMISSION_DATE%TYPE,
        P_STUDENT_ID      OUT STUDENTS.STUDENT_ID%TYPE
    ) AS
BEGIN
INSERT INTO STUDENTS (
    STUDENT_CODE,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    ADMISSION_DATE,
    STATUS
) VALUES (
     P_STUDENT_CODE,
     P_FIRST_NAME,
     P_LAST_NAME,
     P_EMAIL,
     P_PHONE,
     UPPER(TRIM(P_GENDER)),
     P_DATE_OF_BIRTH,
     NVL(P_ADMISSION_DATE, SYSDATE),
     'ACTIVE'
 )
    RETURNING STUDENT_ID INTO P_STUDENT_ID;

EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20301, 'STUDENT CODE, EMAIL, OR PHONE ALREADY EXISTS.');
WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20302, 'ERROR ADDING STUDENT: ' || SQLERRM);
END ADD_STUDENT;


    PROCEDURE UPDATE_STUDENT (
        P_STUDENT_ID      IN STUDENTS.STUDENT_ID%TYPE,
        P_FIRST_NAME      IN STUDENTS.FIRST_NAME%TYPE,
        P_LAST_NAME       IN STUDENTS.LAST_NAME%TYPE,
        P_EMAIL           IN STUDENTS.EMAIL%TYPE,
        P_PHONE           IN STUDENTS.PHONE%TYPE,
        P_GENDER          IN STUDENTS.GENDER%TYPE,
        P_DATE_OF_BIRTH   IN STUDENTS.DATE_OF_BIRTH%TYPE,
        P_ADMISSION_DATE  IN STUDENTS.ADMISSION_DATE%TYPE,
        P_STATUS          IN STUDENTS.STATUS%TYPE
    ) AS
BEGIN
UPDATE STUDENTS
SET FIRST_NAME     = P_FIRST_NAME,
    LAST_NAME      = P_LAST_NAME,
    EMAIL          = P_EMAIL,
    PHONE          = P_PHONE,
    GENDER         = UPPER(TRIM(P_GENDER)),
    DATE_OF_BIRTH  = P_DATE_OF_BIRTH,
    ADMISSION_DATE = P_ADMISSION_DATE,
    STATUS         = UPPER(TRIM(P_STATUS)),
    UPDATED_AT     = SYSTIMESTAMP
WHERE STUDENT_ID = P_STUDENT_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20303, 'STUDENT NOT FOUND.');
END IF;

EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20304, 'STUDENT EMAIL OR PHONE ALREADY EXISTS.');
WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20305, 'ERROR UPDATING STUDENT: ' || SQLERRM);
END UPDATE_STUDENT;


    PROCEDURE DELETE_STUDENT (
        P_STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE
    ) AS
BEGIN
DELETE FROM STUDENT_GUARDIANS
WHERE STUDENT_ID = P_STUDENT_ID;

DELETE FROM STUDENT_ADDRESSES
WHERE STUDENT_ID = P_STUDENT_ID;

DELETE FROM STUDENTS
WHERE STUDENT_ID = P_STUDENT_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20306, 'STUDENT NOT FOUND.');
END IF;

EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20307, 'ERROR DELETING STUDENT: ' || SQLERRM);
END DELETE_STUDENT;


    PROCEDURE GET_STUDENT_BY_ID (
        P_STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
BEGIN
OPEN P_RESULT FOR
SELECT
    STUDENT_ID,
    STUDENT_CODE,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    ADMISSION_DATE,
    STATUS,
    CREATED_AT,
    UPDATED_AT
FROM STUDENTS
WHERE STUDENT_ID = P_STUDENT_ID;
END GET_STUDENT_BY_ID;


    PROCEDURE GET_ALL_STUDENTS (
        P_RESULT OUT SYS_REFCURSOR
    ) AS
BEGIN
OPEN P_RESULT FOR
SELECT
    STUDENT_ID,
    STUDENT_CODE,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    ADMISSION_DATE,
    STATUS,
    CREATED_AT,
    UPDATED_AT
FROM STUDENTS
ORDER BY STUDENT_ID DESC;
END GET_ALL_STUDENTS;

    PROCEDURE SEARCH_STUDENTS (
        P_SEARCH_TEXT IN VARCHAR2,
        P_RESULT      OUT SYS_REFCURSOR
    ) AS
BEGIN
OPEN P_RESULT FOR
SELECT
    STUDENT_ID,
    STUDENT_CODE,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    ADMISSION_DATE,
    STATUS,
    CREATED_AT,
    UPDATED_AT
FROM STUDENTS
    WHERE LOWER(STUDENT_CODE) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
       OR LOWER(FIRST_NAME) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
       OR LOWER(LAST_NAME) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
       OR LOWER(EMAIL) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
       OR LOWER(PHONE) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
    ORDER BY STUDENT_ID DESC;
END SEARCH_STUDENTS;

END STUDENT_PKG;
/