---------------------------------------------------------------
-- CREATE STUDENT_ADDRESS_PKG SPECIFICATION
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE STUDENT_ADDRESS_PKG AS

    PROCEDURE ADD_ADDRESS (
        P_STUDENT_ID     IN STUDENT_ADDRESSES.STUDENT_ID%TYPE,
        P_ADDRESS_TYPE   IN STUDENT_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN STUDENT_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN STUDENT_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN STUDENT_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN STUDENT_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN STUDENT_ADDRESSES.COUNTRY%TYPE,
        P_ADDRESS_ID     OUT STUDENT_ADDRESSES.ADDRESS_ID%TYPE
    );

    PROCEDURE UPDATE_ADDRESS (
        P_ADDRESS_ID     IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE,
        P_ADDRESS_TYPE   IN STUDENT_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN STUDENT_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN STUDENT_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN STUDENT_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN STUDENT_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN STUDENT_ADDRESSES.COUNTRY%TYPE
    );

    PROCEDURE DELETE_ADDRESS (
        P_ADDRESS_ID IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE
    );

    PROCEDURE GET_ADDRESS_BY_ID (
        P_ADDRESS_ID IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ADDRESSES_BY_STUDENT (
        P_STUDENT_ID IN STUDENT_ADDRESSES.STUDENT_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

END STUDENT_ADDRESS_PKG;
/

---------------------------------------------------------------
-- CREATE STUDENT_ADDRESS_PKG BODY
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY STUDENT_ADDRESS_PKG AS

    PROCEDURE ADD_ADDRESS (
        P_STUDENT_ID     IN STUDENT_ADDRESSES.STUDENT_ID%TYPE,
        P_ADDRESS_TYPE   IN STUDENT_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN STUDENT_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN STUDENT_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN STUDENT_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN STUDENT_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN STUDENT_ADDRESSES.COUNTRY%TYPE,
        P_ADDRESS_ID     OUT STUDENT_ADDRESSES.ADDRESS_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO STUDENT_ADDRESSES (
            STUDENT_ID, ADDRESS_TYPE, ADDRESS_LINE, CITY,
            DISTRICT, POSTAL_CODE, COUNTRY
        ) VALUES (
                     P_STUDENT_ID, UPPER(TRIM(P_ADDRESS_TYPE)), P_ADDRESS_LINE,
                     P_CITY, P_DISTRICT, P_POSTAL_CODE, NVL(P_COUNTRY, 'Bangladesh')
                 )
        RETURNING ADDRESS_ID INTO P_ADDRESS_ID;
    END ADD_ADDRESS;


    PROCEDURE UPDATE_ADDRESS (
        P_ADDRESS_ID     IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE,
        P_ADDRESS_TYPE   IN STUDENT_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN STUDENT_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN STUDENT_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN STUDENT_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN STUDENT_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN STUDENT_ADDRESSES.COUNTRY%TYPE
    ) AS
    BEGIN
        UPDATE STUDENT_ADDRESSES
        SET ADDRESS_TYPE = UPPER(TRIM(P_ADDRESS_TYPE)),
            ADDRESS_LINE = P_ADDRESS_LINE,
            CITY = P_CITY,
            DISTRICT = P_DISTRICT,
            POSTAL_CODE = P_POSTAL_CODE,
            COUNTRY = NVL(P_COUNTRY, 'Bangladesh'),
            UPDATED_AT = SYSTIMESTAMP
        WHERE ADDRESS_ID = P_ADDRESS_ID;

        IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20401, 'ADDRESS NOT FOUND.');
            END IF;

        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                RAISE_APPLICATION_ERROR(
                    -20405,
                    'STUDENT ALREADY HAS THIS ADDRESS TYPE.'
                );

            WHEN OTHERS THEN
                RAISE_APPLICATION_ERROR(
                    -20406,
                    'ERROR UPDATING STUDENT ADDRESS: ' || SQLERRM
                );
    END UPDATE_ADDRESS;


    PROCEDURE DELETE_ADDRESS (
        P_ADDRESS_ID IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM STUDENT_ADDRESSES
        WHERE ADDRESS_ID = P_ADDRESS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20402, 'ADDRESS NOT FOUND.');
        END IF;
    END DELETE_ADDRESS;


    PROCEDURE GET_ADDRESS_BY_ID (
        P_ADDRESS_ID IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT ADDRESS_ID, STUDENT_ID, ADDRESS_TYPE, ADDRESS_LINE,
                   CITY, DISTRICT, POSTAL_CODE, COUNTRY, CREATED_AT, UPDATED_AT
            FROM STUDENT_ADDRESSES
            WHERE ADDRESS_ID = P_ADDRESS_ID;
    END GET_ADDRESS_BY_ID;


    PROCEDURE GET_ADDRESSES_BY_STUDENT (
        P_STUDENT_ID IN STUDENT_ADDRESSES.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT ADDRESS_ID, STUDENT_ID, ADDRESS_TYPE, ADDRESS_LINE,
                   CITY, DISTRICT, POSTAL_CODE, COUNTRY, CREATED_AT, UPDATED_AT
            FROM STUDENT_ADDRESSES
            WHERE STUDENT_ID = P_STUDENT_ID
            ORDER BY ADDRESS_ID;
    END GET_ADDRESSES_BY_STUDENT;

END STUDENT_ADDRESS_PKG;
/
