----------------------------------------------------------------
-- CREATE STUDENT_GUARDIAN_PKG SPECIFICATION
----------------------------------------------------------------
CREATE OR REPLACE PACKAGE STUDENT_GUARDIAN_PKG AS

    PROCEDURE ADD_GUARDIAN (
        P_STUDENT_ID      IN STUDENT_GUARDIANS.STUDENT_ID%TYPE,
        P_GUARDIAN_NAME   IN STUDENT_GUARDIANS.GUARDIAN_NAME%TYPE,
        P_RELATIONSHIP    IN STUDENT_GUARDIANS.RELATIONSHIP%TYPE,
        P_PHONE           IN STUDENT_GUARDIANS.PHONE%TYPE,
        P_EMAIL           IN STUDENT_GUARDIANS.EMAIL%TYPE,
        P_OCCUPATION      IN STUDENT_GUARDIANS.OCCUPATION%TYPE,
        P_IS_PRIMARY      IN STUDENT_GUARDIANS.IS_PRIMARY%TYPE,
        P_GUARDIAN_ID     OUT STUDENT_GUARDIANS.GUARDIAN_ID%TYPE
    );

    PROCEDURE UPDATE_GUARDIAN (
        P_GUARDIAN_ID     IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE,
        P_GUARDIAN_NAME   IN STUDENT_GUARDIANS.GUARDIAN_NAME%TYPE,
        P_RELATIONSHIP    IN STUDENT_GUARDIANS.RELATIONSHIP%TYPE,
        P_PHONE           IN STUDENT_GUARDIANS.PHONE%TYPE,
        P_EMAIL           IN STUDENT_GUARDIANS.EMAIL%TYPE,
        P_OCCUPATION      IN STUDENT_GUARDIANS.OCCUPATION%TYPE,
        P_IS_PRIMARY      IN STUDENT_GUARDIANS.IS_PRIMARY%TYPE
    );

    PROCEDURE DELETE_GUARDIAN (
        P_GUARDIAN_ID IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE
    );

    PROCEDURE GET_GUARDIAN_BY_ID (
        P_GUARDIAN_ID IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE,
        P_RESULT      OUT SYS_REFCURSOR
    );

    PROCEDURE GET_GUARDIANS_BY_STUDENT (
        P_STUDENT_ID IN STUDENT_GUARDIANS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

END STUDENT_GUARDIAN_PKG;
/

----------------------------------------------------------------
-- CREATE STUDENT_GUARDIAN_PKG BODY
----------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY STUDENT_GUARDIAN_PKG AS

    PROCEDURE ADD_GUARDIAN (
        P_STUDENT_ID      IN STUDENT_GUARDIANS.STUDENT_ID%TYPE,
        P_GUARDIAN_NAME   IN STUDENT_GUARDIANS.GUARDIAN_NAME%TYPE,
        P_RELATIONSHIP    IN STUDENT_GUARDIANS.RELATIONSHIP%TYPE,
        P_PHONE           IN STUDENT_GUARDIANS.PHONE%TYPE,
        P_EMAIL           IN STUDENT_GUARDIANS.EMAIL%TYPE,
        P_OCCUPATION      IN STUDENT_GUARDIANS.OCCUPATION%TYPE,
        P_IS_PRIMARY      IN STUDENT_GUARDIANS.IS_PRIMARY%TYPE,
        P_GUARDIAN_ID     OUT STUDENT_GUARDIANS.GUARDIAN_ID%TYPE
    ) AS
BEGIN
INSERT INTO STUDENT_GUARDIANS (
    STUDENT_ID,
    GUARDIAN_NAME,
    RELATIONSHIP,
    PHONE,
    EMAIL,
    OCCUPATION,
    IS_PRIMARY
)
VALUES (
           P_STUDENT_ID,
           P_GUARDIAN_NAME,
           P_RELATIONSHIP,
           P_PHONE,
           P_EMAIL,
           P_OCCUPATION,
           UPPER(TRIM(P_IS_PRIMARY))
       )
    RETURNING GUARDIAN_ID INTO P_GUARDIAN_ID;
END ADD_GUARDIAN;


    PROCEDURE UPDATE_GUARDIAN (
        P_GUARDIAN_ID     IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE,
        P_GUARDIAN_NAME   IN STUDENT_GUARDIANS.GUARDIAN_NAME%TYPE,
        P_RELATIONSHIP    IN STUDENT_GUARDIANS.RELATIONSHIP%TYPE,
        P_PHONE           IN STUDENT_GUARDIANS.PHONE%TYPE,
        P_EMAIL           IN STUDENT_GUARDIANS.EMAIL%TYPE,
        P_OCCUPATION      IN STUDENT_GUARDIANS.OCCUPATION%TYPE,
        P_IS_PRIMARY      IN STUDENT_GUARDIANS.IS_PRIMARY%TYPE
    ) AS
BEGIN
UPDATE STUDENT_GUARDIANS
SET GUARDIAN_NAME = P_GUARDIAN_NAME,
    RELATIONSHIP  = P_RELATIONSHIP,
    PHONE         = P_PHONE,
    EMAIL         = P_EMAIL,
    OCCUPATION    = P_OCCUPATION,
    IS_PRIMARY    = UPPER(TRIM(P_IS_PRIMARY)),
    UPDATED_AT    = SYSTIMESTAMP
WHERE GUARDIAN_ID = P_GUARDIAN_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20501, 'GUARDIAN NOT FOUND.');
END IF;
END UPDATE_GUARDIAN;


    PROCEDURE DELETE_GUARDIAN (
        P_GUARDIAN_ID IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE
    ) AS
BEGIN
DELETE FROM STUDENT_GUARDIANS
WHERE GUARDIAN_ID = P_GUARDIAN_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20502, 'GUARDIAN NOT FOUND.');
END IF;
END DELETE_GUARDIAN;


    PROCEDURE GET_GUARDIAN_BY_ID (
        P_GUARDIAN_ID IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE,
        P_RESULT      OUT SYS_REFCURSOR
    ) AS
BEGIN
OPEN P_RESULT FOR
SELECT GUARDIAN_ID,
       STUDENT_ID,
       GUARDIAN_NAME,
       RELATIONSHIP,
       PHONE,
       EMAIL,
       OCCUPATION,
       IS_PRIMARY,
       CREATED_AT,
       UPDATED_AT
FROM STUDENT_GUARDIANS
WHERE GUARDIAN_ID = P_GUARDIAN_ID;
END GET_GUARDIAN_BY_ID;


    PROCEDURE GET_GUARDIANS_BY_STUDENT (
        P_STUDENT_ID IN STUDENT_GUARDIANS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
BEGIN
OPEN P_RESULT FOR
SELECT GUARDIAN_ID,
       STUDENT_ID,
       GUARDIAN_NAME,
       RELATIONSHIP,
       PHONE,
       EMAIL,
       OCCUPATION,
       IS_PRIMARY,
       CREATED_AT,
       UPDATED_AT
FROM STUDENT_GUARDIANS
WHERE STUDENT_ID = P_STUDENT_ID
ORDER BY GUARDIAN_ID;
END GET_GUARDIANS_BY_STUDENT;

END STUDENT_GUARDIAN_PKG;
/