---------------------------------------------------------------
-- CREATE TEACHER_PKG SPECIFICATION
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE TEACHER_PKG AS

    PROCEDURE ADD_TEACHER (
        P_TEACHER_CODE   IN TEACHERS.TEACHER_CODE%TYPE,
        P_FIRST_NAME     IN TEACHERS.FIRST_NAME%TYPE,
        P_LAST_NAME      IN TEACHERS.LAST_NAME%TYPE,
        P_EMAIL          IN TEACHERS.EMAIL%TYPE,
        P_PHONE          IN TEACHERS.PHONE%TYPE,
        P_GENDER         IN TEACHERS.GENDER%TYPE,
        P_DATE_OF_BIRTH  IN TEACHERS.DATE_OF_BIRTH%TYPE,
        P_JOINING_DATE   IN TEACHERS.JOINING_DATE%TYPE,
        P_DESIGNATION    IN TEACHERS.DESIGNATION%TYPE,
        P_QUALIFICATION  IN TEACHERS.QUALIFICATION%TYPE,
        P_DEPARTMENT     IN TEACHERS.DEPARTMENT%TYPE,
        P_TEACHER_ID     OUT TEACHERS.TEACHER_ID%TYPE
    );

    PROCEDURE UPDATE_TEACHER (
        P_TEACHER_ID     IN TEACHERS.TEACHER_ID%TYPE,
        P_FIRST_NAME     IN TEACHERS.FIRST_NAME%TYPE,
        P_LAST_NAME      IN TEACHERS.LAST_NAME%TYPE,
        P_EMAIL          IN TEACHERS.EMAIL%TYPE,
        P_PHONE          IN TEACHERS.PHONE%TYPE,
        P_GENDER         IN TEACHERS.GENDER%TYPE,
        P_DATE_OF_BIRTH  IN TEACHERS.DATE_OF_BIRTH%TYPE,
        P_JOINING_DATE   IN TEACHERS.JOINING_DATE%TYPE,
        P_DESIGNATION    IN TEACHERS.DESIGNATION%TYPE,
        P_QUALIFICATION  IN TEACHERS.QUALIFICATION%TYPE,
        P_DEPARTMENT     IN TEACHERS.DEPARTMENT%TYPE,
        P_STATUS         IN TEACHERS.STATUS%TYPE
    );

    PROCEDURE DELETE_TEACHER (
        P_TEACHER_ID IN TEACHERS.TEACHER_ID%TYPE
    );

    PROCEDURE GET_TEACHER_BY_ID (
        P_TEACHER_ID IN TEACHERS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_TEACHERS (
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE SEARCH_TEACHERS (
        P_SEARCH_TEXT IN VARCHAR2,
        P_RESULT      OUT SYS_REFCURSOR
    );

END TEACHER_PKG;
/

----------------------------------------------------------------
-- CREATE TEACHER_PKG BODY
----------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY TEACHER_PKG AS

    PROCEDURE ADD_TEACHER (
        P_TEACHER_CODE   IN TEACHERS.TEACHER_CODE%TYPE,
        P_FIRST_NAME     IN TEACHERS.FIRST_NAME%TYPE,
        P_LAST_NAME      IN TEACHERS.LAST_NAME%TYPE,
        P_EMAIL          IN TEACHERS.EMAIL%TYPE,
        P_PHONE          IN TEACHERS.PHONE%TYPE,
        P_GENDER         IN TEACHERS.GENDER%TYPE,
        P_DATE_OF_BIRTH  IN TEACHERS.DATE_OF_BIRTH%TYPE,
        P_JOINING_DATE   IN TEACHERS.JOINING_DATE%TYPE,
        P_DESIGNATION    IN TEACHERS.DESIGNATION%TYPE,
        P_QUALIFICATION  IN TEACHERS.QUALIFICATION%TYPE,
        P_DEPARTMENT     IN TEACHERS.DEPARTMENT%TYPE,
        P_TEACHER_ID     OUT TEACHERS.TEACHER_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO TEACHERS (
            TEACHER_CODE,
            FIRST_NAME,
            LAST_NAME,
            EMAIL,
            PHONE,
            GENDER,
            DATE_OF_BIRTH,
            JOINING_DATE,
            DESIGNATION,
            QUALIFICATION,
            DEPARTMENT,
            STATUS
        ) VALUES (
            P_TEACHER_CODE,
            P_FIRST_NAME,
            P_LAST_NAME,
            P_EMAIL,
            P_PHONE,
            UPPER(TRIM(P_GENDER)),
            P_DATE_OF_BIRTH,
            NVL(P_JOINING_DATE, SYSDATE),
            P_DESIGNATION,
            P_QUALIFICATION,
            P_DEPARTMENT,
            'ACTIVE'
        )
        RETURNING TEACHER_ID INTO P_TEACHER_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20601, 'TEACHER CODE, EMAIL, OR PHONE ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20602, 'ERROR ADDING TEACHER: ' || SQLERRM);
    END ADD_TEACHER;


    PROCEDURE UPDATE_TEACHER (
        P_TEACHER_ID     IN TEACHERS.TEACHER_ID%TYPE,
        P_FIRST_NAME     IN TEACHERS.FIRST_NAME%TYPE,
        P_LAST_NAME      IN TEACHERS.LAST_NAME%TYPE,
        P_EMAIL          IN TEACHERS.EMAIL%TYPE,
        P_PHONE          IN TEACHERS.PHONE%TYPE,
        P_GENDER         IN TEACHERS.GENDER%TYPE,
        P_DATE_OF_BIRTH  IN TEACHERS.DATE_OF_BIRTH%TYPE,
        P_JOINING_DATE   IN TEACHERS.JOINING_DATE%TYPE,
        P_DESIGNATION    IN TEACHERS.DESIGNATION%TYPE,
        P_QUALIFICATION  IN TEACHERS.QUALIFICATION%TYPE,
        P_DEPARTMENT     IN TEACHERS.DEPARTMENT%TYPE,
        P_STATUS         IN TEACHERS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE TEACHERS
        SET FIRST_NAME    = P_FIRST_NAME,
            LAST_NAME     = P_LAST_NAME,
            EMAIL         = P_EMAIL,
            PHONE         = P_PHONE,
            GENDER        = UPPER(TRIM(P_GENDER)),
            DATE_OF_BIRTH = P_DATE_OF_BIRTH,
            JOINING_DATE  = P_JOINING_DATE,
            DESIGNATION   = P_DESIGNATION,
            QUALIFICATION = P_QUALIFICATION,
            DEPARTMENT    = P_DEPARTMENT,
            STATUS        = UPPER(TRIM(P_STATUS)),
            UPDATED_AT    = SYSTIMESTAMP
        WHERE TEACHER_ID = P_TEACHER_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20603, 'TEACHER NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20604, 'TEACHER EMAIL OR PHONE ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20605, 'ERROR UPDATING TEACHER: ' || SQLERRM);
    END UPDATE_TEACHER;


    PROCEDURE DELETE_TEACHER (
        P_TEACHER_ID IN TEACHERS.TEACHER_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM TEACHER_CONTACTS
        WHERE TEACHER_ID = P_TEACHER_ID;

        DELETE FROM TEACHER_ADDRESSES
        WHERE TEACHER_ID = P_TEACHER_ID;

        DELETE FROM TEACHERS
        WHERE TEACHER_ID = P_TEACHER_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20606, 'TEACHER NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20607, 'ERROR DELETING TEACHER: ' || SQLERRM);
    END DELETE_TEACHER;


    PROCEDURE GET_TEACHER_BY_ID (
        P_TEACHER_ID IN TEACHERS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT TEACHER_ID,
                   TEACHER_CODE,
                   FIRST_NAME,
                   LAST_NAME,
                   EMAIL,
                   PHONE,
                   GENDER,
                   DATE_OF_BIRTH,
                   JOINING_DATE,
                   DESIGNATION,
                   QUALIFICATION,
                   DEPARTMENT,
                   STATUS,
                   CREATED_AT,
                   UPDATED_AT
            FROM TEACHERS
            WHERE TEACHER_ID = P_TEACHER_ID;
    END GET_TEACHER_BY_ID;


    PROCEDURE GET_ALL_TEACHERS (
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT TEACHER_ID,
                   TEACHER_CODE,
                   FIRST_NAME,
                   LAST_NAME,
                   EMAIL,
                   PHONE,
                   GENDER,
                   DATE_OF_BIRTH,
                   JOINING_DATE,
                   DESIGNATION,
                   QUALIFICATION,
                   DEPARTMENT,
                   STATUS,
                   CREATED_AT,
                   UPDATED_AT
            FROM TEACHERS
            ORDER BY TEACHER_ID DESC;
    END GET_ALL_TEACHERS;


    PROCEDURE SEARCH_TEACHERS (
        P_SEARCH_TEXT IN VARCHAR2,
        P_RESULT      OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT TEACHER_ID,
                   TEACHER_CODE,
                   FIRST_NAME,
                   LAST_NAME,
                   EMAIL,
                   PHONE,
                   GENDER,
                   DATE_OF_BIRTH,
                   JOINING_DATE,
                   DESIGNATION,
                   QUALIFICATION,
                   DEPARTMENT,
                   STATUS,
                   CREATED_AT,
                   UPDATED_AT
            FROM TEACHERS
            WHERE LOWER(TEACHER_CODE) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(FIRST_NAME) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(LAST_NAME) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(EMAIL) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(PHONE) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(DESIGNATION) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(DEPARTMENT) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
            ORDER BY TEACHER_ID DESC;
    END SEARCH_TEACHERS;

END TEACHER_PKG;
/
