---------------------------------------------------------------
-- CREATE TEACHER_ADDRESS_PKG SPECIFICATION
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE TEACHER_ADDRESS_PKG AS

    PROCEDURE ADD_ADDRESS (
        P_TEACHER_ID     IN TEACHER_ADDRESSES.TEACHER_ID%TYPE,
        P_ADDRESS_TYPE   IN TEACHER_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN TEACHER_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN TEACHER_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN TEACHER_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN TEACHER_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN TEACHER_ADDRESSES.COUNTRY%TYPE,
        P_ADDRESS_ID     OUT TEACHER_ADDRESSES.ADDRESS_ID%TYPE
    );

    PROCEDURE UPDATE_ADDRESS (
        P_ADDRESS_ID     IN TEACHER_ADDRESSES.ADDRESS_ID%TYPE,
        P_ADDRESS_TYPE   IN TEACHER_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN TEACHER_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN TEACHER_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN TEACHER_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN TEACHER_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN TEACHER_ADDRESSES.COUNTRY%TYPE
    );

    PROCEDURE DELETE_ADDRESS (
        P_ADDRESS_ID IN TEACHER_ADDRESSES.ADDRESS_ID%TYPE
    );

    PROCEDURE GET_ADDRESSES_BY_TEACHER (
        P_TEACHER_ID IN TEACHER_ADDRESSES.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

END TEACHER_ADDRESS_PKG;
/

---------------------------------------------------------------
-- CREATE TEACHER_ADDRESS_PKG BODY
---------------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY TEACHER_ADDRESS_PKG AS
    PROCEDURE ADD_ADDRESS (
        P_TEACHER_ID     IN TEACHER_ADDRESSES.TEACHER_ID%TYPE,
        P_ADDRESS_TYPE   IN TEACHER_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN TEACHER_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN TEACHER_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN TEACHER_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN TEACHER_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN TEACHER_ADDRESSES.COUNTRY%TYPE,
        P_ADDRESS_ID     OUT TEACHER_ADDRESSES.ADDRESS_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO TEACHER_ADDRESSES (
            TEACHER_ID,
            ADDRESS_TYPE,
            ADDRESS_LINE,
            CITY,
            DISTRICT,
            POSTAL_CODE,
            COUNTRY
        ) VALUES (
            P_TEACHER_ID,
            UPPER(TRIM(P_ADDRESS_TYPE)),
            P_ADDRESS_LINE,
            P_CITY,
            P_DISTRICT,
            P_POSTAL_CODE,
            NVL(P_COUNTRY, 'Bangladesh')
        )
        RETURNING ADDRESS_ID INTO P_ADDRESS_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20701,
                'TEACHER ALREADY HAS THIS ADDRESS TYPE.'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20702,
                'ERROR ADDING TEACHER ADDRESS: ' || SQLERRM
            );
    END ADD_ADDRESS;

    PROCEDURE UPDATE_ADDRESS (
        P_ADDRESS_ID     IN TEACHER_ADDRESSES.ADDRESS_ID%TYPE,
        P_ADDRESS_TYPE   IN TEACHER_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN TEACHER_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN TEACHER_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN TEACHER_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN TEACHER_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN TEACHER_ADDRESSES.COUNTRY%TYPE
    ) AS
    BEGIN
        UPDATE TEACHER_ADDRESSES
        SET ADDRESS_TYPE = UPPER(TRIM(P_ADDRESS_TYPE)),
            ADDRESS_LINE = P_ADDRESS_LINE,
            CITY         = P_CITY,
            DISTRICT     = P_DISTRICT,
            POSTAL_CODE  = P_POSTAL_CODE,
            COUNTRY      = NVL(P_COUNTRY, 'Bangladesh'),
            UPDATED_AT   = SYSTIMESTAMP
        WHERE ADDRESS_ID = P_ADDRESS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20703,
                'TEACHER ADDRESS NOT FOUND.'
            );
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20704,
                'TEACHER ALREADY HAS THIS ADDRESS TYPE.'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20705,
                'ERROR UPDATING TEACHER ADDRESS: ' || SQLERRM
            );
    END UPDATE_ADDRESS;

    PROCEDURE DELETE_ADDRESS (
        P_ADDRESS_ID IN TEACHER_ADDRESSES.ADDRESS_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM TEACHER_ADDRESSES
        WHERE ADDRESS_ID = P_ADDRESS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20706,
                'TEACHER ADDRESS NOT FOUND.'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20707,
                'ERROR DELETING TEACHER ADDRESS: ' || SQLERRM
            );
    END DELETE_ADDRESS;

    PROCEDURE GET_ADDRESSES_BY_TEACHER (
        P_TEACHER_ID IN TEACHER_ADDRESSES.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                ADDRESS_ID,
                TEACHER_ID,
                ADDRESS_TYPE,
                ADDRESS_LINE,
                CITY,
                DISTRICT,
                POSTAL_CODE,
                COUNTRY,
                CREATED_AT,
                UPDATED_AT
            FROM TEACHER_ADDRESSES
            WHERE TEACHER_ID = P_TEACHER_ID
            ORDER BY ADDRESS_ID;
    END GET_ADDRESSES_BY_TEACHER;

END TEACHER_ADDRESS_PKG;
/
