---------------------------------------------------------------
-- CREATE TEACHER_CONTACT_PKG SPECIFICATION
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE TEACHER_CONTACT_PKG AS

    PROCEDURE ADD_CONTACT (
        P_TEACHER_ID     IN TEACHER_CONTACTS.TEACHER_ID%TYPE,
        P_CONTACT_NAME   IN TEACHER_CONTACTS.CONTACT_NAME%TYPE,
        P_RELATIONSHIP   IN TEACHER_CONTACTS.RELATIONSHIP%TYPE,
        P_PHONE          IN TEACHER_CONTACTS.PHONE%TYPE,
        P_EMAIL          IN TEACHER_CONTACTS.EMAIL%TYPE,
        P_IS_PRIMARY     IN TEACHER_CONTACTS.IS_PRIMARY%TYPE,
        P_CONTACT_ID     OUT TEACHER_CONTACTS.CONTACT_ID%TYPE
    );

    PROCEDURE UPDATE_CONTACT (
        P_CONTACT_ID     IN TEACHER_CONTACTS.CONTACT_ID%TYPE,
        P_CONTACT_NAME   IN TEACHER_CONTACTS.CONTACT_NAME%TYPE,
        P_RELATIONSHIP   IN TEACHER_CONTACTS.RELATIONSHIP%TYPE,
        P_PHONE          IN TEACHER_CONTACTS.PHONE%TYPE,
        P_EMAIL          IN TEACHER_CONTACTS.EMAIL%TYPE,
        P_IS_PRIMARY     IN TEACHER_CONTACTS.IS_PRIMARY%TYPE
    );

    PROCEDURE DELETE_CONTACT (
        P_CONTACT_ID IN TEACHER_CONTACTS.CONTACT_ID%TYPE
    );

    PROCEDURE GET_CONTACTS_BY_TEACHER (
        P_TEACHER_ID IN TEACHER_CONTACTS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

END TEACHER_CONTACT_PKG;
/

---------------------------------------------------------------
-- CREATE TEACHER_CONTACT_PKG BODY
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY TEACHER_CONTACT_PKG AS

    PROCEDURE ADD_CONTACT (
        P_TEACHER_ID     IN TEACHER_CONTACTS.TEACHER_ID%TYPE,
        P_CONTACT_NAME   IN TEACHER_CONTACTS.CONTACT_NAME%TYPE,
        P_RELATIONSHIP   IN TEACHER_CONTACTS.RELATIONSHIP%TYPE,
        P_PHONE          IN TEACHER_CONTACTS.PHONE%TYPE,
        P_EMAIL          IN TEACHER_CONTACTS.EMAIL%TYPE,
        P_IS_PRIMARY     IN TEACHER_CONTACTS.IS_PRIMARY%TYPE,
        P_CONTACT_ID     OUT TEACHER_CONTACTS.CONTACT_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO TEACHER_CONTACTS (
            TEACHER_ID,
            CONTACT_NAME,
            RELATIONSHIP,
            PHONE,
            EMAIL,
            IS_PRIMARY
        ) VALUES (
            P_TEACHER_ID,
            P_CONTACT_NAME,
            P_RELATIONSHIP,
            P_PHONE,
            P_EMAIL,
            NVL(UPPER(TRIM(P_IS_PRIMARY)), 'N')
        )
        RETURNING CONTACT_ID INTO P_CONTACT_ID;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20801,
                'ERROR ADDING TEACHER CONTACT: ' || SQLERRM
            );
    END ADD_CONTACT;

    PROCEDURE UPDATE_CONTACT (
        P_CONTACT_ID     IN TEACHER_CONTACTS.CONTACT_ID%TYPE,
        P_CONTACT_NAME   IN TEACHER_CONTACTS.CONTACT_NAME%TYPE,
        P_RELATIONSHIP   IN TEACHER_CONTACTS.RELATIONSHIP%TYPE,
        P_PHONE          IN TEACHER_CONTACTS.PHONE%TYPE,
        P_EMAIL          IN TEACHER_CONTACTS.EMAIL%TYPE,
        P_IS_PRIMARY     IN TEACHER_CONTACTS.IS_PRIMARY%TYPE
    ) AS
    BEGIN
        UPDATE TEACHER_CONTACTS
        SET CONTACT_NAME = P_CONTACT_NAME,
            RELATIONSHIP = P_RELATIONSHIP,
            PHONE        = P_PHONE,
            EMAIL        = P_EMAIL,
            IS_PRIMARY   = NVL(UPPER(TRIM(P_IS_PRIMARY)), 'N'),
            UPDATED_AT   = SYSTIMESTAMP
        WHERE CONTACT_ID = P_CONTACT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20802,
                'TEACHER CONTACT NOT FOUND.'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20803,
                'ERROR UPDATING TEACHER CONTACT: ' || SQLERRM
            );
    END UPDATE_CONTACT;

    PROCEDURE DELETE_CONTACT (
        P_CONTACT_ID IN TEACHER_CONTACTS.CONTACT_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM TEACHER_CONTACTS
        WHERE CONTACT_ID = P_CONTACT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20804,
                'TEACHER CONTACT NOT FOUND.'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20805,
                'ERROR DELETING TEACHER CONTACT: ' || SQLERRM
            );
    END DELETE_CONTACT;

    PROCEDURE GET_CONTACTS_BY_TEACHER (
        P_TEACHER_ID IN TEACHER_CONTACTS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                CONTACT_ID,
                TEACHER_ID,
                CONTACT_NAME,
                RELATIONSHIP,
                PHONE,
                EMAIL,
                IS_PRIMARY,
                CREATED_AT,
                UPDATED_AT
            FROM TEACHER_CONTACTS
            WHERE TEACHER_ID = P_TEACHER_ID
            ORDER BY
                CASE
                    WHEN IS_PRIMARY = 'Y' THEN 0
                    ELSE 1
                END,
                CONTACT_ID;
    END GET_CONTACTS_BY_TEACHER;

END TEACHER_CONTACT_PKG;
/
