# =========================
# APPLICATION CONFIG
# =========================
spring.application.name=student-management
server.port=8085

# =========================
# ORACLE DATABASE CONFIG
# =========================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=STUMGT
spring.datasource.password=Sql054003
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =========================
# HIKARI CONNECTION POOL
# =========================
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=2000000
spring.datasource.hikari.connection-timeout=30000

# =========================
# JPA (NOT USED BUT SAFE TO IGNORE WARNINGS)
# =========================
spring.jpa.hibernate.ddl-auto=none

# =========================
# LOGGING
# =========================
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.com.jakirbd=DEBUG
