--------------------------------------------------------------
-- Create Roles Table
--------------------------------------------------------------
CREATE TABLE ROLES (
    ROLE_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ROLE_NAME   VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    STATUS      VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP,

    CONSTRAINT PK_ROLES PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_ROLES_NAME UNIQUE (ROLE_NAME),
    CONSTRAINT CHK_ROLES_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

--------------------------------------------------------------
-- Create Permissions Table
--------------------------------------------------------------
CREATE TABLE PERMISSIONS (
    PERMISSION_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    PERMISSION_CODE VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP,

    CONSTRAINT PK_PERMISSIONS PRIMARY KEY (PERMISSION_ID),
    CONSTRAINT UK_PERMISSIONS_CODE UNIQUE (PERMISSION_CODE),
    CONSTRAINT CHK_PERMISSIONS_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

--------------------------------------------------------------
-- Create User Roles Table
--------------------------------------------------------------
CREATE TABLE USER_ROLES (
    USER_ID     NUMBER NOT NULL,
    ROLE_ID     NUMBER NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_USER_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID)
);

--------------------------------------------------------------
-- Create Role Permissions Table
--------------------------------------------------------------
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID       NUMBER NOT NULL,
    PERMISSION_ID NUMBER NOT NULL,
    ASSIGNED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ROLE_PERMISSIONS PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_ROLE_PERMISSIONS_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID),
    CONSTRAINT FK_ROLE_PERMISSIONS_PERMISSION FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSIONS(PERMISSION_ID)
);

--------------------------------------------------------------
-- Insert Default Roles
--------------------------------------------------------------
INSERT INTO ROLES (ROLE_NAME, DESCRIPTION) VALUES
('ADMIN', 'System administrator with full access'),
('PRINCIPAL', 'School principal'),
('TEACHER', 'Teacher user'),
('STUDENT', 'Student user'),
('PARENT', 'Parent user'),
('ACCOUNTANT', 'Accountant user');

COMMIT;

SELECT * FROM ROLES;

--------------------------------------------------------------
-- Insert Default Permissions
--------------------------------------------------------------
INSERT INTO PERMISSIONS (PERMISSION_CODE, DESCRIPTION) VALUES
('USER_MANAGE', 'Create, update, lock, and unlock users'),
('ROLE_MANAGE', 'Create and update roles'),
('STUDENT_VIEW', 'View student information'),
('STUDENT_MANAGE', 'Create, update, and delete students'),
('ATTENDANCE_MANAGE', 'Manage student attendance'),
('EXAM_MANAGE', 'Manage exams and results'),
('FEE_MANAGE', 'Manage student fees'),
('REPORT_VIEW', 'View reports');

COMMIT;

SELECT * FROM PERMISSIONS;
