--------------------------------------------------------
-- V10__create_subject_management_packages.sql
-- Subject Management PL/SQL Packages
--------------------------------------------------------


--------------------------------------------------------
-- 1. SUBJECT_PKG - PACKAGE SPECIFICATION
--------------------------------------------------------

CREATE OR REPLACE PACKAGE SUBJECT_PKG AS

    PROCEDURE CREATE_SUBJECT(
        P_SUBJECT_NAME    IN  SUBJECTS.SUBJECT_NAME%TYPE,
        P_SUBJECT_CODE    IN  SUBJECTS.SUBJECT_CODE%TYPE,
        P_SUBJECT_TYPE    IN  SUBJECTS.SUBJECT_TYPE%TYPE,
        P_DESCRIPTION     IN  SUBJECTS.DESCRIPTION%TYPE,
        P_DISPLAY_ORDER   IN  SUBJECTS.DISPLAY_ORDER%TYPE,
        P_STATUS          IN  SUBJECTS.STATUS%TYPE,
        P_SUBJECT_ID      OUT SUBJECTS.SUBJECT_ID%TYPE
    );

    PROCEDURE UPDATE_SUBJECT(
        P_SUBJECT_ID      IN SUBJECTS.SUBJECT_ID%TYPE,
        P_SUBJECT_NAME    IN SUBJECTS.SUBJECT_NAME%TYPE,
        P_SUBJECT_CODE    IN SUBJECTS.SUBJECT_CODE%TYPE,
        P_SUBJECT_TYPE    IN SUBJECTS.SUBJECT_TYPE%TYPE,
        P_DESCRIPTION     IN SUBJECTS.DESCRIPTION%TYPE,
        P_DISPLAY_ORDER   IN SUBJECTS.DISPLAY_ORDER%TYPE,
        P_STATUS          IN SUBJECTS.STATUS%TYPE
    );

    PROCEDURE GET_SUBJECT_BY_ID(
        P_SUBJECT_ID IN  SUBJECTS.SUBJECT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_SUBJECTS(
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE DELETE_SUBJECT(
        P_SUBJECT_ID IN SUBJECTS.SUBJECT_ID%TYPE
    );

END SUBJECT_PKG;
/


--------------------------------------------------------
-- 1. SUBJECT_PKG - PACKAGE BODY
--------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY SUBJECT_PKG AS

    PROCEDURE CREATE_SUBJECT(
        P_SUBJECT_NAME    IN  SUBJECTS.SUBJECT_NAME%TYPE,
        P_SUBJECT_CODE    IN  SUBJECTS.SUBJECT_CODE%TYPE,
        P_SUBJECT_TYPE    IN  SUBJECTS.SUBJECT_TYPE%TYPE,
        P_DESCRIPTION     IN  SUBJECTS.DESCRIPTION%TYPE,
        P_DISPLAY_ORDER   IN  SUBJECTS.DISPLAY_ORDER%TYPE,
        P_STATUS          IN  SUBJECTS.STATUS%TYPE,
        P_SUBJECT_ID      OUT SUBJECTS.SUBJECT_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO SUBJECTS (
            SUBJECT_NAME,
            SUBJECT_CODE,
            SUBJECT_TYPE,
            DESCRIPTION,
            DISPLAY_ORDER,
            STATUS
        )
        VALUES (
            TRIM(P_SUBJECT_NAME),
            UPPER(TRIM(P_SUBJECT_CODE)),
            UPPER(TRIM(P_SUBJECT_TYPE)),
            P_DESCRIPTION,
            P_DISPLAY_ORDER,
            UPPER(TRIM(P_STATUS))
        )
        RETURNING SUBJECT_ID INTO P_SUBJECT_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20101,
                'SUBJECT CODE ALREADY EXISTS'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20801,
                'ERROR CREATING SUBJECT: ' || SQLERRM
            );
    END CREATE_SUBJECT;


    PROCEDURE UPDATE_SUBJECT(
        P_SUBJECT_ID      IN SUBJECTS.SUBJECT_ID%TYPE,
        P_SUBJECT_NAME    IN SUBJECTS.SUBJECT_NAME%TYPE,
        P_SUBJECT_CODE    IN SUBJECTS.SUBJECT_CODE%TYPE,
        P_SUBJECT_TYPE    IN SUBJECTS.SUBJECT_TYPE%TYPE,
        P_DESCRIPTION     IN SUBJECTS.DESCRIPTION%TYPE,
        P_DISPLAY_ORDER   IN SUBJECTS.DISPLAY_ORDER%TYPE,
        P_STATUS          IN SUBJECTS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE SUBJECTS
           SET SUBJECT_NAME  = TRIM(P_SUBJECT_NAME),
               SUBJECT_CODE  = UPPER(TRIM(P_SUBJECT_CODE)),
               SUBJECT_TYPE  = UPPER(TRIM(P_SUBJECT_TYPE)),
               DESCRIPTION   = P_DESCRIPTION,
               DISPLAY_ORDER = P_DISPLAY_ORDER,
               STATUS        = UPPER(TRIM(P_STATUS)),
               UPDATED_AT    = SYSTIMESTAMP
         WHERE SUBJECT_ID = P_SUBJECT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20102,
                'SUBJECT NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20101,
                'SUBJECT CODE ALREADY EXISTS'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20802,
                'ERROR UPDATING SUBJECT: ' || SQLERRM
            );
    END UPDATE_SUBJECT;


    PROCEDURE GET_SUBJECT_BY_ID(
        P_SUBJECT_ID IN  SUBJECTS.SUBJECT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM SUBJECTS
         WHERE SUBJECT_ID = P_SUBJECT_ID;

        IF V_COUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20102,
                'SUBJECT NOT FOUND'
            );
        END IF;

        OPEN P_RESULT FOR
            SELECT
                SUBJECT_ID,
                SUBJECT_NAME,
                SUBJECT_CODE,
                SUBJECT_TYPE,
                DESCRIPTION,
                DISPLAY_ORDER,
                STATUS,
                CREATED_AT,
                UPDATED_AT
            FROM SUBJECTS
            WHERE SUBJECT_ID = P_SUBJECT_ID;

    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20803,
                'ERROR FETCHING SUBJECT: ' || SQLERRM
            );
    END GET_SUBJECT_BY_ID;


    PROCEDURE GET_ALL_SUBJECTS(
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SUBJECT_ID,
                SUBJECT_NAME,
                SUBJECT_CODE,
                SUBJECT_TYPE,
                DESCRIPTION,
                DISPLAY_ORDER,
                STATUS,
                CREATED_AT,
                UPDATED_AT
            FROM SUBJECTS
            ORDER BY
                NVL(DISPLAY_ORDER, 99999),
                SUBJECT_NAME;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20804,
                'ERROR FETCHING SUBJECTS: ' || SQLERRM
            );
    END GET_ALL_SUBJECTS;


    PROCEDURE DELETE_SUBJECT(
        P_SUBJECT_ID IN SUBJECTS.SUBJECT_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM SUBJECTS
        WHERE SUBJECT_ID = P_SUBJECT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20102,
                'SUBJECT NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20805,
                'ERROR DELETING SUBJECT: ' || SQLERRM
            );
    END DELETE_SUBJECT;

END SUBJECT_PKG;
/


--------------------------------------------------------
-- 2. CLASS_SUBJECT_PKG - PACKAGE SPECIFICATION
--------------------------------------------------------

CREATE OR REPLACE PACKAGE CLASS_SUBJECT_PKG AS

    PROCEDURE CREATE_CLASS_SUBJECT(
        P_ACADEMIC_YEAR_CLASS_ID IN  CLASS_SUBJECTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SUBJECT_ID             IN  CLASS_SUBJECTS.SUBJECT_ID%TYPE,
        P_IS_MANDATORY           IN  CLASS_SUBJECTS.IS_MANDATORY%TYPE,
        P_FULL_MARKS             IN  CLASS_SUBJECTS.FULL_MARKS%TYPE,
        P_PASS_MARKS             IN  CLASS_SUBJECTS.PASS_MARKS%TYPE,
        P_DISPLAY_ORDER          IN  CLASS_SUBJECTS.DISPLAY_ORDER%TYPE,
        P_STATUS                 IN  CLASS_SUBJECTS.STATUS%TYPE,
        P_CLASS_SUBJECT_ID       OUT CLASS_SUBJECTS.CLASS_SUBJECT_ID%TYPE
    );

    PROCEDURE UPDATE_CLASS_SUBJECT(
        P_CLASS_SUBJECT_ID       IN CLASS_SUBJECTS.CLASS_SUBJECT_ID%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID IN CLASS_SUBJECTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SUBJECT_ID             IN CLASS_SUBJECTS.SUBJECT_ID%TYPE,
        P_IS_MANDATORY           IN CLASS_SUBJECTS.IS_MANDATORY%TYPE,
        P_FULL_MARKS             IN CLASS_SUBJECTS.FULL_MARKS%TYPE,
        P_PASS_MARKS             IN CLASS_SUBJECTS.PASS_MARKS%TYPE,
        P_DISPLAY_ORDER          IN CLASS_SUBJECTS.DISPLAY_ORDER%TYPE,
        P_STATUS                 IN CLASS_SUBJECTS.STATUS%TYPE
    );

    PROCEDURE GET_CLASS_SUBJECT_BY_ID(
        P_CLASS_SUBJECT_ID IN  CLASS_SUBJECTS.CLASS_SUBJECT_ID%TYPE,
        P_RESULT           OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_CLASS_SUBJECTS(
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_SUBJECTS_BY_ACADEMIC_CLASS(
        P_ACADEMIC_YEAR_CLASS_ID IN  CLASS_SUBJECTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_RESULT                 OUT SYS_REFCURSOR
    );

    PROCEDURE DELETE_CLASS_SUBJECT(
        P_CLASS_SUBJECT_ID IN CLASS_SUBJECTS.CLASS_SUBJECT_ID%TYPE
    );

END CLASS_SUBJECT_PKG;
/


--------------------------------------------------------
-- 2. CLASS_SUBJECT_PKG - PACKAGE BODY
--------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY CLASS_SUBJECT_PKG AS

    PROCEDURE CREATE_CLASS_SUBJECT(
        P_ACADEMIC_YEAR_CLASS_ID IN  CLASS_SUBJECTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SUBJECT_ID             IN  CLASS_SUBJECTS.SUBJECT_ID%TYPE,
        P_IS_MANDATORY           IN  CLASS_SUBJECTS.IS_MANDATORY%TYPE,
        P_FULL_MARKS             IN  CLASS_SUBJECTS.FULL_MARKS%TYPE,
        P_PASS_MARKS             IN  CLASS_SUBJECTS.PASS_MARKS%TYPE,
        P_DISPLAY_ORDER          IN  CLASS_SUBJECTS.DISPLAY_ORDER%TYPE,
        P_STATUS                 IN  CLASS_SUBJECTS.STATUS%TYPE,
        P_CLASS_SUBJECT_ID       OUT CLASS_SUBJECTS.CLASS_SUBJECT_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO CLASS_SUBJECTS (
            ACADEMIC_YEAR_CLASS_ID,
            SUBJECT_ID,
            IS_MANDATORY,
            FULL_MARKS,
            PASS_MARKS,
            DISPLAY_ORDER,
            STATUS
        )
        VALUES (
            P_ACADEMIC_YEAR_CLASS_ID,
            P_SUBJECT_ID,
            UPPER(TRIM(P_IS_MANDATORY)),
            P_FULL_MARKS,
            P_PASS_MARKS,
            P_DISPLAY_ORDER,
            UPPER(TRIM(P_STATUS))
        )
        RETURNING CLASS_SUBJECT_ID
        INTO P_CLASS_SUBJECT_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20201,
                'SUBJECT ALREADY ASSIGNED TO ACADEMIC YEAR CLASS'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20811,
                'ERROR CREATING CLASS SUBJECT: ' || SQLERRM
            );
    END CREATE_CLASS_SUBJECT;


    PROCEDURE UPDATE_CLASS_SUBJECT(
        P_CLASS_SUBJECT_ID       IN CLASS_SUBJECTS.CLASS_SUBJECT_ID%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID IN CLASS_SUBJECTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SUBJECT_ID             IN CLASS_SUBJECTS.SUBJECT_ID%TYPE,
        P_IS_MANDATORY           IN CLASS_SUBJECTS.IS_MANDATORY%TYPE,
        P_FULL_MARKS             IN CLASS_SUBJECTS.FULL_MARKS%TYPE,
        P_PASS_MARKS             IN CLASS_SUBJECTS.PASS_MARKS%TYPE,
        P_DISPLAY_ORDER          IN CLASS_SUBJECTS.DISPLAY_ORDER%TYPE,
        P_STATUS                 IN CLASS_SUBJECTS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE CLASS_SUBJECTS
           SET ACADEMIC_YEAR_CLASS_ID = P_ACADEMIC_YEAR_CLASS_ID,
               SUBJECT_ID             = P_SUBJECT_ID,
               IS_MANDATORY           = UPPER(TRIM(P_IS_MANDATORY)),
               FULL_MARKS             = P_FULL_MARKS,
               PASS_MARKS             = P_PASS_MARKS,
               DISPLAY_ORDER          = P_DISPLAY_ORDER,
               STATUS                 = UPPER(TRIM(P_STATUS)),
               UPDATED_AT             = SYSTIMESTAMP
         WHERE CLASS_SUBJECT_ID = P_CLASS_SUBJECT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20202,
                'CLASS SUBJECT NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20201,
                'SUBJECT ALREADY ASSIGNED TO ACADEMIC YEAR CLASS'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20812,
                'ERROR UPDATING CLASS SUBJECT: ' || SQLERRM
            );
    END UPDATE_CLASS_SUBJECT;


    PROCEDURE GET_CLASS_SUBJECT_BY_ID(
        P_CLASS_SUBJECT_ID IN  CLASS_SUBJECTS.CLASS_SUBJECT_ID%TYPE,
        P_RESULT           OUT SYS_REFCURSOR
    ) AS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM CLASS_SUBJECTS
         WHERE CLASS_SUBJECT_ID = P_CLASS_SUBJECT_ID;

        IF V_COUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20202,
                'CLASS SUBJECT NOT FOUND'
            );
        END IF;

        OPEN P_RESULT FOR
            SELECT
                CS.CLASS_SUBJECT_ID,
                CS.ACADEMIC_YEAR_CLASS_ID,
                CS.SUBJECT_ID,
                S.SUBJECT_NAME,
                S.SUBJECT_CODE,
                S.SUBJECT_TYPE,
                CS.IS_MANDATORY,
                CS.FULL_MARKS,
                CS.PASS_MARKS,
                CS.DISPLAY_ORDER,
                CS.STATUS,
                CS.CREATED_AT,
                CS.UPDATED_AT
            FROM CLASS_SUBJECTS CS
            JOIN SUBJECTS S
              ON S.SUBJECT_ID = CS.SUBJECT_ID
            WHERE CS.CLASS_SUBJECT_ID = P_CLASS_SUBJECT_ID;

    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20813,
                'ERROR FETCHING CLASS SUBJECT: ' || SQLERRM
            );
    END GET_CLASS_SUBJECT_BY_ID;


    PROCEDURE GET_ALL_CLASS_SUBJECTS(
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                CS.CLASS_SUBJECT_ID,
                CS.ACADEMIC_YEAR_CLASS_ID,
                CS.SUBJECT_ID,
                S.SUBJECT_NAME,
                S.SUBJECT_CODE,
                S.SUBJECT_TYPE,
                CS.IS_MANDATORY,
                CS.FULL_MARKS,
                CS.PASS_MARKS,
                CS.DISPLAY_ORDER,
                CS.STATUS,
                CS.CREATED_AT,
                CS.UPDATED_AT
            FROM CLASS_SUBJECTS CS
            JOIN SUBJECTS S
              ON S.SUBJECT_ID = CS.SUBJECT_ID
            ORDER BY
                CS.ACADEMIC_YEAR_CLASS_ID,
                NVL(CS.DISPLAY_ORDER, 99999),
                S.SUBJECT_NAME;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20814,
                'ERROR FETCHING CLASS SUBJECTS: ' || SQLERRM
            );
    END GET_ALL_CLASS_SUBJECTS;


    PROCEDURE GET_SUBJECTS_BY_ACADEMIC_CLASS(
        P_ACADEMIC_YEAR_CLASS_ID IN  CLASS_SUBJECTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_RESULT                 OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                CS.CLASS_SUBJECT_ID,
                CS.ACADEMIC_YEAR_CLASS_ID,
                CS.SUBJECT_ID,
                S.SUBJECT_NAME,
                S.SUBJECT_CODE,
                S.SUBJECT_TYPE,
                CS.IS_MANDATORY,
                CS.FULL_MARKS,
                CS.PASS_MARKS,
                CS.DISPLAY_ORDER,
                CS.STATUS,
                CS.CREATED_AT,
                CS.UPDATED_AT
            FROM CLASS_SUBJECTS CS
            JOIN SUBJECTS S
              ON S.SUBJECT_ID = CS.SUBJECT_ID
            WHERE CS.ACADEMIC_YEAR_CLASS_ID =
                  P_ACADEMIC_YEAR_CLASS_ID
            ORDER BY
                NVL(CS.DISPLAY_ORDER, 99999),
                S.SUBJECT_NAME;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20815,
                'ERROR FETCHING SUBJECTS BY ACADEMIC CLASS: '
                || SQLERRM
            );
    END GET_SUBJECTS_BY_ACADEMIC_CLASS;


    PROCEDURE DELETE_CLASS_SUBJECT(
        P_CLASS_SUBJECT_ID IN CLASS_SUBJECTS.CLASS_SUBJECT_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM CLASS_SUBJECTS
        WHERE CLASS_SUBJECT_ID = P_CLASS_SUBJECT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20202,
                'CLASS SUBJECT NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20816,
                'ERROR DELETING CLASS SUBJECT: ' || SQLERRM
            );
    END DELETE_CLASS_SUBJECT;

END CLASS_SUBJECT_PKG;
/


--------------------------------------------------------
-- 3. TEACHER_SUBJECT_ASSIGNMENT_PKG - PACKAGE SPECIFICATION
--------------------------------------------------------

CREATE OR REPLACE PACKAGE TEACHER_SUBJECT_ASSIGNMENT_PKG AS

    PROCEDURE CREATE_ASSIGNMENT(
        P_CLASS_SUBJECT_ID IN  TEACHER_SUBJECT_ASSIGNMENTS.CLASS_SUBJECT_ID%TYPE,
        P_SECTION_SHIFT_ID IN  TEACHER_SUBJECT_ASSIGNMENTS.SECTION_SHIFT_ID%TYPE,
        P_TEACHER_ID       IN  TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_ID%TYPE,
        P_ASSIGNMENT_TYPE  IN  TEACHER_SUBJECT_ASSIGNMENTS.ASSIGNMENT_TYPE%TYPE,
        P_STATUS           IN  TEACHER_SUBJECT_ASSIGNMENTS.STATUS%TYPE,
        P_ASSIGNMENT_ID    OUT TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_SUBJECT_ASSIGNMENT_ID%TYPE
    );

    PROCEDURE UPDATE_ASSIGNMENT(
        P_ASSIGNMENT_ID    IN TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_SUBJECT_ASSIGNMENT_ID%TYPE,
        P_CLASS_SUBJECT_ID IN TEACHER_SUBJECT_ASSIGNMENTS.CLASS_SUBJECT_ID%TYPE,
        P_SECTION_SHIFT_ID IN TEACHER_SUBJECT_ASSIGNMENTS.SECTION_SHIFT_ID%TYPE,
        P_TEACHER_ID       IN TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_ID%TYPE,
        P_ASSIGNMENT_TYPE  IN TEACHER_SUBJECT_ASSIGNMENTS.ASSIGNMENT_TYPE%TYPE,
        P_STATUS           IN TEACHER_SUBJECT_ASSIGNMENTS.STATUS%TYPE
    );

    PROCEDURE GET_ASSIGNMENT_BY_ID(
        P_ASSIGNMENT_ID IN  TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_SUBJECT_ASSIGNMENT_ID%TYPE,
        P_RESULT        OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_ASSIGNMENTS(
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ASSIGNMENTS_BY_TEACHER(
        P_TEACHER_ID IN  TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

    PROCEDURE DELETE_ASSIGNMENT(
        P_ASSIGNMENT_ID IN TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_SUBJECT_ASSIGNMENT_ID%TYPE
    );

END TEACHER_SUBJECT_ASSIGNMENT_PKG;
/


--------------------------------------------------------
-- 3. TEACHER_SUBJECT_ASSIGNMENT_PKG - PACKAGE BODY
--------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY TEACHER_SUBJECT_ASSIGNMENT_PKG AS

    PROCEDURE CREATE_ASSIGNMENT(
        P_CLASS_SUBJECT_ID IN  TEACHER_SUBJECT_ASSIGNMENTS.CLASS_SUBJECT_ID%TYPE,
        P_SECTION_SHIFT_ID IN  TEACHER_SUBJECT_ASSIGNMENTS.SECTION_SHIFT_ID%TYPE,
        P_TEACHER_ID       IN  TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_ID%TYPE,
        P_ASSIGNMENT_TYPE  IN  TEACHER_SUBJECT_ASSIGNMENTS.ASSIGNMENT_TYPE%TYPE,
        P_STATUS           IN  TEACHER_SUBJECT_ASSIGNMENTS.STATUS%TYPE,
        P_ASSIGNMENT_ID    OUT TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_SUBJECT_ASSIGNMENT_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO TEACHER_SUBJECT_ASSIGNMENTS (
            CLASS_SUBJECT_ID,
            SECTION_SHIFT_ID,
            TEACHER_ID,
            ASSIGNMENT_TYPE,
            STATUS
        )
        VALUES (
            P_CLASS_SUBJECT_ID,
            P_SECTION_SHIFT_ID,
            P_TEACHER_ID,
            UPPER(TRIM(P_ASSIGNMENT_TYPE)),
            UPPER(TRIM(P_STATUS))
        )
        RETURNING TEACHER_SUBJECT_ASSIGNMENT_ID
        INTO P_ASSIGNMENT_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20301,
                'TEACHER SUBJECT ASSIGNMENT ALREADY EXISTS'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20821,
                'ERROR CREATING TEACHER SUBJECT ASSIGNMENT: '
                || SQLERRM
            );
    END CREATE_ASSIGNMENT;


    PROCEDURE UPDATE_ASSIGNMENT(
        P_ASSIGNMENT_ID    IN TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_SUBJECT_ASSIGNMENT_ID%TYPE,
        P_CLASS_SUBJECT_ID IN TEACHER_SUBJECT_ASSIGNMENTS.CLASS_SUBJECT_ID%TYPE,
        P_SECTION_SHIFT_ID IN TEACHER_SUBJECT_ASSIGNMENTS.SECTION_SHIFT_ID%TYPE,
        P_TEACHER_ID       IN TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_ID%TYPE,
        P_ASSIGNMENT_TYPE  IN TEACHER_SUBJECT_ASSIGNMENTS.ASSIGNMENT_TYPE%TYPE,
        P_STATUS           IN TEACHER_SUBJECT_ASSIGNMENTS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE TEACHER_SUBJECT_ASSIGNMENTS
           SET CLASS_SUBJECT_ID = P_CLASS_SUBJECT_ID,
               SECTION_SHIFT_ID = P_SECTION_SHIFT_ID,
               TEACHER_ID       = P_TEACHER_ID,
               ASSIGNMENT_TYPE  = UPPER(TRIM(P_ASSIGNMENT_TYPE)),
               STATUS           = UPPER(TRIM(P_STATUS)),
               UPDATED_AT       = SYSTIMESTAMP
         WHERE TEACHER_SUBJECT_ASSIGNMENT_ID =
               P_ASSIGNMENT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20302,
                'TEACHER SUBJECT ASSIGNMENT NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20301,
                'TEACHER SUBJECT ASSIGNMENT ALREADY EXISTS'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20822,
                'ERROR UPDATING TEACHER SUBJECT ASSIGNMENT: '
                || SQLERRM
            );
    END UPDATE_ASSIGNMENT;


    PROCEDURE GET_ASSIGNMENT_BY_ID(
        P_ASSIGNMENT_ID IN  TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_SUBJECT_ASSIGNMENT_ID%TYPE,
        P_RESULT        OUT SYS_REFCURSOR
    ) AS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO V_COUNT
          FROM TEACHER_SUBJECT_ASSIGNMENTS
         WHERE TEACHER_SUBJECT_ASSIGNMENT_ID =
               P_ASSIGNMENT_ID;

        IF V_COUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20302,
                'TEACHER SUBJECT ASSIGNMENT NOT FOUND'
            );
        END IF;

        OPEN P_RESULT FOR
            SELECT
                TSA.TEACHER_SUBJECT_ASSIGNMENT_ID,
                TSA.CLASS_SUBJECT_ID,
                TSA.SECTION_SHIFT_ID,
                TSA.TEACHER_ID,
                S.SUBJECT_ID,
                S.SUBJECT_NAME,
                S.SUBJECT_CODE,
                TSA.ASSIGNMENT_TYPE,
                TSA.STATUS,
                TSA.CREATED_AT,
                TSA.UPDATED_AT
            FROM TEACHER_SUBJECT_ASSIGNMENTS TSA
            JOIN CLASS_SUBJECTS CS
              ON CS.CLASS_SUBJECT_ID =
                 TSA.CLASS_SUBJECT_ID
            JOIN SUBJECTS S
              ON S.SUBJECT_ID = CS.SUBJECT_ID
            WHERE TSA.TEACHER_SUBJECT_ASSIGNMENT_ID =
                  P_ASSIGNMENT_ID;

    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20823,
                'ERROR FETCHING TEACHER SUBJECT ASSIGNMENT: '
                || SQLERRM
            );
    END GET_ASSIGNMENT_BY_ID;


    PROCEDURE GET_ALL_ASSIGNMENTS(
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                TSA.TEACHER_SUBJECT_ASSIGNMENT_ID,
                TSA.CLASS_SUBJECT_ID,
                TSA.SECTION_SHIFT_ID,
                TSA.TEACHER_ID,
                S.SUBJECT_ID,
                S.SUBJECT_NAME,
                S.SUBJECT_CODE,
                TSA.ASSIGNMENT_TYPE,
                TSA.STATUS,
                TSA.CREATED_AT,
                TSA.UPDATED_AT
            FROM TEACHER_SUBJECT_ASSIGNMENTS TSA
            JOIN CLASS_SUBJECTS CS
              ON CS.CLASS_SUBJECT_ID =
                 TSA.CLASS_SUBJECT_ID
            JOIN SUBJECTS S
              ON S.SUBJECT_ID = CS.SUBJECT_ID
            ORDER BY
                TSA.TEACHER_ID,
                S.SUBJECT_NAME;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20824,
                'ERROR FETCHING TEACHER SUBJECT ASSIGNMENTS: '
                || SQLERRM
            );
    END GET_ALL_ASSIGNMENTS;


    PROCEDURE GET_ASSIGNMENTS_BY_TEACHER(
        P_TEACHER_ID IN  TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                TSA.TEACHER_SUBJECT_ASSIGNMENT_ID,
                TSA.CLASS_SUBJECT_ID,
                TSA.SECTION_SHIFT_ID,
                TSA.TEACHER_ID,
                S.SUBJECT_ID,
                S.SUBJECT_NAME,
                S.SUBJECT_CODE,
                TSA.ASSIGNMENT_TYPE,
                TSA.STATUS,
                TSA.CREATED_AT,
                TSA.UPDATED_AT
            FROM TEACHER_SUBJECT_ASSIGNMENTS TSA
            JOIN CLASS_SUBJECTS CS
              ON CS.CLASS_SUBJECT_ID =
                 TSA.CLASS_SUBJECT_ID
            JOIN SUBJECTS S
              ON S.SUBJECT_ID = CS.SUBJECT_ID
            WHERE TSA.TEACHER_ID = P_TEACHER_ID
            ORDER BY S.SUBJECT_NAME;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20825,
                'ERROR FETCHING ASSIGNMENTS BY TEACHER: '
                || SQLERRM
            );
    END GET_ASSIGNMENTS_BY_TEACHER;


    PROCEDURE DELETE_ASSIGNMENT(
        P_ASSIGNMENT_ID IN TEACHER_SUBJECT_ASSIGNMENTS.TEACHER_SUBJECT_ASSIGNMENT_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM TEACHER_SUBJECT_ASSIGNMENTS
        WHERE TEACHER_SUBJECT_ASSIGNMENT_ID =
              P_ASSIGNMENT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20302,
                'TEACHER SUBJECT ASSIGNMENT NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                -20826,
                'ERROR DELETING TEACHER SUBJECT ASSIGNMENT: '
                || SQLERRM
            );
    END DELETE_ASSIGNMENT;

END TEACHER_SUBJECT_ASSIGNMENT_PKG;
/
