--------------------------------------------------------------------------------------------
-- V11__create_attendance_management_tables.sql
-- Attendance Management Tables
--------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------
-- 1. STUDENT_ENROLLMENTS
-- Assigns a student to an academic-year class, section and shift
--------------------------------------------------------------------------------------------

CREATE TABLE STUDENT_ENROLLMENTS (
    ENROLLMENT_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    STUDENT_ID               NUMBER NOT NULL,
    ACADEMIC_YEAR_CLASS_ID   NUMBER NOT NULL,
    SECTION_SHIFT_ID         NUMBER NOT NULL,
    ROLL_NUMBER              VARCHAR2(30),
    ENROLLMENT_DATE          DATE DEFAULT SYSDATE NOT NULL,
    STATUS                   VARCHAR2(20) DEFAULT 'ENROLLED' NOT NULL,
    REMARKS                  VARCHAR2(500),
    CREATED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT               TIMESTAMP,

    CONSTRAINT PK_STUDENT_ENROLLMENTS
     PRIMARY KEY (ENROLLMENT_ID),

    CONSTRAINT FK_STUDENT_ENROLL_STUDENT
     FOREIGN KEY (STUDENT_ID)
         REFERENCES STUDENTS (STUDENT_ID),

    CONSTRAINT FK_STUDENT_ENROLL_AYC
     FOREIGN KEY (ACADEMIC_YEAR_CLASS_ID)
         REFERENCES ACADEMIC_YEAR_CLASSES (ACADEMIC_YEAR_CLASS_ID),

    CONSTRAINT FK_STUDENT_ENROLL_SECTION_SHIFT
     FOREIGN KEY (SECTION_SHIFT_ID)
         REFERENCES SECTION_SHIFTS (SECTION_SHIFT_ID),

    CONSTRAINT UK_STUDENT_ENROLLMENT
     UNIQUE (
             STUDENT_ID,
             ACADEMIC_YEAR_CLASS_ID
         ),

    CONSTRAINT UK_ENROLL_SECTION_ROLL
     UNIQUE (
             SECTION_SHIFT_ID,
             ROLL_NUMBER
         ),

    CONSTRAINT CHK_STUDENT_ENROLL_STATUS
     CHECK (
         STATUS IN (
                    'ENROLLED',
                    'TRANSFERRED',
                    'COMPLETED',
                    'WITHDRAWN'
             )
         )
);


--------------------------------------------------------------------------------------------
-- 2. ATTENDANCE_SESSIONS
-- Represents one attendance-taking event
--
-- DAILY:
--   One general attendance session for a section/shift/date
--
-- SUBJECT:
--   Attendance for a specific class subject
--------------------------------------------------------------------------------------------

CREATE TABLE ATTENDANCE_SESSIONS (
    ATTENDANCE_SESSION_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    SECTION_SHIFT_ID        NUMBER NOT NULL,
    CLASS_SUBJECT_ID        NUMBER,
    ATTENDANCE_DATE         DATE NOT NULL,
    ATTENDANCE_TYPE         VARCHAR2(20) DEFAULT 'DAILY' NOT NULL,
    PERIOD_NUMBER           NUMBER(3),
    MARKED_BY_TEACHER_ID    NUMBER,
    STATUS                  VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    REMARKS                 VARCHAR2(500),
    CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP,

    CONSTRAINT PK_ATTENDANCE_SESSIONS
     PRIMARY KEY (ATTENDANCE_SESSION_ID),

    CONSTRAINT FK_ATT_SESSION_SECTION_SHIFT
     FOREIGN KEY (SECTION_SHIFT_ID)
         REFERENCES SECTION_SHIFTS (SECTION_SHIFT_ID),

    CONSTRAINT FK_ATT_SESSION_CLASS_SUBJECT
     FOREIGN KEY (CLASS_SUBJECT_ID)
         REFERENCES CLASS_SUBJECTS (CLASS_SUBJECT_ID),

    CONSTRAINT FK_ATT_SESSION_TEACHER
     FOREIGN KEY (MARKED_BY_TEACHER_ID)
         REFERENCES TEACHERS (TEACHER_ID),

    CONSTRAINT CHK_ATT_SESSION_TYPE
     CHECK (
         ATTENDANCE_TYPE IN ('DAILY', 'SUBJECT')
         ),

    CONSTRAINT CHK_ATT_SESSION_STATUS
     CHECK (
         STATUS IN ('OPEN', 'SUBMITTED', 'LOCKED', 'CANCELLED')
         ),

    CONSTRAINT CHK_ATT_SESSION_PERIOD
     CHECK (
         PERIOD_NUMBER IS NULL
             OR PERIOD_NUMBER > 0
         ),

    CONSTRAINT CHK_ATT_SESSION_SUBJECT
     CHECK (
         (
             ATTENDANCE_TYPE = 'DAILY'
                 AND CLASS_SUBJECT_ID IS NULL
             )
             OR
         (
             ATTENDANCE_TYPE = 'SUBJECT'
                 AND CLASS_SUBJECT_ID IS NOT NULL
             )
         )
);


--------------------------------------------------------------------------------------------
-- 3. ATTENDANCE_RECORDS
-- Stores attendance for each enrolled student in a session
--------------------------------------------------------------------------------------------

CREATE TABLE ATTENDANCE_RECORDS (
    ATTENDANCE_RECORD_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ATTENDANCE_SESSION_ID   NUMBER NOT NULL,
    ENROLLMENT_ID           NUMBER NOT NULL,
    ATTENDANCE_STATUS       VARCHAR2(20) DEFAULT 'PRESENT' NOT NULL,
    CHECK_IN_TIME           TIMESTAMP,
    REMARKS                 VARCHAR2(500),
    MARKED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP,

    CONSTRAINT PK_ATTENDANCE_RECORDS
        PRIMARY KEY (ATTENDANCE_RECORD_ID),

    CONSTRAINT FK_ATT_RECORD_SESSION
        FOREIGN KEY (ATTENDANCE_SESSION_ID)
            REFERENCES ATTENDANCE_SESSIONS (ATTENDANCE_SESSION_ID),

    CONSTRAINT FK_ATT_RECORD_ENROLLMENT
        FOREIGN KEY (ENROLLMENT_ID)
            REFERENCES STUDENT_ENROLLMENTS (ENROLLMENT_ID),

    CONSTRAINT UK_ATT_RECORD_SESSION_STUDENT
        UNIQUE (
                ATTENDANCE_SESSION_ID,
                ENROLLMENT_ID
            ),

    CONSTRAINT CHK_ATT_RECORD_STATUS
        CHECK (
            ATTENDANCE_STATUS IN (
                                  'PRESENT',
                                  'ABSENT',
                                  'LATE',
                                  'LEAVE'
                )
            )
);


--------------------------------------------------------------------------------------------
-- UNIQUE INDEXES FOR ATTENDANCE SESSIONS
-- Oracle does not support partial unique constraints directly,
-- so function-based indexes are used.
--------------------------------------------------------------------------------------------


-- Only one DAILY session for a section/shift on a date

CREATE UNIQUE INDEX UK_ATT_SESSION_DAILY
    ON ATTENDANCE_SESSIONS (
        CASE
            WHEN ATTENDANCE_TYPE = 'DAILY'
                THEN SECTION_SHIFT_ID
            END,

        CASE
            WHEN ATTENDANCE_TYPE = 'DAILY'
                THEN TRUNC(ATTENDANCE_DATE)
            END
        );


-- One SUBJECT session per subject, section/shift, date and period

CREATE UNIQUE INDEX UK_ATT_SESSION_SUBJECT
    ON ATTENDANCE_SESSIONS (
        CASE
            WHEN ATTENDANCE_TYPE = 'SUBJECT'
                THEN SECTION_SHIFT_ID
            END,

        CASE
            WHEN ATTENDANCE_TYPE = 'SUBJECT'
                THEN CLASS_SUBJECT_ID
            END,

        CASE
            WHEN ATTENDANCE_TYPE = 'SUBJECT'
                THEN TRUNC(ATTENDANCE_DATE)
            END,

        CASE
            WHEN ATTENDANCE_TYPE = 'SUBJECT'
                THEN NVL(PERIOD_NUMBER, 0)
            END
        );


--------------------------------------------------------------------------------------------
-- PERFORMANCE INDEXES
--------------------------------------------------------------------------------------------

CREATE INDEX IDX_STUDENT_ENROLL_STUDENT
    ON STUDENT_ENROLLMENTS (STUDENT_ID);

CREATE INDEX IDX_STUDENT_ENROLL_AYC
    ON STUDENT_ENROLLMENTS (ACADEMIC_YEAR_CLASS_ID);

CREATE INDEX IDX_STUDENT_ENROLL_SECTION
    ON STUDENT_ENROLLMENTS (SECTION_SHIFT_ID);

CREATE INDEX IDX_ATT_SESSION_DATE
    ON ATTENDANCE_SESSIONS (ATTENDANCE_DATE);

CREATE INDEX IDX_ATT_SESSION_SECTION
    ON ATTENDANCE_SESSIONS (SECTION_SHIFT_ID);

CREATE INDEX IDX_ATT_SESSION_SUBJECT
    ON ATTENDANCE_SESSIONS (CLASS_SUBJECT_ID);

CREATE INDEX IDX_ATT_SESSION_TEACHER
    ON ATTENDANCE_SESSIONS (MARKED_BY_TEACHER_ID);

CREATE INDEX IDX_ATT_RECORD_SESSION
    ON ATTENDANCE_RECORDS (ATTENDANCE_SESSION_ID);

CREATE INDEX IDX_ATT_RECORD_ENROLLMENT
    ON ATTENDANCE_RECORDS (ENROLLMENT_ID);

CREATE INDEX IDX_ATT_RECORD_STATUS
    ON ATTENDANCE_RECORDS (ATTENDANCE_STATUS);