-- ============================================================
-- V12__create_attendance_management_packages.sql
-- Attendance Management PL/SQL Packages
-- ============================================================


-- ============================================================
-- 1. STUDENT_ENROLLMENT_PKG
-- ============================================================

CREATE OR REPLACE PACKAGE STUDENT_ENROLLMENT_PKG AS

    PROCEDURE CREATE_ENROLLMENT(
        P_STUDENT_ID              IN  STUDENT_ENROLLMENTS.STUDENT_ID%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID  IN  STUDENT_ENROLLMENTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SECTION_SHIFT_ID        IN  STUDENT_ENROLLMENTS.SECTION_SHIFT_ID%TYPE,
        P_ROLL_NUMBER             IN  STUDENT_ENROLLMENTS.ROLL_NUMBER%TYPE,
        P_ENROLLMENT_DATE         IN  STUDENT_ENROLLMENTS.ENROLLMENT_DATE%TYPE,
        P_STATUS                  IN  STUDENT_ENROLLMENTS.STATUS%TYPE,
        P_REMARKS                 IN  STUDENT_ENROLLMENTS.REMARKS%TYPE,
        P_ENROLLMENT_ID           OUT STUDENT_ENROLLMENTS.ENROLLMENT_ID%TYPE
    );

    PROCEDURE UPDATE_ENROLLMENT(
        P_ENROLLMENT_ID           IN STUDENT_ENROLLMENTS.ENROLLMENT_ID%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID  IN STUDENT_ENROLLMENTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SECTION_SHIFT_ID        IN STUDENT_ENROLLMENTS.SECTION_SHIFT_ID%TYPE,
        P_ROLL_NUMBER             IN STUDENT_ENROLLMENTS.ROLL_NUMBER%TYPE,
        P_ENROLLMENT_DATE         IN STUDENT_ENROLLMENTS.ENROLLMENT_DATE%TYPE,
        P_STATUS                  IN STUDENT_ENROLLMENTS.STATUS%TYPE,
        P_REMARKS                 IN STUDENT_ENROLLMENTS.REMARKS%TYPE
    );

    PROCEDURE GET_ENROLLMENT_BY_ID(
        P_ENROLLMENT_ID IN  STUDENT_ENROLLMENTS.ENROLLMENT_ID%TYPE,
        P_RESULT        OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_ENROLLMENTS(
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ENROLLMENTS_BY_STUDENT(
        P_STUDENT_ID IN  STUDENT_ENROLLMENTS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ENROLLMENTS_BY_SECTION_SHIFT(
        P_SECTION_SHIFT_ID IN  STUDENT_ENROLLMENTS.SECTION_SHIFT_ID%TYPE,
        P_STATUS           IN  STUDENT_ENROLLMENTS.STATUS%TYPE,
        P_RESULT           OUT SYS_REFCURSOR
    );

    PROCEDURE DELETE_ENROLLMENT(
        P_ENROLLMENT_ID IN STUDENT_ENROLLMENTS.ENROLLMENT_ID%TYPE
    );

END STUDENT_ENROLLMENT_PKG;
/


CREATE OR REPLACE PACKAGE BODY STUDENT_ENROLLMENT_PKG AS

    PROCEDURE CREATE_ENROLLMENT(
        P_STUDENT_ID              IN  STUDENT_ENROLLMENTS.STUDENT_ID%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID  IN  STUDENT_ENROLLMENTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SECTION_SHIFT_ID        IN  STUDENT_ENROLLMENTS.SECTION_SHIFT_ID%TYPE,
        P_ROLL_NUMBER             IN  STUDENT_ENROLLMENTS.ROLL_NUMBER%TYPE,
        P_ENROLLMENT_DATE         IN  STUDENT_ENROLLMENTS.ENROLLMENT_DATE%TYPE,
        P_STATUS                  IN  STUDENT_ENROLLMENTS.STATUS%TYPE,
        P_REMARKS                 IN  STUDENT_ENROLLMENTS.REMARKS%TYPE,
        P_ENROLLMENT_ID           OUT STUDENT_ENROLLMENTS.ENROLLMENT_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO STUDENT_ENROLLMENTS (
            STUDENT_ID,
            ACADEMIC_YEAR_CLASS_ID,
            SECTION_SHIFT_ID,
            ROLL_NUMBER,
            ENROLLMENT_DATE,
            STATUS,
            REMARKS
        )
        VALUES (
                   P_STUDENT_ID,
                   P_ACADEMIC_YEAR_CLASS_ID,
                   P_SECTION_SHIFT_ID,
                   NULLIF(TRIM(P_ROLL_NUMBER), ''),
                   NVL(P_ENROLLMENT_DATE, SYSDATE),
                   UPPER(TRIM(NVL(P_STATUS, 'ENROLLED'))),
                   P_REMARKS
               )
        RETURNING ENROLLMENT_ID
        INTO P_ENROLLMENT_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                    -20401,
                    'STUDENT ENROLLMENT OR SECTION ROLL NUMBER ALREADY EXISTS'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20831,
                    'ERROR CREATING STUDENT ENROLLMENT: ' || SQLERRM
            );
    END CREATE_ENROLLMENT;


    PROCEDURE UPDATE_ENROLLMENT(
        P_ENROLLMENT_ID           IN STUDENT_ENROLLMENTS.ENROLLMENT_ID%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID  IN STUDENT_ENROLLMENTS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SECTION_SHIFT_ID        IN STUDENT_ENROLLMENTS.SECTION_SHIFT_ID%TYPE,
        P_ROLL_NUMBER             IN STUDENT_ENROLLMENTS.ROLL_NUMBER%TYPE,
        P_ENROLLMENT_DATE         IN STUDENT_ENROLLMENTS.ENROLLMENT_DATE%TYPE,
        P_STATUS                  IN STUDENT_ENROLLMENTS.STATUS%TYPE,
        P_REMARKS                 IN STUDENT_ENROLLMENTS.REMARKS%TYPE
    ) AS
    BEGIN
        UPDATE STUDENT_ENROLLMENTS
        SET ACADEMIC_YEAR_CLASS_ID = P_ACADEMIC_YEAR_CLASS_ID,
            SECTION_SHIFT_ID       = P_SECTION_SHIFT_ID,
            ROLL_NUMBER            = NULLIF(TRIM(P_ROLL_NUMBER), ''),
            ENROLLMENT_DATE        = P_ENROLLMENT_DATE,
            STATUS                 = UPPER(TRIM(P_STATUS)),
            REMARKS                = P_REMARKS,
            UPDATED_AT             = SYSTIMESTAMP
        WHERE ENROLLMENT_ID = P_ENROLLMENT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20402,
                    'STUDENT ENROLLMENT NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                    -20401,
                    'STUDENT ENROLLMENT OR SECTION ROLL NUMBER ALREADY EXISTS'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20832,
                    'ERROR UPDATING STUDENT ENROLLMENT: ' || SQLERRM
            );
    END UPDATE_ENROLLMENT;


    PROCEDURE GET_ENROLLMENT_BY_ID(
        P_ENROLLMENT_ID IN  STUDENT_ENROLLMENTS.ENROLLMENT_ID%TYPE,
        P_RESULT        OUT SYS_REFCURSOR
    ) AS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM STUDENT_ENROLLMENTS
        WHERE ENROLLMENT_ID = P_ENROLLMENT_ID;

        IF V_COUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20402,
                    'STUDENT ENROLLMENT NOT FOUND'
            );
        END IF;

        OPEN P_RESULT FOR
            SELECT
                SE.ENROLLMENT_ID,
                SE.STUDENT_ID,
                SE.ACADEMIC_YEAR_CLASS_ID,
                SE.SECTION_SHIFT_ID,
                SE.ROLL_NUMBER,
                SE.ENROLLMENT_DATE,
                SE.STATUS,
                SE.REMARKS,
                SE.CREATED_AT,
                SE.UPDATED_AT
            FROM STUDENT_ENROLLMENTS SE
            WHERE SE.ENROLLMENT_ID = P_ENROLLMENT_ID;
    END GET_ENROLLMENT_BY_ID;


    PROCEDURE GET_ALL_ENROLLMENTS(
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SE.ENROLLMENT_ID,
                SE.STUDENT_ID,
                SE.ACADEMIC_YEAR_CLASS_ID,
                SE.SECTION_SHIFT_ID,
                SE.ROLL_NUMBER,
                SE.ENROLLMENT_DATE,
                SE.STATUS,
                SE.REMARKS,
                SE.CREATED_AT,
                SE.UPDATED_AT
            FROM STUDENT_ENROLLMENTS SE
            ORDER BY
                SE.ACADEMIC_YEAR_CLASS_ID,
                SE.SECTION_SHIFT_ID,
                SE.ROLL_NUMBER;
    END GET_ALL_ENROLLMENTS;


    PROCEDURE GET_ENROLLMENTS_BY_STUDENT(
        P_STUDENT_ID IN  STUDENT_ENROLLMENTS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SE.ENROLLMENT_ID,
                SE.STUDENT_ID,
                SE.ACADEMIC_YEAR_CLASS_ID,
                SE.SECTION_SHIFT_ID,
                SE.ROLL_NUMBER,
                SE.ENROLLMENT_DATE,
                SE.STATUS,
                SE.REMARKS,
                SE.CREATED_AT,
                SE.UPDATED_AT
            FROM STUDENT_ENROLLMENTS SE
            WHERE SE.STUDENT_ID = P_STUDENT_ID
            ORDER BY SE.ENROLLMENT_DATE DESC;
    END GET_ENROLLMENTS_BY_STUDENT;


    PROCEDURE GET_ENROLLMENTS_BY_SECTION_SHIFT(
        P_SECTION_SHIFT_ID IN  STUDENT_ENROLLMENTS.SECTION_SHIFT_ID%TYPE,
        P_STATUS           IN  STUDENT_ENROLLMENTS.STATUS%TYPE,
        P_RESULT           OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SE.ENROLLMENT_ID,
                SE.STUDENT_ID,
                SE.ACADEMIC_YEAR_CLASS_ID,
                SE.SECTION_SHIFT_ID,
                SE.ROLL_NUMBER,
                SE.ENROLLMENT_DATE,
                SE.STATUS,
                SE.REMARKS,
                SE.CREATED_AT,
                SE.UPDATED_AT
            FROM STUDENT_ENROLLMENTS SE
            WHERE SE.SECTION_SHIFT_ID = P_SECTION_SHIFT_ID
              AND (
                P_STATUS IS NULL
                    OR SE.STATUS = UPPER(TRIM(P_STATUS))
                )
            ORDER BY SE.ROLL_NUMBER;
    END GET_ENROLLMENTS_BY_SECTION_SHIFT;


    PROCEDURE DELETE_ENROLLMENT(
        P_ENROLLMENT_ID IN STUDENT_ENROLLMENTS.ENROLLMENT_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM STUDENT_ENROLLMENTS
        WHERE ENROLLMENT_ID = P_ENROLLMENT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20402,
                    'STUDENT ENROLLMENT NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20833,
                    'ERROR DELETING STUDENT ENROLLMENT: ' || SQLERRM
            );
    END DELETE_ENROLLMENT;

END STUDENT_ENROLLMENT_PKG;
/


-- ============================================================
-- 2. ATTENDANCE_SESSION_PKG
-- ============================================================

CREATE OR REPLACE PACKAGE ATTENDANCE_SESSION_PKG AS

    PROCEDURE CREATE_SESSION(
        P_SECTION_SHIFT_ID       IN  ATTENDANCE_SESSIONS.SECTION_SHIFT_ID%TYPE,
        P_CLASS_SUBJECT_ID       IN  ATTENDANCE_SESSIONS.CLASS_SUBJECT_ID%TYPE,
        P_ATTENDANCE_DATE        IN  ATTENDANCE_SESSIONS.ATTENDANCE_DATE%TYPE,
        P_ATTENDANCE_TYPE        IN  ATTENDANCE_SESSIONS.ATTENDANCE_TYPE%TYPE,
        P_PERIOD_NUMBER          IN  ATTENDANCE_SESSIONS.PERIOD_NUMBER%TYPE,
        P_MARKED_BY_TEACHER_ID   IN  ATTENDANCE_SESSIONS.MARKED_BY_TEACHER_ID%TYPE,
        P_STATUS                 IN  ATTENDANCE_SESSIONS.STATUS%TYPE,
        P_REMARKS                IN  ATTENDANCE_SESSIONS.REMARKS%TYPE,
        P_ATTENDANCE_SESSION_ID  OUT ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE
    );

    PROCEDURE UPDATE_SESSION(
        P_ATTENDANCE_SESSION_ID IN ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE,
        P_SECTION_SHIFT_ID      IN ATTENDANCE_SESSIONS.SECTION_SHIFT_ID%TYPE,
        P_CLASS_SUBJECT_ID      IN ATTENDANCE_SESSIONS.CLASS_SUBJECT_ID%TYPE,
        P_ATTENDANCE_DATE       IN ATTENDANCE_SESSIONS.ATTENDANCE_DATE%TYPE,
        P_ATTENDANCE_TYPE       IN ATTENDANCE_SESSIONS.ATTENDANCE_TYPE%TYPE,
        P_PERIOD_NUMBER         IN ATTENDANCE_SESSIONS.PERIOD_NUMBER%TYPE,
        P_MARKED_BY_TEACHER_ID  IN ATTENDANCE_SESSIONS.MARKED_BY_TEACHER_ID%TYPE,
        P_STATUS                IN ATTENDANCE_SESSIONS.STATUS%TYPE,
        P_REMARKS               IN ATTENDANCE_SESSIONS.REMARKS%TYPE
    );

    PROCEDURE GET_SESSION_BY_ID(
        P_ATTENDANCE_SESSION_ID IN  ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE,
        P_RESULT                OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_SESSIONS(
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_SESSIONS_BY_SECTION_DATE(
        P_SECTION_SHIFT_ID IN  ATTENDANCE_SESSIONS.SECTION_SHIFT_ID%TYPE,
        P_ATTENDANCE_DATE  IN  ATTENDANCE_SESSIONS.ATTENDANCE_DATE%TYPE,
        P_RESULT           OUT SYS_REFCURSOR
    );

    PROCEDURE CHANGE_SESSION_STATUS(
        P_ATTENDANCE_SESSION_ID IN ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE,
        P_STATUS                IN ATTENDANCE_SESSIONS.STATUS%TYPE
    );

    PROCEDURE DELETE_SESSION(
        P_ATTENDANCE_SESSION_ID IN ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE
    );

END ATTENDANCE_SESSION_PKG;
/


CREATE OR REPLACE PACKAGE BODY ATTENDANCE_SESSION_PKG AS

    PROCEDURE CREATE_SESSION(
        P_SECTION_SHIFT_ID       IN  ATTENDANCE_SESSIONS.SECTION_SHIFT_ID%TYPE,
        P_CLASS_SUBJECT_ID       IN  ATTENDANCE_SESSIONS.CLASS_SUBJECT_ID%TYPE,
        P_ATTENDANCE_DATE        IN  ATTENDANCE_SESSIONS.ATTENDANCE_DATE%TYPE,
        P_ATTENDANCE_TYPE        IN  ATTENDANCE_SESSIONS.ATTENDANCE_TYPE%TYPE,
        P_PERIOD_NUMBER          IN  ATTENDANCE_SESSIONS.PERIOD_NUMBER%TYPE,
        P_MARKED_BY_TEACHER_ID   IN  ATTENDANCE_SESSIONS.MARKED_BY_TEACHER_ID%TYPE,
        P_STATUS                 IN  ATTENDANCE_SESSIONS.STATUS%TYPE,
        P_REMARKS                IN  ATTENDANCE_SESSIONS.REMARKS%TYPE,
        P_ATTENDANCE_SESSION_ID  OUT ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO ATTENDANCE_SESSIONS (
            SECTION_SHIFT_ID,
            CLASS_SUBJECT_ID,
            ATTENDANCE_DATE,
            ATTENDANCE_TYPE,
            PERIOD_NUMBER,
            MARKED_BY_TEACHER_ID,
            STATUS,
            REMARKS
        )
        VALUES (
                   P_SECTION_SHIFT_ID,
                   P_CLASS_SUBJECT_ID,
                   TRUNC(P_ATTENDANCE_DATE),
                   UPPER(TRIM(NVL(P_ATTENDANCE_TYPE, 'DAILY'))),
                   P_PERIOD_NUMBER,
                   P_MARKED_BY_TEACHER_ID,
                   UPPER(TRIM(NVL(P_STATUS, 'OPEN'))),
                   P_REMARKS
               )
        RETURNING ATTENDANCE_SESSION_ID
        INTO P_ATTENDANCE_SESSION_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                    -20501,
                    'ATTENDANCE SESSION ALREADY EXISTS'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20841,
                    'ERROR CREATING ATTENDANCE SESSION: ' || SQLERRM
            );
    END CREATE_SESSION;


    PROCEDURE UPDATE_SESSION(
        P_ATTENDANCE_SESSION_ID IN ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE,
        P_SECTION_SHIFT_ID      IN ATTENDANCE_SESSIONS.SECTION_SHIFT_ID%TYPE,
        P_CLASS_SUBJECT_ID      IN ATTENDANCE_SESSIONS.CLASS_SUBJECT_ID%TYPE,
        P_ATTENDANCE_DATE       IN ATTENDANCE_SESSIONS.ATTENDANCE_DATE%TYPE,
        P_ATTENDANCE_TYPE       IN ATTENDANCE_SESSIONS.ATTENDANCE_TYPE%TYPE,
        P_PERIOD_NUMBER         IN ATTENDANCE_SESSIONS.PERIOD_NUMBER%TYPE,
        P_MARKED_BY_TEACHER_ID  IN ATTENDANCE_SESSIONS.MARKED_BY_TEACHER_ID%TYPE,
        P_STATUS                IN ATTENDANCE_SESSIONS.STATUS%TYPE,
        P_REMARKS               IN ATTENDANCE_SESSIONS.REMARKS%TYPE
    ) AS
    BEGIN
        UPDATE ATTENDANCE_SESSIONS
        SET SECTION_SHIFT_ID      = P_SECTION_SHIFT_ID,
            CLASS_SUBJECT_ID      = P_CLASS_SUBJECT_ID,
            ATTENDANCE_DATE       = TRUNC(P_ATTENDANCE_DATE),
            ATTENDANCE_TYPE       = UPPER(TRIM(P_ATTENDANCE_TYPE)),
            PERIOD_NUMBER         = P_PERIOD_NUMBER,
            MARKED_BY_TEACHER_ID  = P_MARKED_BY_TEACHER_ID,
            STATUS                = UPPER(TRIM(P_STATUS)),
            REMARKS               = P_REMARKS,
            UPDATED_AT            = SYSTIMESTAMP
        WHERE ATTENDANCE_SESSION_ID = P_ATTENDANCE_SESSION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20502,
                    'ATTENDANCE SESSION NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                    -20501,
                    'ATTENDANCE SESSION ALREADY EXISTS'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20842,
                    'ERROR UPDATING ATTENDANCE SESSION: ' || SQLERRM
            );
    END UPDATE_SESSION;


    PROCEDURE GET_SESSION_BY_ID(
        P_ATTENDANCE_SESSION_ID IN  ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE,
        P_RESULT                OUT SYS_REFCURSOR
    ) AS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM ATTENDANCE_SESSIONS
        WHERE ATTENDANCE_SESSION_ID = P_ATTENDANCE_SESSION_ID;

        IF V_COUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20502,
                    'ATTENDANCE SESSION NOT FOUND'
            );
        END IF;

        OPEN P_RESULT FOR
            SELECT
                ATTENDANCE_SESSION_ID,
                SECTION_SHIFT_ID,
                CLASS_SUBJECT_ID,
                ATTENDANCE_DATE,
                ATTENDANCE_TYPE,
                PERIOD_NUMBER,
                MARKED_BY_TEACHER_ID,
                STATUS,
                REMARKS,
                CREATED_AT,
                UPDATED_AT
            FROM ATTENDANCE_SESSIONS
            WHERE ATTENDANCE_SESSION_ID = P_ATTENDANCE_SESSION_ID;
    END GET_SESSION_BY_ID;


    PROCEDURE GET_ALL_SESSIONS(
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                ATTENDANCE_SESSION_ID,
                SECTION_SHIFT_ID,
                CLASS_SUBJECT_ID,
                ATTENDANCE_DATE,
                ATTENDANCE_TYPE,
                PERIOD_NUMBER,
                MARKED_BY_TEACHER_ID,
                STATUS,
                REMARKS,
                CREATED_AT,
                UPDATED_AT
            FROM ATTENDANCE_SESSIONS
            ORDER BY ATTENDANCE_DATE DESC,
                     SECTION_SHIFT_ID,
                     PERIOD_NUMBER;
    END GET_ALL_SESSIONS;


    PROCEDURE GET_SESSIONS_BY_SECTION_DATE(
        P_SECTION_SHIFT_ID IN  ATTENDANCE_SESSIONS.SECTION_SHIFT_ID%TYPE,
        P_ATTENDANCE_DATE  IN  ATTENDANCE_SESSIONS.ATTENDANCE_DATE%TYPE,
        P_RESULT           OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                ATTENDANCE_SESSION_ID,
                SECTION_SHIFT_ID,
                CLASS_SUBJECT_ID,
                ATTENDANCE_DATE,
                ATTENDANCE_TYPE,
                PERIOD_NUMBER,
                MARKED_BY_TEACHER_ID,
                STATUS,
                REMARKS,
                CREATED_AT,
                UPDATED_AT
            FROM ATTENDANCE_SESSIONS
            WHERE SECTION_SHIFT_ID = P_SECTION_SHIFT_ID
              AND TRUNC(ATTENDANCE_DATE) = TRUNC(P_ATTENDANCE_DATE)
            ORDER BY PERIOD_NUMBER;
    END GET_SESSIONS_BY_SECTION_DATE;


    PROCEDURE CHANGE_SESSION_STATUS(
        P_ATTENDANCE_SESSION_ID IN ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE,
        P_STATUS                IN ATTENDANCE_SESSIONS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE ATTENDANCE_SESSIONS
        SET STATUS     = UPPER(TRIM(P_STATUS)),
            UPDATED_AT = SYSTIMESTAMP
        WHERE ATTENDANCE_SESSION_ID = P_ATTENDANCE_SESSION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20502,
                    'ATTENDANCE SESSION NOT FOUND'
            );
        END IF;
    END CHANGE_SESSION_STATUS;


    PROCEDURE DELETE_SESSION(
        P_ATTENDANCE_SESSION_ID IN ATTENDANCE_SESSIONS.ATTENDANCE_SESSION_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM ATTENDANCE_SESSIONS
        WHERE ATTENDANCE_SESSION_ID = P_ATTENDANCE_SESSION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20502,
                    'ATTENDANCE SESSION NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20843,
                    'ERROR DELETING ATTENDANCE SESSION: ' || SQLERRM
            );
    END DELETE_SESSION;

END ATTENDANCE_SESSION_PKG;
/


-- ============================================================
-- 3. ATTENDANCE_RECORD_PKG
-- ============================================================

CREATE OR REPLACE PACKAGE ATTENDANCE_RECORD_PKG AS

    PROCEDURE CREATE_RECORD(
        P_ATTENDANCE_SESSION_ID IN  ATTENDANCE_RECORDS.ATTENDANCE_SESSION_ID%TYPE,
        P_ENROLLMENT_ID         IN  ATTENDANCE_RECORDS.ENROLLMENT_ID%TYPE,
        P_ATTENDANCE_STATUS     IN  ATTENDANCE_RECORDS.ATTENDANCE_STATUS%TYPE,
        P_CHECK_IN_TIME         IN  ATTENDANCE_RECORDS.CHECK_IN_TIME%TYPE,
        P_REMARKS               IN  ATTENDANCE_RECORDS.REMARKS%TYPE,
        P_ATTENDANCE_RECORD_ID  OUT ATTENDANCE_RECORDS.ATTENDANCE_RECORD_ID%TYPE
    );

    PROCEDURE UPDATE_RECORD(
        P_ATTENDANCE_RECORD_ID IN ATTENDANCE_RECORDS.ATTENDANCE_RECORD_ID%TYPE,
        P_ATTENDANCE_STATUS    IN ATTENDANCE_RECORDS.ATTENDANCE_STATUS%TYPE,
        P_CHECK_IN_TIME        IN ATTENDANCE_RECORDS.CHECK_IN_TIME%TYPE,
        P_REMARKS              IN ATTENDANCE_RECORDS.REMARKS%TYPE
    );

    PROCEDURE GET_RECORD_BY_ID(
        P_ATTENDANCE_RECORD_ID IN  ATTENDANCE_RECORDS.ATTENDANCE_RECORD_ID%TYPE,
        P_RESULT               OUT SYS_REFCURSOR
    );

    PROCEDURE GET_RECORDS_BY_SESSION(
        P_ATTENDANCE_SESSION_ID IN  ATTENDANCE_RECORDS.ATTENDANCE_SESSION_ID%TYPE,
        P_RESULT                OUT SYS_REFCURSOR
    );

    PROCEDURE GET_RECORDS_BY_ENROLLMENT(
        P_ENROLLMENT_ID IN  ATTENDANCE_RECORDS.ENROLLMENT_ID%TYPE,
        P_RESULT        OUT SYS_REFCURSOR
    );

    PROCEDURE DELETE_RECORD(
        P_ATTENDANCE_RECORD_ID IN ATTENDANCE_RECORDS.ATTENDANCE_RECORD_ID%TYPE
    );

END ATTENDANCE_RECORD_PKG;
/


CREATE OR REPLACE PACKAGE BODY ATTENDANCE_RECORD_PKG AS

    PROCEDURE CREATE_RECORD(
        P_ATTENDANCE_SESSION_ID IN  ATTENDANCE_RECORDS.ATTENDANCE_SESSION_ID%TYPE,
        P_ENROLLMENT_ID         IN  ATTENDANCE_RECORDS.ENROLLMENT_ID%TYPE,
        P_ATTENDANCE_STATUS     IN  ATTENDANCE_RECORDS.ATTENDANCE_STATUS%TYPE,
        P_CHECK_IN_TIME         IN  ATTENDANCE_RECORDS.CHECK_IN_TIME%TYPE,
        P_REMARKS               IN  ATTENDANCE_RECORDS.REMARKS%TYPE,
        P_ATTENDANCE_RECORD_ID  OUT ATTENDANCE_RECORDS.ATTENDANCE_RECORD_ID%TYPE
    ) AS
        V_SESSION_SECTION_SHIFT_ID
            ATTENDANCE_SESSIONS.SECTION_SHIFT_ID%TYPE;

        V_ENROLL_SECTION_SHIFT_ID
            STUDENT_ENROLLMENTS.SECTION_SHIFT_ID%TYPE;

        V_SESSION_STATUS
            ATTENDANCE_SESSIONS.STATUS%TYPE;
    BEGIN
        SELECT SECTION_SHIFT_ID, STATUS
        INTO V_SESSION_SECTION_SHIFT_ID, V_SESSION_STATUS
        FROM ATTENDANCE_SESSIONS
        WHERE ATTENDANCE_SESSION_ID = P_ATTENDANCE_SESSION_ID;

        IF V_SESSION_STATUS IN ('LOCKED', 'CANCELLED') THEN
            RAISE_APPLICATION_ERROR(
                    -20603,
                    'ATTENDANCE RECORD CANNOT BE ADDED TO A LOCKED OR CANCELLED SESSION'
            );
        END IF;

        SELECT SECTION_SHIFT_ID
        INTO V_ENROLL_SECTION_SHIFT_ID
        FROM STUDENT_ENROLLMENTS
        WHERE ENROLLMENT_ID = P_ENROLLMENT_ID;

        IF V_SESSION_SECTION_SHIFT_ID <> V_ENROLL_SECTION_SHIFT_ID THEN
            RAISE_APPLICATION_ERROR(
                    -20604,
                    'STUDENT ENROLLMENT DOES NOT BELONG TO THE ATTENDANCE SESSION SECTION SHIFT'
            );
        END IF;

        INSERT INTO ATTENDANCE_RECORDS (
            ATTENDANCE_SESSION_ID,
            ENROLLMENT_ID,
            ATTENDANCE_STATUS,
            CHECK_IN_TIME,
            REMARKS
        )
        VALUES (
                   P_ATTENDANCE_SESSION_ID,
                   P_ENROLLMENT_ID,
                   UPPER(TRIM(NVL(P_ATTENDANCE_STATUS, 'PRESENT'))),
                   P_CHECK_IN_TIME,
                   P_REMARKS
               )
        RETURNING ATTENDANCE_RECORD_ID
        INTO P_ATTENDANCE_RECORD_ID;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(
                    -20605,
                    'ATTENDANCE SESSION OR STUDENT ENROLLMENT NOT FOUND'
            );

        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                    -20601,
                    'ATTENDANCE RECORD ALREADY EXISTS FOR THIS STUDENT AND SESSION'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20851,
                    'ERROR CREATING ATTENDANCE RECORD: ' || SQLERRM
            );
    END CREATE_RECORD;


    PROCEDURE UPDATE_RECORD(
        P_ATTENDANCE_RECORD_ID IN ATTENDANCE_RECORDS.ATTENDANCE_RECORD_ID%TYPE,
        P_ATTENDANCE_STATUS    IN ATTENDANCE_RECORDS.ATTENDANCE_STATUS%TYPE,
        P_CHECK_IN_TIME        IN ATTENDANCE_RECORDS.CHECK_IN_TIME%TYPE,
        P_REMARKS              IN ATTENDANCE_RECORDS.REMARKS%TYPE
    ) AS
        V_SESSION_STATUS ATTENDANCE_SESSIONS.STATUS%TYPE;
    BEGIN
        SELECT ATS.STATUS
        INTO V_SESSION_STATUS
        FROM ATTENDANCE_RECORDS AR
                 JOIN ATTENDANCE_SESSIONS ATS
                      ON ATS.ATTENDANCE_SESSION_ID = AR.ATTENDANCE_SESSION_ID
        WHERE AR.ATTENDANCE_RECORD_ID = P_ATTENDANCE_RECORD_ID;

        IF V_SESSION_STATUS IN ('LOCKED', 'CANCELLED') THEN
            RAISE_APPLICATION_ERROR(
                    -20603,
                    'ATTENDANCE RECORD CANNOT BE UPDATED IN A LOCKED OR CANCELLED SESSION'
            );
        END IF;

        UPDATE ATTENDANCE_RECORDS
        SET ATTENDANCE_STATUS = UPPER(TRIM(P_ATTENDANCE_STATUS)),
            CHECK_IN_TIME     = P_CHECK_IN_TIME,
            REMARKS           = P_REMARKS,
            UPDATED_AT        = SYSTIMESTAMP
        WHERE ATTENDANCE_RECORD_ID = P_ATTENDANCE_RECORD_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20602,
                    'ATTENDANCE RECORD NOT FOUND'
            );
        END IF;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(
                    -20602,
                    'ATTENDANCE RECORD NOT FOUND'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20852,
                    'ERROR UPDATING ATTENDANCE RECORD: ' || SQLERRM
            );
    END UPDATE_RECORD;


    PROCEDURE GET_RECORD_BY_ID(
        P_ATTENDANCE_RECORD_ID IN  ATTENDANCE_RECORDS.ATTENDANCE_RECORD_ID%TYPE,
        P_RESULT               OUT SYS_REFCURSOR
    ) AS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM ATTENDANCE_RECORDS
        WHERE ATTENDANCE_RECORD_ID = P_ATTENDANCE_RECORD_ID;

        IF V_COUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                    -20602,
                    'ATTENDANCE RECORD NOT FOUND'
            );
        END IF;

        OPEN P_RESULT FOR
            SELECT
                ATTENDANCE_RECORD_ID,
                ATTENDANCE_SESSION_ID,
                ENROLLMENT_ID,
                ATTENDANCE_STATUS,
                CHECK_IN_TIME,
                REMARKS,
                MARKED_AT,
                UPDATED_AT
            FROM ATTENDANCE_RECORDS
            WHERE ATTENDANCE_RECORD_ID = P_ATTENDANCE_RECORD_ID;
    END GET_RECORD_BY_ID;


    PROCEDURE GET_RECORDS_BY_SESSION(
        P_ATTENDANCE_SESSION_ID IN  ATTENDANCE_RECORDS.ATTENDANCE_SESSION_ID%TYPE,
        P_RESULT                OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                AR.ATTENDANCE_RECORD_ID,
                AR.ATTENDANCE_SESSION_ID,
                AR.ENROLLMENT_ID,
                SE.STUDENT_ID,
                SE.ROLL_NUMBER,
                AR.ATTENDANCE_STATUS,
                AR.CHECK_IN_TIME,
                AR.REMARKS,
                AR.MARKED_AT,
                AR.UPDATED_AT
            FROM ATTENDANCE_RECORDS AR
                     JOIN STUDENT_ENROLLMENTS SE
                          ON SE.ENROLLMENT_ID = AR.ENROLLMENT_ID
            WHERE AR.ATTENDANCE_SESSION_ID =
                  P_ATTENDANCE_SESSION_ID
            ORDER BY SE.ROLL_NUMBER;
    END GET_RECORDS_BY_SESSION;


    PROCEDURE GET_RECORDS_BY_ENROLLMENT(
        P_ENROLLMENT_ID IN  ATTENDANCE_RECORDS.ENROLLMENT_ID%TYPE,
        P_RESULT        OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                AR.ATTENDANCE_RECORD_ID,
                AR.ATTENDANCE_SESSION_ID,
                AR.ENROLLMENT_ID,
                AR.ATTENDANCE_STATUS,
                AR.CHECK_IN_TIME,
                AR.REMARKS,
                AR.MARKED_AT,
                AR.UPDATED_AT
            FROM ATTENDANCE_RECORDS AR
            WHERE AR.ENROLLMENT_ID = P_ENROLLMENT_ID
            ORDER BY AR.MARKED_AT DESC;
    END GET_RECORDS_BY_ENROLLMENT;


    PROCEDURE DELETE_RECORD(
        P_ATTENDANCE_RECORD_ID IN ATTENDANCE_RECORDS.ATTENDANCE_RECORD_ID%TYPE
    ) AS
        V_SESSION_STATUS ATTENDANCE_SESSIONS.STATUS%TYPE;
    BEGIN
        SELECT ATS.STATUS
        INTO V_SESSION_STATUS
        FROM ATTENDANCE_RECORDS AR
                 JOIN ATTENDANCE_SESSIONS ATS
                      ON ATS.ATTENDANCE_SESSION_ID = AR.ATTENDANCE_SESSION_ID
        WHERE AR.ATTENDANCE_RECORD_ID = P_ATTENDANCE_RECORD_ID;

        IF V_SESSION_STATUS = 'LOCKED' THEN
            RAISE_APPLICATION_ERROR(
                    -20603,
                    'ATTENDANCE RECORD CANNOT BE DELETED FROM A LOCKED SESSION'
            );
        END IF;

        DELETE FROM ATTENDANCE_RECORDS
        WHERE ATTENDANCE_RECORD_ID = P_ATTENDANCE_RECORD_ID;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(
                    -20602,
                    'ATTENDANCE RECORD NOT FOUND'
            );

        WHEN OTHERS THEN
            IF SQLCODE BETWEEN -20999 AND -20000 THEN
                RAISE;
            END IF;

            RAISE_APPLICATION_ERROR(
                    -20853,
                    'ERROR DELETING ATTENDANCE RECORD: ' || SQLERRM
            );
    END DELETE_RECORD;

END ATTENDANCE_RECORD_PKG;
/