----------------------------------------------------------------------
-- V13: EXAMINATION MANAGEMENT TABLES
----------------------------------------------------------------------

----------------------------------------------------------------------
-- 1. EXAM
----------------------------------------------------------------------

CREATE TABLE EXAM (
                      EXAM_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY,
                      ACADEMIC_YEAR_ID    NUMBER NOT NULL,
                      EXAM_NAME           VARCHAR2(100) NOT NULL,
                      EXAM_CODE           VARCHAR2(30) NOT NULL,
                      EXAM_TYPE           VARCHAR2(30) NOT NULL,
                      START_DATE          DATE NOT NULL,
                      END_DATE            DATE NOT NULL,
                      DESCRIPTION         VARCHAR2(500),
                      STATUS              VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
                      CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                      UPDATED_AT          TIMESTAMP,
                      CREATED_BY          NUMBER,
                      UPDATED_BY          NUMBER,

                      CONSTRAINT PK_EXAM
                          PRIMARY KEY (EXAM_ID),

                      CONSTRAINT UK_EXAM_YEAR_CODE
                          UNIQUE (ACADEMIC_YEAR_ID, EXAM_CODE),

                      CONSTRAINT FK_EXAM_ACADEMIC_YEAR
                          FOREIGN KEY (ACADEMIC_YEAR_ID)
                              REFERENCES ACADEMIC_YEARS (ACADEMIC_YEAR_ID),

                      CONSTRAINT CK_EXAM_TYPE
                          CHECK (
                              EXAM_TYPE IN (
                                            'CLASS_TEST',
                                            'QUIZ',
                                            'MIDTERM',
                                            'FINAL',
                                            'PRACTICAL',
                                            'ASSIGNMENT',
                                            'OTHER'
                                  )
                              ),

                      CONSTRAINT CK_EXAM_STATUS
                          CHECK (
                              STATUS IN (
                                         'DRAFT',
                                         'SCHEDULED',
                                         'ONGOING',
                                         'COMPLETED',
                                         'CANCELLED'
                                  )
                              ),

                      CONSTRAINT CK_EXAM_DATE_RANGE
                          CHECK (END_DATE >= START_DATE)
);

----------------------------------------------------------------------
-- 2. EXAM SUBJECT
----------------------------------------------------------------------

CREATE TABLE EXAM_SUBJECT (
                              EXAM_SUBJECT_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
                              EXAM_ID                  NUMBER NOT NULL,
                              ACADEMIC_YEAR_CLASS_ID   NUMBER NOT NULL,
                              SECTION_ID               NUMBER,
                              SUBJECT_ID               NUMBER NOT NULL,
                              EXAM_DATE                DATE NOT NULL,
                              START_TIME               VARCHAR2(10),
                              END_TIME                 VARCHAR2(10),
                              DURATION_MINUTES         NUMBER(5),
                              FULL_MARKS               NUMBER(7,2) NOT NULL,
                              PASS_MARKS               NUMBER(7,2) NOT NULL,
                              ROOM_NUMBER              VARCHAR2(30),
                              INSTRUCTIONS             VARCHAR2(1000),
                              STATUS                   VARCHAR2(20) DEFAULT 'SCHEDULED' NOT NULL,
                              CREATED_AT               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                              UPDATED_AT               TIMESTAMP,
                              CREATED_BY               NUMBER,
                              UPDATED_BY               NUMBER,

                              CONSTRAINT PK_EXAM_SUBJECT
                                  PRIMARY KEY (EXAM_SUBJECT_ID),

                              CONSTRAINT UK_EXAM_SUBJECT
                                  UNIQUE (
                                          EXAM_ID,
                                          ACADEMIC_YEAR_CLASS_ID,
                                          SECTION_ID,
                                          SUBJECT_ID
                                      ),

                              CONSTRAINT FK_EXAM_SUBJECT_EXAM
                                  FOREIGN KEY (EXAM_ID)
                                      REFERENCES EXAM (EXAM_ID),

                              CONSTRAINT FK_EXAM_SUBJECT_CLASS
                                  FOREIGN KEY (ACADEMIC_YEAR_CLASS_ID)
                                      REFERENCES ACADEMIC_YEAR_CLASSES (ACADEMIC_YEAR_CLASS_ID),

                              CONSTRAINT FK_EXAM_SUBJECT_SECTION
                                  FOREIGN KEY (SECTION_ID)
                                      REFERENCES SECTIONS (SECTION_ID),

                              CONSTRAINT FK_EXAM_SUBJECT_SUBJECT
                                  FOREIGN KEY (SUBJECT_ID)
                                      REFERENCES SUBJECTS (SUBJECT_ID),

                              CONSTRAINT CK_EXAM_SUBJECT_STATUS
                                  CHECK (
                                      STATUS IN (
                                                 'SCHEDULED',
                                                 'ONGOING',
                                                 'COMPLETED',
                                                 'POSTPONED',
                                                 'CANCELLED'
                                          )
                                      ),

                              CONSTRAINT CK_EXAM_FULL_MARKS
                                  CHECK (FULL_MARKS > 0),

                              CONSTRAINT CK_EXAM_PASS_MARKS
                                  CHECK (
                                      PASS_MARKS >= 0
                                          AND PASS_MARKS <= FULL_MARKS
                                      ),

                              CONSTRAINT CK_EXAM_DURATION
                                  CHECK (
                                      DURATION_MINUTES IS NULL
                                          OR DURATION_MINUTES > 0
                                      )
);

----------------------------------------------------------------------
-- 3. GRADE SCALE
----------------------------------------------------------------------

CREATE TABLE GRADE_SCALE (
                             GRADE_SCALE_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             GRADE_NAME          VARCHAR2(20) NOT NULL,
                             LETTER_GRADE        VARCHAR2(5) NOT NULL,
                             MIN_PERCENTAGE      NUMBER(5,2) NOT NULL,
                             MAX_PERCENTAGE      NUMBER(5,2) NOT NULL,
                             GRADE_POINT         NUMBER(4,2) NOT NULL,
                             DESCRIPTION         VARCHAR2(250),
                             DISPLAY_ORDER       NUMBER(5) DEFAULT 1 NOT NULL,
                             STATUS              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
                             CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             UPDATED_AT          TIMESTAMP,
                             CREATED_BY          NUMBER,
                             UPDATED_BY          NUMBER,

                             CONSTRAINT PK_GRADE_SCALE
                                 PRIMARY KEY (GRADE_SCALE_ID),

                             CONSTRAINT UK_GRADE_SCALE_LETTER
                                 UNIQUE (LETTER_GRADE),

                             CONSTRAINT CK_GRADE_PERCENTAGES
                                 CHECK (
                                     MIN_PERCENTAGE >= 0
                                         AND MAX_PERCENTAGE <= 100
                                         AND MAX_PERCENTAGE >= MIN_PERCENTAGE
                                     ),

                             CONSTRAINT CK_GRADE_POINT
                                 CHECK (GRADE_POINT >= 0),

                             CONSTRAINT CK_GRADE_STATUS
                                 CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
);

----------------------------------------------------------------------
-- 4. STUDENT EXAM MARK
----------------------------------------------------------------------

CREATE TABLE STUDENT_EXAM_MARK (
                                   STUDENT_EXAM_MARK_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                   EXAM_SUBJECT_ID         NUMBER NOT NULL,
                                   STUDENT_ID              NUMBER NOT NULL,
                                   OBTAINED_MARKS          NUMBER(7,2),
                                   PERCENTAGE              NUMBER(5,2),
                                   LETTER_GRADE            VARCHAR2(5),
                                   GRADE_POINT             NUMBER(4,2),
                                   RESULT_STATUS           VARCHAR2(20),
                                   ATTENDANCE_STATUS       VARCHAR2(20) DEFAULT 'PRESENT' NOT NULL,
                                   REMARKS                 VARCHAR2(500),
                                   PUBLISHED_FLAG          CHAR(1) DEFAULT 'N' NOT NULL,
                                   MARKED_AT               TIMESTAMP,
                                   PUBLISHED_AT            TIMESTAMP,
                                   CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                   UPDATED_AT              TIMESTAMP,
                                   CREATED_BY              NUMBER,
                                   UPDATED_BY              NUMBER,

                                   CONSTRAINT PK_STUDENT_EXAM_MARK
                                       PRIMARY KEY (STUDENT_EXAM_MARK_ID),

                                   CONSTRAINT UK_STUDENT_EXAM_MARK
                                       UNIQUE (EXAM_SUBJECT_ID, STUDENT_ID),

                                   CONSTRAINT FK_STUDENT_MARK_EXAM_SUB
                                       FOREIGN KEY (EXAM_SUBJECT_ID)
                                           REFERENCES EXAM_SUBJECT (EXAM_SUBJECT_ID),

                                   CONSTRAINT FK_STUDENT_MARK_STUDENT
                                       FOREIGN KEY (STUDENT_ID)
                                           REFERENCES STUDENTS (STUDENT_ID),

                                   CONSTRAINT CK_OBTAINED_MARKS
                                       CHECK (
                                           OBTAINED_MARKS IS NULL
                                               OR OBTAINED_MARKS >= 0
                                           ),

                                   CONSTRAINT CK_MARK_PERCENTAGE
                                       CHECK (
                                           PERCENTAGE IS NULL
                                               OR PERCENTAGE BETWEEN 0 AND 100
                                           ),

                                   CONSTRAINT CK_MARK_GRADE_POINT
                                       CHECK (
                                           GRADE_POINT IS NULL
                                               OR GRADE_POINT >= 0
                                           ),

                                   CONSTRAINT CK_MARK_RESULT_STATUS
                                       CHECK (
                                           RESULT_STATUS IS NULL
                                               OR RESULT_STATUS IN ('PASS', 'FAIL', 'WITHHELD')
                                           ),

                                   CONSTRAINT CK_MARK_ATTENDANCE
                                       CHECK (
                                           ATTENDANCE_STATUS IN (
                                                                 'PRESENT',
                                                                 'ABSENT',
                                                                 'EXCUSED'
                                               )
                                           ),

                                   CONSTRAINT CK_MARK_PUBLISHED
                                       CHECK (PUBLISHED_FLAG IN ('Y', 'N'))
);

----------------------------------------------------------------------
-- INDEXES
----------------------------------------------------------------------

CREATE INDEX IDX_EXAM_ACADEMIC_YEAR
    ON EXAM (ACADEMIC_YEAR_ID);

CREATE INDEX IDX_EXAM_STATUS
    ON EXAM (STATUS);

CREATE INDEX IDX_EXAM_SUBJECT_EXAM
    ON EXAM_SUBJECT (EXAM_ID);

CREATE INDEX IDX_EXAM_SUBJECT_CLASS
    ON EXAM_SUBJECT (ACADEMIC_YEAR_CLASS_ID);

CREATE INDEX IDX_EXAM_SUBJECT_SECTION
    ON EXAM_SUBJECT (SECTION_ID);

CREATE INDEX IDX_EXAM_SUBJECT_SUBJECT
    ON EXAM_SUBJECT (SUBJECT_ID);

CREATE INDEX IDX_STUDENT_MARK_EXAM_SUB
    ON STUDENT_EXAM_MARK (EXAM_SUBJECT_ID);

CREATE INDEX IDX_STUDENT_MARK_STUDENT
    ON STUDENT_EXAM_MARK (STUDENT_ID);

CREATE INDEX IDX_STUDENT_MARK_RESULT
    ON STUDENT_EXAM_MARK (RESULT_STATUS);

CREATE INDEX IDX_GRADE_SCALE_RANGE
    ON GRADE_SCALE (MIN_PERCENTAGE, MAX_PERCENTAGE);

----------------------------------------------------------------------
-- DEFAULT GRADE SCALE
----------------------------------------------------------------------

INSERT INTO GRADE_SCALE (
    GRADE_NAME,
    LETTER_GRADE,
    MIN_PERCENTAGE,
    MAX_PERCENTAGE,
    GRADE_POINT,
    DISPLAY_ORDER,
    STATUS
) VALUES (
             'Outstanding',
             'A+',
             80,
             100,
             5.00,
             1,
             'ACTIVE'
         );

INSERT INTO GRADE_SCALE (
    GRADE_NAME,
    LETTER_GRADE,
    MIN_PERCENTAGE,
    MAX_PERCENTAGE,
    GRADE_POINT,
    DISPLAY_ORDER,
    STATUS
) VALUES (
             'Excellent',
             'A',
             70,
             79.99,
             4.00,
             2,
             'ACTIVE'
         );

INSERT INTO GRADE_SCALE (
    GRADE_NAME,
    LETTER_GRADE,
    MIN_PERCENTAGE,
    MAX_PERCENTAGE,
    GRADE_POINT,
    DISPLAY_ORDER,
    STATUS
) VALUES (
             'Very Good',
             'A-',
             60,
             69.99,
             3.50,
             3,
             'ACTIVE'
         );

INSERT INTO GRADE_SCALE (
    GRADE_NAME,
    LETTER_GRADE,
    MIN_PERCENTAGE,
    MAX_PERCENTAGE,
    GRADE_POINT,
    DISPLAY_ORDER,
    STATUS
) VALUES (
             'Good',
             'B',
             50,
             59.99,
             3.00,
             4,
             'ACTIVE'
         );

INSERT INTO GRADE_SCALE (
    GRADE_NAME,
    LETTER_GRADE,
    MIN_PERCENTAGE,
    MAX_PERCENTAGE,
    GRADE_POINT,
    DISPLAY_ORDER,
    STATUS
) VALUES (
             'Satisfactory',
             'C',
             40,
             49.99,
             2.00,
             5,
             'ACTIVE'
         );

INSERT INTO GRADE_SCALE (
    GRADE_NAME,
    LETTER_GRADE,
    MIN_PERCENTAGE,
    MAX_PERCENTAGE,
    GRADE_POINT,
    DISPLAY_ORDER,
    STATUS
) VALUES (
             'Pass',
             'D',
             33,
             39.99,
             1.00,
             6,
             'ACTIVE'
         );

INSERT INTO GRADE_SCALE (
    GRADE_NAME,
    LETTER_GRADE,
    MIN_PERCENTAGE,
    MAX_PERCENTAGE,
    GRADE_POINT,
    DISPLAY_ORDER,
    STATUS
) VALUES (
             'Fail',
             'F',
             0,
             32.99,
             0.00,
             7,
             'ACTIVE'
         );