----------------------------------------------------------------------
-- V18: FEE MANAGEMENT TABLES
----------------------------------------------------------------------

----------------------------------------------------------------------
-- 1. FEE TYPE
----------------------------------------------------------------------

CREATE TABLE FEE_TYPE (
                          FEE_TYPE_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                          FEE_TYPE_NAME    VARCHAR2(100) NOT NULL,
                          FEE_TYPE_CODE    VARCHAR2(30) NOT NULL,
                          DESCRIPTION      VARCHAR2(500),
                          DISPLAY_ORDER    NUMBER(5) DEFAULT 1 NOT NULL,
                          STATUS           VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
                          CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                          UPDATED_AT       TIMESTAMP,
                          CREATED_BY       NUMBER,
                          UPDATED_BY       NUMBER,

                          CONSTRAINT PK_FEE_TYPE
                              PRIMARY KEY (FEE_TYPE_ID),

                          CONSTRAINT UK_FEE_TYPE_NAME
                              UNIQUE (FEE_TYPE_NAME),

                          CONSTRAINT UK_FEE_TYPE_CODE
                              UNIQUE (FEE_TYPE_CODE),

                          CONSTRAINT CK_FEE_TYPE_STATUS
                              CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),

                          CONSTRAINT CK_FEE_TYPE_ORDER
                              CHECK (DISPLAY_ORDER > 0)
);

----------------------------------------------------------------------
-- 2. FEE STRUCTURE
----------------------------------------------------------------------

CREATE TABLE FEE_STRUCTURE (
                               FEE_STRUCTURE_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
                               ACADEMIC_YEAR_ID          NUMBER NOT NULL,
                               ACADEMIC_YEAR_CLASS_ID    NUMBER NOT NULL,
                               SECTION_ID                NUMBER,
                               FEE_TYPE_ID               NUMBER NOT NULL,
                               STRUCTURE_NAME            VARCHAR2(150) NOT NULL,
                               AMOUNT                    NUMBER(12,2) NOT NULL,
                               FREQUENCY                 VARCHAR2(20) NOT NULL,
                               DUE_DAY                   NUMBER(2),
                               EFFECTIVE_FROM            DATE NOT NULL,
                               EFFECTIVE_TO              DATE,
                               FINE_TYPE                 VARCHAR2(20) DEFAULT 'NONE' NOT NULL,
                               FINE_VALUE                NUMBER(12,2) DEFAULT 0 NOT NULL,
                               DESCRIPTION               VARCHAR2(500),
                               STATUS                    VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
                               CREATED_AT                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                               UPDATED_AT                TIMESTAMP,
                               CREATED_BY                NUMBER,
                               UPDATED_BY                NUMBER,

                               CONSTRAINT PK_FEE_STRUCTURE
                                   PRIMARY KEY (FEE_STRUCTURE_ID),

                               CONSTRAINT FK_FEE_STRUCTURE_YEAR
                                   FOREIGN KEY (ACADEMIC_YEAR_ID)
                                       REFERENCES ACADEMIC_YEARS (ACADEMIC_YEAR_ID),

                               CONSTRAINT FK_FEE_STRUCTURE_CLASS
                                   FOREIGN KEY (ACADEMIC_YEAR_CLASS_ID)
                                       REFERENCES ACADEMIC_YEAR_CLASSES (
                                                                         ACADEMIC_YEAR_CLASS_ID
                                           ),

                               CONSTRAINT FK_FEE_STRUCTURE_SECTION
                                   FOREIGN KEY (SECTION_ID)
                                       REFERENCES SECTIONS (SECTION_ID),

                               CONSTRAINT FK_FEE_STRUCTURE_TYPE
                                   FOREIGN KEY (FEE_TYPE_ID)
                                       REFERENCES FEE_TYPE (FEE_TYPE_ID),

                               CONSTRAINT UK_FEE_STRUCTURE
                                   UNIQUE (
                                           ACADEMIC_YEAR_ID,
                                           ACADEMIC_YEAR_CLASS_ID,
                                           SECTION_ID,
                                           FEE_TYPE_ID,
                                           STRUCTURE_NAME
                                       ),

                               CONSTRAINT CK_FEE_STRUCTURE_AMOUNT
                                   CHECK (AMOUNT > 0),

                               CONSTRAINT CK_FEE_FREQUENCY
                                   CHECK (
                                       FREQUENCY IN (
                                                     'ONE_TIME',
                                                     'MONTHLY',
                                                     'QUARTERLY',
                                                     'HALF_YEARLY',
                                                     'ANNUAL'
                                           )
                                       ),

                               CONSTRAINT CK_FEE_STRUCTURE_DUE_DAY
                                   CHECK (
                                       DUE_DAY IS NULL
                                           OR DUE_DAY BETWEEN 1 AND 31
                                       ),

                               CONSTRAINT CK_FEE_EFFECTIVE_DATES
                                   CHECK (
                                       EFFECTIVE_TO IS NULL
                                           OR EFFECTIVE_TO >= EFFECTIVE_FROM
                                       ),

                               CONSTRAINT CK_FEE_FINE_TYPE
                                   CHECK (
                                       FINE_TYPE IN (
                                                     'NONE',
                                                     'FIXED',
                                                     'PERCENTAGE'
                                           )
                                       ),

                               CONSTRAINT CK_FEE_FINE_VALUE
                                   CHECK (FINE_VALUE >= 0),

                               CONSTRAINT CK_FEE_STRUCTURE_STATUS
                                   CHECK (
                                       STATUS IN ('ACTIVE', 'INACTIVE')
                                       )
);

----------------------------------------------------------------------
-- 3. STUDENT FEE
----------------------------------------------------------------------

CREATE TABLE STUDENT_FEE (
                             STUDENT_FEE_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             FEE_STRUCTURE_ID     NUMBER NOT NULL,
                             STUDENT_ID           NUMBER NOT NULL,
                             BILLING_PERIOD       VARCHAR2(20) NOT NULL,
                             DUE_DATE             DATE NOT NULL,
                             BASE_AMOUNT          NUMBER(12,2) NOT NULL,
                             DISCOUNT_AMOUNT      NUMBER(12,2) DEFAULT 0 NOT NULL,
                             FINE_AMOUNT          NUMBER(12,2) DEFAULT 0 NOT NULL,
                             TOTAL_AMOUNT         NUMBER(12,2) NOT NULL,
                             PAID_AMOUNT          NUMBER(12,2) DEFAULT 0 NOT NULL,
                             BALANCE_AMOUNT       NUMBER(12,2) NOT NULL,
                             STATUS               VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
                             REMARKS              VARCHAR2(500),
                             CREATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             UPDATED_AT           TIMESTAMP,
                             CREATED_BY           NUMBER,
                             UPDATED_BY           NUMBER,

                             CONSTRAINT PK_STUDENT_FEE
                                 PRIMARY KEY (STUDENT_FEE_ID),

                             CONSTRAINT FK_STUDENT_FEE_STRUCTURE
                                 FOREIGN KEY (FEE_STRUCTURE_ID)
                                     REFERENCES FEE_STRUCTURE (FEE_STRUCTURE_ID),

                             CONSTRAINT FK_STUDENT_FEE_STUDENT
                                 FOREIGN KEY (STUDENT_ID)
                                     REFERENCES STUDENTS (STUDENT_ID),

                             CONSTRAINT UK_STUDENT_FEE
                                 UNIQUE (
                                         FEE_STRUCTURE_ID,
                                         STUDENT_ID,
                                         BILLING_PERIOD
                                     ),

                             CONSTRAINT CK_STUDENT_FEE_BASE
                                 CHECK (BASE_AMOUNT > 0),

                             CONSTRAINT CK_STUDENT_FEE_DISCOUNT
                                 CHECK (
                                     DISCOUNT_AMOUNT >= 0
                                         AND DISCOUNT_AMOUNT <= BASE_AMOUNT
                                     ),

                             CONSTRAINT CK_STUDENT_FEE_FINE
                                 CHECK (FINE_AMOUNT >= 0),

                             CONSTRAINT CK_STUDENT_FEE_TOTAL
                                 CHECK (TOTAL_AMOUNT >= 0),

                             CONSTRAINT CK_STUDENT_FEE_PAID
                                 CHECK (PAID_AMOUNT >= 0),

                             CONSTRAINT CK_STUDENT_FEE_BALANCE
                                 CHECK (BALANCE_AMOUNT >= 0),

                             CONSTRAINT CK_STUDENT_FEE_STATUS
                                 CHECK (
                                     STATUS IN (
                                                'PENDING',
                                                'PARTIALLY_PAID',
                                                'PAID',
                                                'OVERDUE',
                                                'WAIVED',
                                                'CANCELLED'
                                         )
                                     )
);

----------------------------------------------------------------------
-- 4. STUDENT FEE DISCOUNT
----------------------------------------------------------------------

CREATE TABLE STUDENT_FEE_DISCOUNT (
                                      STUDENT_FEE_DISCOUNT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                      STUDENT_FEE_ID          NUMBER NOT NULL,
                                      DISCOUNT_TYPE           VARCHAR2(20) NOT NULL,
                                      DISCOUNT_VALUE          NUMBER(12,2) NOT NULL,
                                      DISCOUNT_AMOUNT         NUMBER(12,2) NOT NULL,
                                      REASON                  VARCHAR2(500) NOT NULL,
                                      APPROVAL_STATUS         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
                                      APPROVED_BY             NUMBER,
                                      APPROVED_AT             TIMESTAMP,
                                      CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                      UPDATED_AT              TIMESTAMP,
                                      CREATED_BY              NUMBER,
                                      UPDATED_BY              NUMBER,

                                      CONSTRAINT PK_STUDENT_FEE_DISCOUNT
                                          PRIMARY KEY (STUDENT_FEE_DISCOUNT_ID),

                                      CONSTRAINT FK_FEE_DISCOUNT_STUDENT_FEE
                                          FOREIGN KEY (STUDENT_FEE_ID)
                                              REFERENCES STUDENT_FEE (STUDENT_FEE_ID),

                                      CONSTRAINT CK_FEE_DISCOUNT_TYPE
                                          CHECK (
                                              DISCOUNT_TYPE IN (
                                                                'FIXED',
                                                                'PERCENTAGE'
                                                  )
                                              ),

                                      CONSTRAINT CK_FEE_DISCOUNT_VALUE
                                          CHECK (DISCOUNT_VALUE > 0),

                                      CONSTRAINT CK_FEE_DISCOUNT_AMOUNT
                                          CHECK (DISCOUNT_AMOUNT > 0),

                                      CONSTRAINT CK_FEE_DISCOUNT_APPROVAL
                                          CHECK (
                                              APPROVAL_STATUS IN (
                                                                  'PENDING',
                                                                  'APPROVED',
                                                                  'REJECTED',
                                                                  'CANCELLED'
                                                  )
                                              )
);

----------------------------------------------------------------------
-- 5. FEE PAYMENT
----------------------------------------------------------------------

CREATE TABLE FEE_PAYMENT (
                             FEE_PAYMENT_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             STUDENT_ID           NUMBER NOT NULL,
                             RECEIPT_NUMBER       VARCHAR2(50) NOT NULL,
                             PAYMENT_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             PAYMENT_AMOUNT       NUMBER(12,2) NOT NULL,
                             PAYMENT_METHOD       VARCHAR2(20) NOT NULL,
                             TRANSACTION_REFERENCE VARCHAR2(100),
                             PAYMENT_STATUS       VARCHAR2(20) DEFAULT 'COMPLETED' NOT NULL,
                             NOTES                VARCHAR2(500),
                             RECEIVED_BY          NUMBER,
                             CREATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             UPDATED_AT           TIMESTAMP,
                             CREATED_BY           NUMBER,
                             UPDATED_BY           NUMBER,

                             CONSTRAINT PK_FEE_PAYMENT
                                 PRIMARY KEY (FEE_PAYMENT_ID),

                             CONSTRAINT UK_FEE_PAYMENT_RECEIPT
                                 UNIQUE (RECEIPT_NUMBER),

                             CONSTRAINT FK_FEE_PAYMENT_STUDENT
                                 FOREIGN KEY (STUDENT_ID)
                                     REFERENCES STUDENTS (STUDENT_ID),

                             CONSTRAINT CK_FEE_PAYMENT_AMOUNT
                                 CHECK (PAYMENT_AMOUNT > 0),

                             CONSTRAINT CK_FEE_PAYMENT_METHOD
                                 CHECK (
                                     PAYMENT_METHOD IN (
                                                        'CASH',
                                                        'CARD',
                                                        'BANK_TRANSFER',
                                                        'MOBILE_BANKING',
                                                        'CHEQUE',
                                                        'ONLINE'
                                         )
                                     ),

                             CONSTRAINT CK_FEE_PAYMENT_STATUS
                                 CHECK (
                                     PAYMENT_STATUS IN (
                                                        'PENDING',
                                                        'COMPLETED',
                                                        'FAILED',
                                                        'CANCELLED',
                                                        'REFUNDED'
                                         )
                                     )
);

----------------------------------------------------------------------
-- 6. FEE PAYMENT ALLOCATION
----------------------------------------------------------------------

CREATE TABLE FEE_PAYMENT_ALLOCATION (
                                        PAYMENT_ALLOCATION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                        FEE_PAYMENT_ID        NUMBER NOT NULL,
                                        STUDENT_FEE_ID        NUMBER NOT NULL,
                                        ALLOCATED_AMOUNT      NUMBER(12,2) NOT NULL,
                                        CREATED_AT            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                        CREATED_BY            NUMBER,

                                        CONSTRAINT PK_FEE_PAYMENT_ALLOCATION
                                            PRIMARY KEY (PAYMENT_ALLOCATION_ID),

                                        CONSTRAINT FK_ALLOCATION_PAYMENT
                                            FOREIGN KEY (FEE_PAYMENT_ID)
                                                REFERENCES FEE_PAYMENT (FEE_PAYMENT_ID),

                                        CONSTRAINT FK_ALLOCATION_STUDENT_FEE
                                            FOREIGN KEY (STUDENT_FEE_ID)
                                                REFERENCES STUDENT_FEE (STUDENT_FEE_ID),

                                        CONSTRAINT UK_PAYMENT_STUDENT_FEE
                                            UNIQUE (
                                                    FEE_PAYMENT_ID,
                                                    STUDENT_FEE_ID
                                                ),

                                        CONSTRAINT CK_ALLOCATION_AMOUNT
                                            CHECK (ALLOCATED_AMOUNT > 0)
);

----------------------------------------------------------------------
-- INDEXES
----------------------------------------------------------------------

CREATE INDEX IDX_FEE_STRUCTURE_YEAR
    ON FEE_STRUCTURE (ACADEMIC_YEAR_ID);

CREATE INDEX IDX_FEE_STRUCTURE_CLASS
    ON FEE_STRUCTURE (ACADEMIC_YEAR_CLASS_ID);

CREATE INDEX IDX_FEE_STRUCTURE_SECTION
    ON FEE_STRUCTURE (SECTION_ID);

CREATE INDEX IDX_FEE_STRUCTURE_TYPE
    ON FEE_STRUCTURE (FEE_TYPE_ID);

CREATE INDEX IDX_STUDENT_FEE_STRUCTURE
    ON STUDENT_FEE (FEE_STRUCTURE_ID);

CREATE INDEX IDX_STUDENT_FEE_STUDENT
    ON STUDENT_FEE (STUDENT_ID);

CREATE INDEX IDX_STUDENT_FEE_STATUS
    ON STUDENT_FEE (STATUS);

CREATE INDEX IDX_STUDENT_FEE_DUE_DATE
    ON STUDENT_FEE (DUE_DATE);

CREATE INDEX IDX_FEE_DISCOUNT_STUDENT_FEE
    ON STUDENT_FEE_DISCOUNT (STUDENT_FEE_ID);

CREATE INDEX IDX_FEE_DISCOUNT_APPROVAL
    ON STUDENT_FEE_DISCOUNT (APPROVAL_STATUS);

CREATE INDEX IDX_FEE_PAYMENT_STUDENT
    ON FEE_PAYMENT (STUDENT_ID);

CREATE INDEX IDX_FEE_PAYMENT_DATE
    ON FEE_PAYMENT (PAYMENT_DATE);

CREATE INDEX IDX_FEE_PAYMENT_STATUS
    ON FEE_PAYMENT (PAYMENT_STATUS);

CREATE INDEX IDX_ALLOCATION_PAYMENT
    ON FEE_PAYMENT_ALLOCATION (FEE_PAYMENT_ID);

CREATE INDEX IDX_ALLOCATION_STUDENT_FEE
    ON FEE_PAYMENT_ALLOCATION (STUDENT_FEE_ID);