---------------------------------------------------------
-- AUTH_PKG
---------------------------------------------------------
CREATE OR REPLACE PACKAGE AUTH_PKG AS
    PROCEDURE REGISTER_USER (
        P_USERNAME       IN USERS.USERNAME%TYPE,
        P_EMAIL          IN USERS.EMAIL%TYPE,
        P_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE,
        P_FULL_NAME      IN USERS.FULL_NAME%TYPE,
        P_USER_ID        OUT USERS.USER_ID%TYPE
    );

    PROCEDURE LOGIN_USER (
        P_USERNAME      IN USERS.USERNAME%TYPE,
        P_PASSWORD_HASH IN USERS.PASSWORD_HASH%TYPE,
        P_IP_ADDRESS    IN LOGIN_HISTORY.IP_ADDRESS%TYPE,
        P_USER_ID       OUT USERS.USER_ID%TYPE,
        P_STATUS        OUT USERS.STATUS%TYPE
    );

    PROCEDURE CHANGE_PASSWORD (
        P_USER_ID            IN USERS.USER_ID%TYPE,
        P_OLD_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE,
        P_NEW_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE
    );

    PROCEDURE LOCK_USER (
        P_USER_ID IN USERS.USER_ID%TYPE
    );

    PROCEDURE UNLOCK_USER (
        P_USER_ID IN USERS.USER_ID%TYPE
    );
END AUTH_PKG;
/

CREATE OR REPLACE PACKAGE BODY AUTH_PKG AS
    PROCEDURE REGISTER_USER (
        P_USERNAME       IN USERS.USERNAME%TYPE,
        P_EMAIL          IN USERS.EMAIL%TYPE,
        P_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE,
        P_FULL_NAME      IN USERS.FULL_NAME%TYPE,
        P_USER_ID        OUT USERS.USER_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO USERS (USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, STATUS)
        VALUES (P_USERNAME, P_EMAIL, P_PASSWORD_HASH, P_FULL_NAME, 'ACTIVE')
        RETURNING USER_ID INTO P_USER_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20001, 'USERNAME OR EMAIL ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR REGISTERING USER: ' || SQLERRM);
    END REGISTER_USER;

    PROCEDURE LOGIN_USER (
        P_USERNAME      IN USERS.USERNAME%TYPE,
        P_PASSWORD_HASH IN USERS.PASSWORD_HASH%TYPE,
        P_IP_ADDRESS    IN LOGIN_HISTORY.IP_ADDRESS%TYPE,
        P_USER_ID       OUT USERS.USER_ID%TYPE,
        P_STATUS        OUT USERS.STATUS%TYPE
    ) AS
        V_PASSWORD_HASH USERS.PASSWORD_HASH%TYPE;
        V_FAILED_LOGIN  USERS.FAILED_LOGIN%TYPE;
    BEGIN
        SELECT USER_ID, PASSWORD_HASH, STATUS, FAILED_LOGIN
        INTO P_USER_ID, V_PASSWORD_HASH, P_STATUS, V_FAILED_LOGIN
        FROM USERS
        WHERE USERNAME = P_USERNAME;

        IF P_STATUS = 'LOCKED' THEN
            INSERT INTO LOGIN_HISTORY (USER_ID, USERNAME, LOGIN_STATUS, IP_ADDRESS)
            VALUES (P_USER_ID, P_USERNAME, 'FAILED', P_IP_ADDRESS);

            RAISE_APPLICATION_ERROR(-20003, 'USER ACCOUNT IS LOCKED.');
        END IF;

        IF P_STATUS <> 'ACTIVE' THEN
            INSERT INTO LOGIN_HISTORY (USER_ID, USERNAME, LOGIN_STATUS, IP_ADDRESS)
            VALUES (P_USER_ID, P_USERNAME, 'FAILED', P_IP_ADDRESS);

            RAISE_APPLICATION_ERROR(-20004, 'USER ACCOUNT IS NOT ACTIVE.');
        END IF;

        IF V_PASSWORD_HASH = P_PASSWORD_HASH THEN
            UPDATE USERS
            SET FAILED_LOGIN = 0,
                LAST_LOGIN_AT = SYSTIMESTAMP,
                UPDATED_AT = SYSTIMESTAMP
            WHERE USER_ID = P_USER_ID;

            INSERT INTO LOGIN_HISTORY (USER_ID, USERNAME, LOGIN_STATUS, IP_ADDRESS)
            VALUES (P_USER_ID, P_USERNAME, 'SUCCESS', P_IP_ADDRESS);
        ELSE
            V_FAILED_LOGIN := V_FAILED_LOGIN + 1;

            UPDATE USERS
            SET FAILED_LOGIN = V_FAILED_LOGIN,
                STATUS = CASE WHEN V_FAILED_LOGIN >= 5 THEN 'LOCKED' ELSE STATUS END,
                UPDATED_AT = SYSTIMESTAMP
            WHERE USER_ID = P_USER_ID;

            INSERT INTO LOGIN_HISTORY (USER_ID, USERNAME, LOGIN_STATUS, IP_ADDRESS)
            VALUES (P_USER_ID, P_USERNAME, 'FAILED', P_IP_ADDRESS);

            RAISE_APPLICATION_ERROR(-20005, 'INVALID USERNAME OR PASSWORD.');
        END IF;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO LOGIN_HISTORY (USERNAME, LOGIN_STATUS, IP_ADDRESS)
            VALUES (P_USERNAME, 'FAILED', P_IP_ADDRESS);

            RAISE_APPLICATION_ERROR(-20006, 'INVALID USERNAME OR PASSWORD.');
        WHEN OTHERS THEN
            RAISE;
    END LOGIN_USER;

    PROCEDURE CHANGE_PASSWORD (
        P_USER_ID            IN USERS.USER_ID%TYPE,
        P_OLD_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE,
        P_NEW_PASSWORD_HASH  IN USERS.PASSWORD_HASH%TYPE
    ) AS
        V_PASSWORD_HASH USERS.PASSWORD_HASH%TYPE;
    BEGIN
        SELECT PASSWORD_HASH
        INTO V_PASSWORD_HASH
        FROM USERS
        WHERE USER_ID = P_USER_ID
          AND STATUS = 'ACTIVE';

        IF V_PASSWORD_HASH <> P_OLD_PASSWORD_HASH THEN
            RAISE_APPLICATION_ERROR(-20007, 'OLD PASSWORD IS INCORRECT.');
        END IF;

        UPDATE USERS
        SET PASSWORD_HASH = P_NEW_PASSWORD_HASH,
            UPDATED_AT = SYSTIMESTAMP
        WHERE USER_ID = P_USER_ID;

        INSERT INTO PASSWORD_HISTORY (USER_ID, PASSWORD_HASH)
        VALUES (P_USER_ID, P_NEW_PASSWORD_HASH);

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20008, 'ACTIVE USER NOT FOUND.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20009, 'ERROR CHANGING PASSWORD: ' || SQLERRM);
    END CHANGE_PASSWORD;

    PROCEDURE LOCK_USER (
        P_USER_ID IN USERS.USER_ID%TYPE
    ) AS
    BEGIN
        UPDATE USERS
        SET STATUS = 'LOCKED',
            UPDATED_AT = SYSTIMESTAMP
        WHERE USER_ID = P_USER_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20010, 'USER NOT FOUND.');
        END IF;
    END LOCK_USER;

    PROCEDURE UNLOCK_USER (
        P_USER_ID IN USERS.USER_ID%TYPE
    ) AS
    BEGIN
        UPDATE USERS
        SET STATUS = 'ACTIVE',
            FAILED_LOGIN = 0,
            UPDATED_AT = SYSTIMESTAMP
        WHERE USER_ID = P_USER_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20011, 'USER NOT FOUND.');
        END IF;
    END UNLOCK_USER;
END AUTH_PKG;
/

---------------------------------------------------------
-- ROLE_PKG
---------------------------------------------------------
CREATE OR REPLACE PACKAGE ROLE_PKG AS
    PROCEDURE ADD_ROLE (
        P_ROLE_NAME   IN ROLES.ROLE_NAME%TYPE,
        P_DESCRIPTION IN ROLES.DESCRIPTION%TYPE,
        P_ROLE_ID     OUT ROLES.ROLE_ID%TYPE
    );

    PROCEDURE UPDATE_ROLE (
        P_ROLE_ID     IN ROLES.ROLE_ID%TYPE,
        P_ROLE_NAME   IN ROLES.ROLE_NAME%TYPE,
        P_DESCRIPTION IN ROLES.DESCRIPTION%TYPE,
        P_STATUS      IN ROLES.STATUS%TYPE
    );

    PROCEDURE DELETE_ROLE (
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE
    );

    PROCEDURE ASSIGN_ROLE_TO_USER (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE
    );

    PROCEDURE REMOVE_ROLE_FROM_USER (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE
    );

    PROCEDURE GET_USER_ROLES (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    );
END ROLE_PKG;
/

CREATE OR REPLACE PACKAGE BODY ROLE_PKG AS
    PROCEDURE ADD_ROLE (
        P_ROLE_NAME   IN ROLES.ROLE_NAME%TYPE,
        P_DESCRIPTION IN ROLES.DESCRIPTION%TYPE,
        P_ROLE_ID     OUT ROLES.ROLE_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO ROLES (ROLE_NAME, DESCRIPTION)
        VALUES (UPPER(TRIM(P_ROLE_NAME)), P_DESCRIPTION)
        RETURNING ROLE_ID INTO P_ROLE_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20101, 'ROLE ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20102, 'ERROR ADDING ROLE: ' || SQLERRM);
    END ADD_ROLE;

    PROCEDURE UPDATE_ROLE (
        P_ROLE_ID     IN ROLES.ROLE_ID%TYPE,
        P_ROLE_NAME   IN ROLES.ROLE_NAME%TYPE,
        P_DESCRIPTION IN ROLES.DESCRIPTION%TYPE,
        P_STATUS      IN ROLES.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE ROLES
        SET ROLE_NAME   = UPPER(TRIM(P_ROLE_NAME)),
            DESCRIPTION = P_DESCRIPTION,
            STATUS      = UPPER(TRIM(P_STATUS)),
            UPDATED_AT  = SYSTIMESTAMP
        WHERE ROLE_ID = P_ROLE_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20103, 'ROLE NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20104, 'ROLE NAME ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20105, 'ERROR UPDATING ROLE: ' || SQLERRM);
    END UPDATE_ROLE;

    PROCEDURE DELETE_ROLE (
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE
    ) AS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM USER_ROLES
        WHERE ROLE_ID = P_ROLE_ID;

        IF V_COUNT > 0 THEN
            RAISE_APPLICATION_ERROR(-20106, 'ROLE IS ASSIGNED TO USERS AND CANNOT BE DELETED.');
        END IF;

        DELETE FROM ROLE_PERMISSIONS
        WHERE ROLE_ID = P_ROLE_ID;

        DELETE FROM ROLES
        WHERE ROLE_ID = P_ROLE_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20107, 'ROLE NOT FOUND.');
        END IF;
    END DELETE_ROLE;

    PROCEDURE ASSIGN_ROLE_TO_USER (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
        VALUES (P_USER_ID, P_ROLE_ID);

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20108, 'ROLE IS ALREADY ASSIGNED TO THIS USER.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20109, 'ERROR ASSIGNING ROLE: ' || SQLERRM);
    END ASSIGN_ROLE_TO_USER;

    PROCEDURE REMOVE_ROLE_FROM_USER (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM USER_ROLES
        WHERE USER_ID = P_USER_ID
          AND ROLE_ID = P_ROLE_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20110, 'USER DOES NOT HAVE THIS ROLE.');
        END IF;
    END REMOVE_ROLE_FROM_USER;

    PROCEDURE GET_USER_ROLES (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT R.ROLE_ID,
                   R.ROLE_NAME,
                   R.DESCRIPTION,
                   UR.ASSIGNED_AT
            FROM USER_ROLES UR
            INNER JOIN ROLES R ON UR.ROLE_ID = R.ROLE_ID
            WHERE UR.USER_ID = P_USER_ID
            ORDER BY R.ROLE_NAME;
    END GET_USER_ROLES;
END ROLE_PKG;
/

---------------------------------------------------------
-- PERMISSION_PKG
---------------------------------------------------------
CREATE OR REPLACE PACKAGE PERMISSION_PKG AS
    PROCEDURE ADD_PERMISSION (
        P_PERMISSION_CODE IN PERMISSIONS.PERMISSION_CODE%TYPE,
        P_DESCRIPTION     IN PERMISSIONS.DESCRIPTION%TYPE,
        P_PERMISSION_ID   OUT PERMISSIONS.PERMISSION_ID%TYPE
    );

    PROCEDURE UPDATE_PERMISSION (
        P_PERMISSION_ID   IN PERMISSIONS.PERMISSION_ID%TYPE,
        P_PERMISSION_CODE IN PERMISSIONS.PERMISSION_CODE%TYPE,
        P_DESCRIPTION     IN PERMISSIONS.DESCRIPTION%TYPE,
        P_STATUS          IN PERMISSIONS.STATUS%TYPE
    );

    PROCEDURE ASSIGN_PERMISSION_TO_ROLE (
        P_ROLE_ID       IN ROLES.ROLE_ID%TYPE,
        P_PERMISSION_ID IN PERMISSIONS.PERMISSION_ID%TYPE
    );

    PROCEDURE REMOVE_PERMISSION_FROM_ROLE (
        P_ROLE_ID       IN ROLES.ROLE_ID%TYPE,
        P_PERMISSION_ID IN PERMISSIONS.PERMISSION_ID%TYPE
    );

    PROCEDURE GET_ROLE_PERMISSIONS (
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    );

    PROCEDURE GET_USER_PERMISSIONS (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    );
END PERMISSION_PKG;
/

CREATE OR REPLACE PACKAGE BODY PERMISSION_PKG AS
    PROCEDURE ADD_PERMISSION (
        P_PERMISSION_CODE IN PERMISSIONS.PERMISSION_CODE%TYPE,
        P_DESCRIPTION     IN PERMISSIONS.DESCRIPTION%TYPE,
        P_PERMISSION_ID   OUT PERMISSIONS.PERMISSION_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO PERMISSIONS (PERMISSION_CODE, DESCRIPTION)
        VALUES (UPPER(TRIM(P_PERMISSION_CODE)), P_DESCRIPTION)
        RETURNING PERMISSION_ID INTO P_PERMISSION_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20201, 'PERMISSION ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20202, 'ERROR ADDING PERMISSION: ' || SQLERRM);
    END ADD_PERMISSION;

    PROCEDURE UPDATE_PERMISSION (
        P_PERMISSION_ID   IN PERMISSIONS.PERMISSION_ID%TYPE,
        P_PERMISSION_CODE IN PERMISSIONS.PERMISSION_CODE%TYPE,
        P_DESCRIPTION     IN PERMISSIONS.DESCRIPTION%TYPE,
        P_STATUS          IN PERMISSIONS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE PERMISSIONS
        SET PERMISSION_CODE = UPPER(TRIM(P_PERMISSION_CODE)),
            DESCRIPTION     = P_DESCRIPTION,
            STATUS          = UPPER(TRIM(P_STATUS)),
            UPDATED_AT      = SYSTIMESTAMP
        WHERE PERMISSION_ID = P_PERMISSION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20203, 'PERMISSION NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20204, 'PERMISSION CODE ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20205, 'ERROR UPDATING PERMISSION: ' || SQLERRM);
    END UPDATE_PERMISSION;

    PROCEDURE ASSIGN_PERMISSION_TO_ROLE (
        P_ROLE_ID       IN ROLES.ROLE_ID%TYPE,
        P_PERMISSION_ID IN PERMISSIONS.PERMISSION_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
        VALUES (P_ROLE_ID, P_PERMISSION_ID);

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20206, 'PERMISSION ALREADY ASSIGNED TO THIS ROLE.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20207, 'ERROR ASSIGNING PERMISSION: ' || SQLERRM);
    END ASSIGN_PERMISSION_TO_ROLE;

    PROCEDURE REMOVE_PERMISSION_FROM_ROLE (
        P_ROLE_ID       IN ROLES.ROLE_ID%TYPE,
        P_PERMISSION_ID IN PERMISSIONS.PERMISSION_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM ROLE_PERMISSIONS
        WHERE ROLE_ID = P_ROLE_ID
          AND PERMISSION_ID = P_PERMISSION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20208, 'ROLE DOES NOT HAVE THIS PERMISSION.');
        END IF;
    END REMOVE_PERMISSION_FROM_ROLE;

    PROCEDURE GET_ROLE_PERMISSIONS (
        P_ROLE_ID IN ROLES.ROLE_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT P.PERMISSION_ID,
                   P.PERMISSION_CODE,
                   P.DESCRIPTION,
                   RP.ASSIGNED_AT
            FROM ROLE_PERMISSIONS RP
            INNER JOIN PERMISSIONS P ON RP.PERMISSION_ID = P.PERMISSION_ID
            WHERE RP.ROLE_ID = P_ROLE_ID
              AND P.STATUS = 'ACTIVE'
            ORDER BY P.PERMISSION_CODE;
    END GET_ROLE_PERMISSIONS;

    PROCEDURE GET_USER_PERMISSIONS (
        P_USER_ID IN USERS.USER_ID%TYPE,
        P_RESULT  OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT DISTINCT
                   P.PERMISSION_ID,
                   P.PERMISSION_CODE,
                   P.DESCRIPTION
            FROM USER_ROLES UR
            INNER JOIN ROLES R ON UR.ROLE_ID = R.ROLE_ID
            INNER JOIN ROLE_PERMISSIONS RP ON R.ROLE_ID = RP.ROLE_ID
            INNER JOIN PERMISSIONS P ON RP.PERMISSION_ID = P.PERMISSION_ID
            WHERE UR.USER_ID = P_USER_ID
              AND R.STATUS = 'ACTIVE'
              AND P.STATUS = 'ACTIVE'
            ORDER BY P.PERMISSION_CODE;
    END GET_USER_PERMISSIONS;
END PERMISSION_PKG;
/
