---------------------------------------------------------
-- CREATE STUDENT_PKG SPECIFICATION
---------------------------------------------------------
CREATE OR REPLACE PACKAGE STUDENT_PKG AS
    PROCEDURE ADD_STUDENT (
        P_STUDENT_CODE    IN STUDENTS.STUDENT_CODE%TYPE,
        P_FIRST_NAME      IN STUDENTS.FIRST_NAME%TYPE,
        P_LAST_NAME       IN STUDENTS.LAST_NAME%TYPE,
        P_EMAIL           IN STUDENTS.EMAIL%TYPE,
        P_PHONE           IN STUDENTS.PHONE%TYPE,
        P_GENDER          IN STUDENTS.GENDER%TYPE,
        P_DATE_OF_BIRTH   IN STUDENTS.DATE_OF_BIRTH%TYPE,
        P_ADMISSION_DATE  IN STUDENTS.ADMISSION_DATE%TYPE,
        P_STUDENT_ID      OUT STUDENTS.STUDENT_ID%TYPE
    );
    PROCEDURE UPDATE_STUDENT (
        P_STUDENT_ID      IN STUDENTS.STUDENT_ID%TYPE,
        P_FIRST_NAME      IN STUDENTS.FIRST_NAME%TYPE,
        P_LAST_NAME       IN STUDENTS.LAST_NAME%TYPE,
        P_EMAIL           IN STUDENTS.EMAIL%TYPE,
        P_PHONE           IN STUDENTS.PHONE%TYPE,
        P_GENDER          IN STUDENTS.GENDER%TYPE,
        P_DATE_OF_BIRTH   IN STUDENTS.DATE_OF_BIRTH%TYPE,
        P_ADMISSION_DATE  IN STUDENTS.ADMISSION_DATE%TYPE,
        P_STATUS          IN STUDENTS.STATUS%TYPE
    );

    PROCEDURE DELETE_STUDENT (
        P_STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE
    );

    PROCEDURE GET_STUDENT_BY_ID (
        P_STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_STUDENTS (
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE SEARCH_STUDENTS (
        P_SEARCH_TEXT IN VARCHAR2,
        P_RESULT      OUT SYS_REFCURSOR
    );
END STUDENT_PKG;
/

---------------------------------------------------------
-- CREATE STUDENT_PKG BODY
---------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY STUDENT_PKG AS

    PROCEDURE ADD_STUDENT (
        P_STUDENT_CODE    IN STUDENTS.STUDENT_CODE%TYPE,
        P_FIRST_NAME      IN STUDENTS.FIRST_NAME%TYPE,
        P_LAST_NAME       IN STUDENTS.LAST_NAME%TYPE,
        P_EMAIL           IN STUDENTS.EMAIL%TYPE,
        P_PHONE           IN STUDENTS.PHONE%TYPE,
        P_GENDER          IN STUDENTS.GENDER%TYPE,
        P_DATE_OF_BIRTH   IN STUDENTS.DATE_OF_BIRTH%TYPE,
        P_ADMISSION_DATE  IN STUDENTS.ADMISSION_DATE%TYPE,
        P_STUDENT_ID      OUT STUDENTS.STUDENT_ID%TYPE
    ) AS
BEGIN
INSERT INTO STUDENTS (
    STUDENT_CODE,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    ADMISSION_DATE,
    STATUS
) VALUES (
     P_STUDENT_CODE,
     P_FIRST_NAME,
     P_LAST_NAME,
     P_EMAIL,
     P_PHONE,
     UPPER(TRIM(P_GENDER)),
     P_DATE_OF_BIRTH,
     NVL(P_ADMISSION_DATE, SYSDATE),
     'ACTIVE'
 )
    RETURNING STUDENT_ID INTO P_STUDENT_ID;

EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20301, 'STUDENT CODE, EMAIL, OR PHONE ALREADY EXISTS.');
WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20302, 'ERROR ADDING STUDENT: ' || SQLERRM);
END ADD_STUDENT;

    PROCEDURE UPDATE_STUDENT (
        P_STUDENT_ID      IN STUDENTS.STUDENT_ID%TYPE,
        P_FIRST_NAME      IN STUDENTS.FIRST_NAME%TYPE,
        P_LAST_NAME       IN STUDENTS.LAST_NAME%TYPE,
        P_EMAIL           IN STUDENTS.EMAIL%TYPE,
        P_PHONE           IN STUDENTS.PHONE%TYPE,
        P_GENDER          IN STUDENTS.GENDER%TYPE,
        P_DATE_OF_BIRTH   IN STUDENTS.DATE_OF_BIRTH%TYPE,
        P_ADMISSION_DATE  IN STUDENTS.ADMISSION_DATE%TYPE,
        P_STATUS          IN STUDENTS.STATUS%TYPE
    ) AS
BEGIN
UPDATE STUDENTS
SET FIRST_NAME     = P_FIRST_NAME,
    LAST_NAME      = P_LAST_NAME,
    EMAIL          = P_EMAIL,
    PHONE          = P_PHONE,
    GENDER         = UPPER(TRIM(P_GENDER)),
    DATE_OF_BIRTH  = P_DATE_OF_BIRTH,
    ADMISSION_DATE = P_ADMISSION_DATE,
    STATUS         = UPPER(TRIM(P_STATUS)),
    UPDATED_AT     = SYSTIMESTAMP
WHERE STUDENT_ID = P_STUDENT_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20303, 'STUDENT NOT FOUND.');
END IF;

EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20304, 'STUDENT EMAIL OR PHONE ALREADY EXISTS.');
WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20305, 'ERROR UPDATING STUDENT: ' || SQLERRM);
END UPDATE_STUDENT;


    PROCEDURE DELETE_STUDENT (
        P_STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE
    ) AS
BEGIN
DELETE FROM STUDENT_GUARDIANS
WHERE STUDENT_ID = P_STUDENT_ID;

DELETE FROM STUDENT_ADDRESSES
WHERE STUDENT_ID = P_STUDENT_ID;

DELETE FROM STUDENTS
WHERE STUDENT_ID = P_STUDENT_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20306, 'STUDENT NOT FOUND.');
END IF;

EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20307, 'ERROR DELETING STUDENT: ' || SQLERRM);
END DELETE_STUDENT;


    PROCEDURE GET_STUDENT_BY_ID (
        P_STUDENT_ID IN STUDENTS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
BEGIN
OPEN P_RESULT FOR
SELECT
    STUDENT_ID,
    STUDENT_CODE,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    ADMISSION_DATE,
    STATUS,
    CREATED_AT,
    UPDATED_AT
FROM STUDENTS
WHERE STUDENT_ID = P_STUDENT_ID;
END GET_STUDENT_BY_ID;


    PROCEDURE GET_ALL_STUDENTS (
        P_RESULT OUT SYS_REFCURSOR
    ) AS
BEGIN
OPEN P_RESULT FOR
SELECT
    STUDENT_ID,
    STUDENT_CODE,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    ADMISSION_DATE,
    STATUS,
    CREATED_AT,
    UPDATED_AT
FROM STUDENTS
ORDER BY STUDENT_ID DESC;
END GET_ALL_STUDENTS;

    PROCEDURE SEARCH_STUDENTS (
        P_SEARCH_TEXT IN VARCHAR2,
        P_RESULT      OUT SYS_REFCURSOR
    ) AS
BEGIN
OPEN P_RESULT FOR
SELECT
    STUDENT_ID,
    STUDENT_CODE,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    GENDER,
    DATE_OF_BIRTH,
    ADMISSION_DATE,
    STATUS,
    CREATED_AT,
    UPDATED_AT
FROM STUDENTS
    WHERE LOWER(STUDENT_CODE) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
       OR LOWER(FIRST_NAME) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
       OR LOWER(LAST_NAME) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
       OR LOWER(EMAIL) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
       OR LOWER(PHONE) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
    ORDER BY STUDENT_ID DESC;
END SEARCH_STUDENTS;

END STUDENT_PKG;
/

---------------------------------------------------------------
-- CREATE STUDENT_ADDRESS_PKG SPECIFICATION
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE STUDENT_ADDRESS_PKG AS

    PROCEDURE ADD_ADDRESS (
        P_STUDENT_ID     IN STUDENT_ADDRESSES.STUDENT_ID%TYPE,
        P_ADDRESS_TYPE   IN STUDENT_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN STUDENT_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN STUDENT_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN STUDENT_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN STUDENT_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN STUDENT_ADDRESSES.COUNTRY%TYPE,
        P_ADDRESS_ID     OUT STUDENT_ADDRESSES.ADDRESS_ID%TYPE
    );

    PROCEDURE UPDATE_ADDRESS (
        P_ADDRESS_ID     IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE,
        P_ADDRESS_TYPE   IN STUDENT_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN STUDENT_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN STUDENT_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN STUDENT_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN STUDENT_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN STUDENT_ADDRESSES.COUNTRY%TYPE
    );

    PROCEDURE DELETE_ADDRESS (
        P_ADDRESS_ID IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE
    );

    PROCEDURE GET_ADDRESS_BY_ID (
        P_ADDRESS_ID IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ADDRESSES_BY_STUDENT (
        P_STUDENT_ID IN STUDENT_ADDRESSES.STUDENT_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

END STUDENT_ADDRESS_PKG;
/

---------------------------------------------------------------
-- CREATE STUDENT_ADDRESS_PKG BODY
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY STUDENT_ADDRESS_PKG AS

    PROCEDURE ADD_ADDRESS (
    P_STUDENT_ID     IN STUDENT_ADDRESSES.STUDENT_ID%TYPE,
    P_ADDRESS_TYPE   IN STUDENT_ADDRESSES.ADDRESS_TYPE%TYPE,
    P_ADDRESS_LINE   IN STUDENT_ADDRESSES.ADDRESS_LINE%TYPE,
    P_CITY           IN STUDENT_ADDRESSES.CITY%TYPE,
    P_DISTRICT       IN STUDENT_ADDRESSES.DISTRICT%TYPE,
    P_POSTAL_CODE    IN STUDENT_ADDRESSES.POSTAL_CODE%TYPE,
    P_COUNTRY        IN STUDENT_ADDRESSES.COUNTRY%TYPE,
    P_ADDRESS_ID     OUT STUDENT_ADDRESSES.ADDRESS_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO STUDENT_ADDRESSES (
            STUDENT_ID,
            ADDRESS_TYPE,
            ADDRESS_LINE,
            CITY,
            DISTRICT,
            POSTAL_CODE,
            COUNTRY
        ) VALUES (
            P_STUDENT_ID,
            UPPER(TRIM(P_ADDRESS_TYPE)),
            P_ADDRESS_LINE,
            P_CITY,
            P_DISTRICT,
            P_POSTAL_CODE,
            NVL(P_COUNTRY, 'Bangladesh')
        )
        RETURNING ADDRESS_ID INTO P_ADDRESS_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20403,
                'STUDENT ALREADY HAS THIS ADDRESS TYPE.'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20404,
                'ERROR ADDING STUDENT ADDRESS: ' || SQLERRM
            );
    END ADD_ADDRESS;

    PROCEDURE UPDATE_ADDRESS (
        P_ADDRESS_ID     IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE,
        P_ADDRESS_TYPE   IN STUDENT_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN STUDENT_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN STUDENT_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN STUDENT_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN STUDENT_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN STUDENT_ADDRESSES.COUNTRY%TYPE
    ) AS
    BEGIN
        UPDATE STUDENT_ADDRESSES
        SET ADDRESS_TYPE = UPPER(TRIM(P_ADDRESS_TYPE)),
            ADDRESS_LINE = P_ADDRESS_LINE,
            CITY = P_CITY,
            DISTRICT = P_DISTRICT,
            POSTAL_CODE = P_POSTAL_CODE,
            COUNTRY = NVL(P_COUNTRY, 'Bangladesh'),
            UPDATED_AT = SYSTIMESTAMP
        WHERE ADDRESS_ID = P_ADDRESS_ID;

        IF SQL%ROWCOUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20401, 'ADDRESS NOT FOUND.');
            END IF;

        EXCEPTION
            WHEN DUP_VAL_ON_INDEX THEN
                RAISE_APPLICATION_ERROR(
                    -20405,
                    'STUDENT ALREADY HAS THIS ADDRESS TYPE.'
                );

            WHEN OTHERS THEN
                RAISE_APPLICATION_ERROR(
                    -20406,
                    'ERROR UPDATING STUDENT ADDRESS: ' || SQLERRM
                );
    END UPDATE_ADDRESS;


    PROCEDURE DELETE_ADDRESS (
        P_ADDRESS_ID IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM STUDENT_ADDRESSES
        WHERE ADDRESS_ID = P_ADDRESS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20402, 'ADDRESS NOT FOUND.');
        END IF;
    END DELETE_ADDRESS;


    PROCEDURE GET_ADDRESS_BY_ID (
        P_ADDRESS_ID IN STUDENT_ADDRESSES.ADDRESS_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT ADDRESS_ID, STUDENT_ID, ADDRESS_TYPE, ADDRESS_LINE,
                   CITY, DISTRICT, POSTAL_CODE, COUNTRY, CREATED_AT, UPDATED_AT
            FROM STUDENT_ADDRESSES
            WHERE ADDRESS_ID = P_ADDRESS_ID;
    END GET_ADDRESS_BY_ID;


    PROCEDURE GET_ADDRESSES_BY_STUDENT (
        P_STUDENT_ID IN STUDENT_ADDRESSES.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT ADDRESS_ID, STUDENT_ID, ADDRESS_TYPE, ADDRESS_LINE,
                   CITY, DISTRICT, POSTAL_CODE, COUNTRY, CREATED_AT, UPDATED_AT
            FROM STUDENT_ADDRESSES
            WHERE STUDENT_ID = P_STUDENT_ID
            ORDER BY ADDRESS_ID;
    END GET_ADDRESSES_BY_STUDENT;

END STUDENT_ADDRESS_PKG;
/

----------------------------------------------------------------
-- CREATE STUDENT_GUARDIAN_PKG SPECIFICATION
----------------------------------------------------------------
CREATE OR REPLACE PACKAGE STUDENT_GUARDIAN_PKG AS

    PROCEDURE ADD_GUARDIAN (
        P_STUDENT_ID      IN STUDENT_GUARDIANS.STUDENT_ID%TYPE,
        P_GUARDIAN_NAME   IN STUDENT_GUARDIANS.GUARDIAN_NAME%TYPE,
        P_RELATIONSHIP    IN STUDENT_GUARDIANS.RELATIONSHIP%TYPE,
        P_PHONE           IN STUDENT_GUARDIANS.PHONE%TYPE,
        P_EMAIL           IN STUDENT_GUARDIANS.EMAIL%TYPE,
        P_OCCUPATION      IN STUDENT_GUARDIANS.OCCUPATION%TYPE,
        P_IS_PRIMARY      IN STUDENT_GUARDIANS.IS_PRIMARY%TYPE,
        P_GUARDIAN_ID     OUT STUDENT_GUARDIANS.GUARDIAN_ID%TYPE
    );

    PROCEDURE UPDATE_GUARDIAN (
        P_GUARDIAN_ID     IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE,
        P_GUARDIAN_NAME   IN STUDENT_GUARDIANS.GUARDIAN_NAME%TYPE,
        P_RELATIONSHIP    IN STUDENT_GUARDIANS.RELATIONSHIP%TYPE,
        P_PHONE           IN STUDENT_GUARDIANS.PHONE%TYPE,
        P_EMAIL           IN STUDENT_GUARDIANS.EMAIL%TYPE,
        P_OCCUPATION      IN STUDENT_GUARDIANS.OCCUPATION%TYPE,
        P_IS_PRIMARY      IN STUDENT_GUARDIANS.IS_PRIMARY%TYPE
    );

    PROCEDURE DELETE_GUARDIAN (
        P_GUARDIAN_ID IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE
    );

    PROCEDURE GET_GUARDIAN_BY_ID (
        P_GUARDIAN_ID IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE,
        P_RESULT      OUT SYS_REFCURSOR
    );

    PROCEDURE GET_GUARDIANS_BY_STUDENT (
        P_STUDENT_ID IN STUDENT_GUARDIANS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

END STUDENT_GUARDIAN_PKG;
/

----------------------------------------------------------------
-- CREATE STUDENT_GUARDIAN_PKG BODY
----------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY STUDENT_GUARDIAN_PKG AS

    PROCEDURE ADD_GUARDIAN (
        P_STUDENT_ID      IN STUDENT_GUARDIANS.STUDENT_ID%TYPE,
        P_GUARDIAN_NAME   IN STUDENT_GUARDIANS.GUARDIAN_NAME%TYPE,
        P_RELATIONSHIP    IN STUDENT_GUARDIANS.RELATIONSHIP%TYPE,
        P_PHONE           IN STUDENT_GUARDIANS.PHONE%TYPE,
        P_EMAIL           IN STUDENT_GUARDIANS.EMAIL%TYPE,
        P_OCCUPATION      IN STUDENT_GUARDIANS.OCCUPATION%TYPE,
        P_IS_PRIMARY      IN STUDENT_GUARDIANS.IS_PRIMARY%TYPE,
        P_GUARDIAN_ID     OUT STUDENT_GUARDIANS.GUARDIAN_ID%TYPE
    ) AS
BEGIN
INSERT INTO STUDENT_GUARDIANS (
    STUDENT_ID,
    GUARDIAN_NAME,
    RELATIONSHIP,
    PHONE,
    EMAIL,
    OCCUPATION,
    IS_PRIMARY
)
VALUES (
           P_STUDENT_ID,
           P_GUARDIAN_NAME,
           P_RELATIONSHIP,
           P_PHONE,
           P_EMAIL,
           P_OCCUPATION,
           UPPER(TRIM(P_IS_PRIMARY))
       )
    RETURNING GUARDIAN_ID INTO P_GUARDIAN_ID;
END ADD_GUARDIAN;


    PROCEDURE UPDATE_GUARDIAN (
        P_GUARDIAN_ID     IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE,
        P_GUARDIAN_NAME   IN STUDENT_GUARDIANS.GUARDIAN_NAME%TYPE,
        P_RELATIONSHIP    IN STUDENT_GUARDIANS.RELATIONSHIP%TYPE,
        P_PHONE           IN STUDENT_GUARDIANS.PHONE%TYPE,
        P_EMAIL           IN STUDENT_GUARDIANS.EMAIL%TYPE,
        P_OCCUPATION      IN STUDENT_GUARDIANS.OCCUPATION%TYPE,
        P_IS_PRIMARY      IN STUDENT_GUARDIANS.IS_PRIMARY%TYPE
    ) AS
BEGIN
UPDATE STUDENT_GUARDIANS
SET GUARDIAN_NAME = P_GUARDIAN_NAME,
    RELATIONSHIP  = P_RELATIONSHIP,
    PHONE         = P_PHONE,
    EMAIL         = P_EMAIL,
    OCCUPATION    = P_OCCUPATION,
    IS_PRIMARY    = UPPER(TRIM(P_IS_PRIMARY)),
    UPDATED_AT    = SYSTIMESTAMP
WHERE GUARDIAN_ID = P_GUARDIAN_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20501, 'GUARDIAN NOT FOUND.');
END IF;
END UPDATE_GUARDIAN;


    PROCEDURE DELETE_GUARDIAN (
        P_GUARDIAN_ID IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE
    ) AS
BEGIN
DELETE FROM STUDENT_GUARDIANS
WHERE GUARDIAN_ID = P_GUARDIAN_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20502, 'GUARDIAN NOT FOUND.');
END IF;
END DELETE_GUARDIAN;


    PROCEDURE GET_GUARDIAN_BY_ID (
        P_GUARDIAN_ID IN STUDENT_GUARDIANS.GUARDIAN_ID%TYPE,
        P_RESULT      OUT SYS_REFCURSOR
    ) AS
BEGIN
    OPEN P_RESULT FOR
        SELECT GUARDIAN_ID,
            STUDENT_ID,
            GUARDIAN_NAME,
            RELATIONSHIP,
            PHONE,
            EMAIL,
            OCCUPATION,
            IS_PRIMARY,
            CREATED_AT,
            UPDATED_AT
        FROM STUDENT_GUARDIANS
    WHERE GUARDIAN_ID = P_GUARDIAN_ID;
END GET_GUARDIAN_BY_ID;


    PROCEDURE GET_GUARDIANS_BY_STUDENT (
        P_STUDENT_ID IN STUDENT_GUARDIANS.STUDENT_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT GUARDIAN_ID,
                STUDENT_ID,
                GUARDIAN_NAME,
                RELATIONSHIP,
                PHONE,
                EMAIL,
                OCCUPATION,
                IS_PRIMARY,
                CREATED_AT,
                UPDATED_AT
            FROM STUDENT_GUARDIANS
        WHERE STUDENT_ID = P_STUDENT_ID
    ORDER BY GUARDIAN_ID;
END GET_GUARDIANS_BY_STUDENT;

END STUDENT_GUARDIAN_PKG;
/
