---------------------------------------------------------------
-- CREATE TEACHER_PKG SPECIFICATION
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE TEACHER_PKG AS

    PROCEDURE ADD_TEACHER (
        P_TEACHER_CODE   IN TEACHERS.TEACHER_CODE%TYPE,
        P_FIRST_NAME     IN TEACHERS.FIRST_NAME%TYPE,
        P_LAST_NAME      IN TEACHERS.LAST_NAME%TYPE,
        P_EMAIL          IN TEACHERS.EMAIL%TYPE,
        P_PHONE          IN TEACHERS.PHONE%TYPE,
        P_GENDER         IN TEACHERS.GENDER%TYPE,
        P_DATE_OF_BIRTH  IN TEACHERS.DATE_OF_BIRTH%TYPE,
        P_JOINING_DATE   IN TEACHERS.JOINING_DATE%TYPE,
        P_DESIGNATION    IN TEACHERS.DESIGNATION%TYPE,
        P_QUALIFICATION  IN TEACHERS.QUALIFICATION%TYPE,
        P_DEPARTMENT     IN TEACHERS.DEPARTMENT%TYPE,
        P_TEACHER_ID     OUT TEACHERS.TEACHER_ID%TYPE
    );

    PROCEDURE UPDATE_TEACHER (
        P_TEACHER_ID     IN TEACHERS.TEACHER_ID%TYPE,
        P_FIRST_NAME     IN TEACHERS.FIRST_NAME%TYPE,
        P_LAST_NAME      IN TEACHERS.LAST_NAME%TYPE,
        P_EMAIL          IN TEACHERS.EMAIL%TYPE,
        P_PHONE          IN TEACHERS.PHONE%TYPE,
        P_GENDER         IN TEACHERS.GENDER%TYPE,
        P_DATE_OF_BIRTH  IN TEACHERS.DATE_OF_BIRTH%TYPE,
        P_JOINING_DATE   IN TEACHERS.JOINING_DATE%TYPE,
        P_DESIGNATION    IN TEACHERS.DESIGNATION%TYPE,
        P_QUALIFICATION  IN TEACHERS.QUALIFICATION%TYPE,
        P_DEPARTMENT     IN TEACHERS.DEPARTMENT%TYPE,
        P_STATUS         IN TEACHERS.STATUS%TYPE
    );

    PROCEDURE DELETE_TEACHER (
        P_TEACHER_ID IN TEACHERS.TEACHER_ID%TYPE
    );

    PROCEDURE GET_TEACHER_BY_ID (
        P_TEACHER_ID IN TEACHERS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_TEACHERS (
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE SEARCH_TEACHERS (
        P_SEARCH_TEXT IN VARCHAR2,
        P_RESULT      OUT SYS_REFCURSOR
    );

END TEACHER_PKG;
/

----------------------------------------------------------------
-- CREATE TEACHER_PKG BODY
----------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY TEACHER_PKG AS

    PROCEDURE ADD_TEACHER (
        P_TEACHER_CODE   IN TEACHERS.TEACHER_CODE%TYPE,
        P_FIRST_NAME     IN TEACHERS.FIRST_NAME%TYPE,
        P_LAST_NAME      IN TEACHERS.LAST_NAME%TYPE,
        P_EMAIL          IN TEACHERS.EMAIL%TYPE,
        P_PHONE          IN TEACHERS.PHONE%TYPE,
        P_GENDER         IN TEACHERS.GENDER%TYPE,
        P_DATE_OF_BIRTH  IN TEACHERS.DATE_OF_BIRTH%TYPE,
        P_JOINING_DATE   IN TEACHERS.JOINING_DATE%TYPE,
        P_DESIGNATION    IN TEACHERS.DESIGNATION%TYPE,
        P_QUALIFICATION  IN TEACHERS.QUALIFICATION%TYPE,
        P_DEPARTMENT     IN TEACHERS.DEPARTMENT%TYPE,
        P_TEACHER_ID     OUT TEACHERS.TEACHER_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO TEACHERS (
            TEACHER_CODE,
            FIRST_NAME,
            LAST_NAME,
            EMAIL,
            PHONE,
            GENDER,
            DATE_OF_BIRTH,
            JOINING_DATE,
            DESIGNATION,
            QUALIFICATION,
            DEPARTMENT,
            STATUS
        ) VALUES (
            P_TEACHER_CODE,
            P_FIRST_NAME,
            P_LAST_NAME,
            P_EMAIL,
            P_PHONE,
            UPPER(TRIM(P_GENDER)),
            P_DATE_OF_BIRTH,
            NVL(P_JOINING_DATE, SYSDATE),
            P_DESIGNATION,
            P_QUALIFICATION,
            P_DEPARTMENT,
            'ACTIVE'
        )
        RETURNING TEACHER_ID INTO P_TEACHER_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20601, 'TEACHER CODE, EMAIL, OR PHONE ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20602, 'ERROR ADDING TEACHER: ' || SQLERRM);
    END ADD_TEACHER;


    PROCEDURE UPDATE_TEACHER (
        P_TEACHER_ID     IN TEACHERS.TEACHER_ID%TYPE,
        P_FIRST_NAME     IN TEACHERS.FIRST_NAME%TYPE,
        P_LAST_NAME      IN TEACHERS.LAST_NAME%TYPE,
        P_EMAIL          IN TEACHERS.EMAIL%TYPE,
        P_PHONE          IN TEACHERS.PHONE%TYPE,
        P_GENDER         IN TEACHERS.GENDER%TYPE,
        P_DATE_OF_BIRTH  IN TEACHERS.DATE_OF_BIRTH%TYPE,
        P_JOINING_DATE   IN TEACHERS.JOINING_DATE%TYPE,
        P_DESIGNATION    IN TEACHERS.DESIGNATION%TYPE,
        P_QUALIFICATION  IN TEACHERS.QUALIFICATION%TYPE,
        P_DEPARTMENT     IN TEACHERS.DEPARTMENT%TYPE,
        P_STATUS         IN TEACHERS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE TEACHERS
        SET FIRST_NAME    = P_FIRST_NAME,
            LAST_NAME     = P_LAST_NAME,
            EMAIL         = P_EMAIL,
            PHONE         = P_PHONE,
            GENDER        = UPPER(TRIM(P_GENDER)),
            DATE_OF_BIRTH = P_DATE_OF_BIRTH,
            JOINING_DATE  = P_JOINING_DATE,
            DESIGNATION   = P_DESIGNATION,
            QUALIFICATION = P_QUALIFICATION,
            DEPARTMENT    = P_DEPARTMENT,
            STATUS        = UPPER(TRIM(P_STATUS)),
            UPDATED_AT    = SYSTIMESTAMP
        WHERE TEACHER_ID = P_TEACHER_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20603, 'TEACHER NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20604, 'TEACHER EMAIL OR PHONE ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20605, 'ERROR UPDATING TEACHER: ' || SQLERRM);
    END UPDATE_TEACHER;


    PROCEDURE DELETE_TEACHER (
        P_TEACHER_ID IN TEACHERS.TEACHER_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM TEACHER_CONTACTS
        WHERE TEACHER_ID = P_TEACHER_ID;

        DELETE FROM TEACHER_ADDRESSES
        WHERE TEACHER_ID = P_TEACHER_ID;

        DELETE FROM TEACHERS
        WHERE TEACHER_ID = P_TEACHER_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20606, 'TEACHER NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20607, 'ERROR DELETING TEACHER: ' || SQLERRM);
    END DELETE_TEACHER;


    PROCEDURE GET_TEACHER_BY_ID (
        P_TEACHER_ID IN TEACHERS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT TEACHER_ID,
                   TEACHER_CODE,
                   FIRST_NAME,
                   LAST_NAME,
                   EMAIL,
                   PHONE,
                   GENDER,
                   DATE_OF_BIRTH,
                   JOINING_DATE,
                   DESIGNATION,
                   QUALIFICATION,
                   DEPARTMENT,
                   STATUS,
                   CREATED_AT,
                   UPDATED_AT
            FROM TEACHERS
            WHERE TEACHER_ID = P_TEACHER_ID;
    END GET_TEACHER_BY_ID;


    PROCEDURE GET_ALL_TEACHERS (
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT TEACHER_ID,
                   TEACHER_CODE,
                   FIRST_NAME,
                   LAST_NAME,
                   EMAIL,
                   PHONE,
                   GENDER,
                   DATE_OF_BIRTH,
                   JOINING_DATE,
                   DESIGNATION,
                   QUALIFICATION,
                   DEPARTMENT,
                   STATUS,
                   CREATED_AT,
                   UPDATED_AT
            FROM TEACHERS
            ORDER BY TEACHER_ID DESC;
    END GET_ALL_TEACHERS;


    PROCEDURE SEARCH_TEACHERS (
        P_SEARCH_TEXT IN VARCHAR2,
        P_RESULT      OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT TEACHER_ID,
                   TEACHER_CODE,
                   FIRST_NAME,
                   LAST_NAME,
                   EMAIL,
                   PHONE,
                   GENDER,
                   DATE_OF_BIRTH,
                   JOINING_DATE,
                   DESIGNATION,
                   QUALIFICATION,
                   DEPARTMENT,
                   STATUS,
                   CREATED_AT,
                   UPDATED_AT
            FROM TEACHERS
            WHERE LOWER(TEACHER_CODE) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(FIRST_NAME) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(LAST_NAME) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(EMAIL) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(PHONE) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(DESIGNATION) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
               OR LOWER(DEPARTMENT) LIKE '%' || LOWER(P_SEARCH_TEXT) || '%'
            ORDER BY TEACHER_ID DESC;
    END SEARCH_TEACHERS;

END TEACHER_PKG;
/

---------------------------------------------------------------
-- CREATE TEACHER_ADDRESS_PKG SPECIFICATION
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE TEACHER_ADDRESS_PKG AS

    PROCEDURE ADD_ADDRESS (
        P_TEACHER_ID     IN TEACHER_ADDRESSES.TEACHER_ID%TYPE,
        P_ADDRESS_TYPE   IN TEACHER_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN TEACHER_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN TEACHER_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN TEACHER_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN TEACHER_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN TEACHER_ADDRESSES.COUNTRY%TYPE,
        P_ADDRESS_ID     OUT TEACHER_ADDRESSES.ADDRESS_ID%TYPE
    );

    PROCEDURE UPDATE_ADDRESS (
        P_ADDRESS_ID     IN TEACHER_ADDRESSES.ADDRESS_ID%TYPE,
        P_ADDRESS_TYPE   IN TEACHER_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN TEACHER_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN TEACHER_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN TEACHER_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN TEACHER_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN TEACHER_ADDRESSES.COUNTRY%TYPE
    );

    PROCEDURE DELETE_ADDRESS (
        P_ADDRESS_ID IN TEACHER_ADDRESSES.ADDRESS_ID%TYPE
    );

    PROCEDURE GET_ADDRESSES_BY_TEACHER (
        P_TEACHER_ID IN TEACHER_ADDRESSES.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

END TEACHER_ADDRESS_PKG;
/

---------------------------------------------------------------
-- CREATE TEACHER_ADDRESS_PKG BODY
---------------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY TEACHER_ADDRESS_PKG AS
    PROCEDURE ADD_ADDRESS (
        P_TEACHER_ID     IN TEACHER_ADDRESSES.TEACHER_ID%TYPE,
        P_ADDRESS_TYPE   IN TEACHER_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN TEACHER_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN TEACHER_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN TEACHER_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN TEACHER_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN TEACHER_ADDRESSES.COUNTRY%TYPE,
        P_ADDRESS_ID     OUT TEACHER_ADDRESSES.ADDRESS_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO TEACHER_ADDRESSES (
            TEACHER_ID,
            ADDRESS_TYPE,
            ADDRESS_LINE,
            CITY,
            DISTRICT,
            POSTAL_CODE,
            COUNTRY
        ) VALUES (
            P_TEACHER_ID,
            UPPER(TRIM(P_ADDRESS_TYPE)),
            P_ADDRESS_LINE,
            P_CITY,
            P_DISTRICT,
            P_POSTAL_CODE,
            NVL(P_COUNTRY, 'Bangladesh')
        )
        RETURNING ADDRESS_ID INTO P_ADDRESS_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20701,
                'TEACHER ALREADY HAS THIS ADDRESS TYPE.'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20702,
                'ERROR ADDING TEACHER ADDRESS: ' || SQLERRM
            );
    END ADD_ADDRESS;

    PROCEDURE UPDATE_ADDRESS (
        P_ADDRESS_ID     IN TEACHER_ADDRESSES.ADDRESS_ID%TYPE,
        P_ADDRESS_TYPE   IN TEACHER_ADDRESSES.ADDRESS_TYPE%TYPE,
        P_ADDRESS_LINE   IN TEACHER_ADDRESSES.ADDRESS_LINE%TYPE,
        P_CITY           IN TEACHER_ADDRESSES.CITY%TYPE,
        P_DISTRICT       IN TEACHER_ADDRESSES.DISTRICT%TYPE,
        P_POSTAL_CODE    IN TEACHER_ADDRESSES.POSTAL_CODE%TYPE,
        P_COUNTRY        IN TEACHER_ADDRESSES.COUNTRY%TYPE
    ) AS
    BEGIN
        UPDATE TEACHER_ADDRESSES
        SET ADDRESS_TYPE = UPPER(TRIM(P_ADDRESS_TYPE)),
            ADDRESS_LINE = P_ADDRESS_LINE,
            CITY         = P_CITY,
            DISTRICT     = P_DISTRICT,
            POSTAL_CODE  = P_POSTAL_CODE,
            COUNTRY      = NVL(P_COUNTRY, 'Bangladesh'),
            UPDATED_AT   = SYSTIMESTAMP
        WHERE ADDRESS_ID = P_ADDRESS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20703,
                'TEACHER ADDRESS NOT FOUND.'
            );
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20704,
                'TEACHER ALREADY HAS THIS ADDRESS TYPE.'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20705,
                'ERROR UPDATING TEACHER ADDRESS: ' || SQLERRM
            );
    END UPDATE_ADDRESS;

    PROCEDURE DELETE_ADDRESS (
        P_ADDRESS_ID IN TEACHER_ADDRESSES.ADDRESS_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM TEACHER_ADDRESSES
        WHERE ADDRESS_ID = P_ADDRESS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20706,
                'TEACHER ADDRESS NOT FOUND.'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20707,
                'ERROR DELETING TEACHER ADDRESS: ' || SQLERRM
            );
    END DELETE_ADDRESS;

    PROCEDURE GET_ADDRESSES_BY_TEACHER (
        P_TEACHER_ID IN TEACHER_ADDRESSES.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                ADDRESS_ID,
                TEACHER_ID,
                ADDRESS_TYPE,
                ADDRESS_LINE,
                CITY,
                DISTRICT,
                POSTAL_CODE,
                COUNTRY,
                CREATED_AT,
                UPDATED_AT
            FROM TEACHER_ADDRESSES
            WHERE TEACHER_ID = P_TEACHER_ID
            ORDER BY ADDRESS_ID;
    END GET_ADDRESSES_BY_TEACHER;

END TEACHER_ADDRESS_PKG;
/

---------------------------------------------------------------
-- CREATE TEACHER_CONTACT_PKG SPECIFICATION
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE TEACHER_CONTACT_PKG AS

    PROCEDURE ADD_CONTACT (
        P_TEACHER_ID     IN TEACHER_CONTACTS.TEACHER_ID%TYPE,
        P_CONTACT_NAME   IN TEACHER_CONTACTS.CONTACT_NAME%TYPE,
        P_RELATIONSHIP   IN TEACHER_CONTACTS.RELATIONSHIP%TYPE,
        P_PHONE          IN TEACHER_CONTACTS.PHONE%TYPE,
        P_EMAIL          IN TEACHER_CONTACTS.EMAIL%TYPE,
        P_IS_PRIMARY     IN TEACHER_CONTACTS.IS_PRIMARY%TYPE,
        P_CONTACT_ID     OUT TEACHER_CONTACTS.CONTACT_ID%TYPE
    );

    PROCEDURE UPDATE_CONTACT (
        P_CONTACT_ID     IN TEACHER_CONTACTS.CONTACT_ID%TYPE,
        P_CONTACT_NAME   IN TEACHER_CONTACTS.CONTACT_NAME%TYPE,
        P_RELATIONSHIP   IN TEACHER_CONTACTS.RELATIONSHIP%TYPE,
        P_PHONE          IN TEACHER_CONTACTS.PHONE%TYPE,
        P_EMAIL          IN TEACHER_CONTACTS.EMAIL%TYPE,
        P_IS_PRIMARY     IN TEACHER_CONTACTS.IS_PRIMARY%TYPE
    );

    PROCEDURE DELETE_CONTACT (
        P_CONTACT_ID IN TEACHER_CONTACTS.CONTACT_ID%TYPE
    );

    PROCEDURE GET_CONTACTS_BY_TEACHER (
        P_TEACHER_ID IN TEACHER_CONTACTS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    );

END TEACHER_CONTACT_PKG;
/

---------------------------------------------------------------
-- CREATE TEACHER_CONTACT_PKG BODY
---------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY TEACHER_CONTACT_PKG AS

    PROCEDURE ADD_CONTACT (
        P_TEACHER_ID     IN TEACHER_CONTACTS.TEACHER_ID%TYPE,
        P_CONTACT_NAME   IN TEACHER_CONTACTS.CONTACT_NAME%TYPE,
        P_RELATIONSHIP   IN TEACHER_CONTACTS.RELATIONSHIP%TYPE,
        P_PHONE          IN TEACHER_CONTACTS.PHONE%TYPE,
        P_EMAIL          IN TEACHER_CONTACTS.EMAIL%TYPE,
        P_IS_PRIMARY     IN TEACHER_CONTACTS.IS_PRIMARY%TYPE,
        P_CONTACT_ID     OUT TEACHER_CONTACTS.CONTACT_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO TEACHER_CONTACTS (
            TEACHER_ID,
            CONTACT_NAME,
            RELATIONSHIP,
            PHONE,
            EMAIL,
            IS_PRIMARY
        ) VALUES (
            P_TEACHER_ID,
            P_CONTACT_NAME,
            P_RELATIONSHIP,
            P_PHONE,
            P_EMAIL,
            NVL(UPPER(TRIM(P_IS_PRIMARY)), 'N')
        )
        RETURNING CONTACT_ID INTO P_CONTACT_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20806,
                'TEACHER ALREADY HAS A PRIMARY CONTACT.'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20801,
                'ERROR ADDING TEACHER CONTACT: ' || SQLERRM
            );
    END ADD_CONTACT;

    PROCEDURE UPDATE_CONTACT (
        P_CONTACT_ID     IN TEACHER_CONTACTS.CONTACT_ID%TYPE,
        P_CONTACT_NAME   IN TEACHER_CONTACTS.CONTACT_NAME%TYPE,
        P_RELATIONSHIP   IN TEACHER_CONTACTS.RELATIONSHIP%TYPE,
        P_PHONE          IN TEACHER_CONTACTS.PHONE%TYPE,
        P_EMAIL          IN TEACHER_CONTACTS.EMAIL%TYPE,
        P_IS_PRIMARY     IN TEACHER_CONTACTS.IS_PRIMARY%TYPE
    ) AS
    BEGIN
        UPDATE TEACHER_CONTACTS
        SET CONTACT_NAME = P_CONTACT_NAME,
            RELATIONSHIP = P_RELATIONSHIP,
            PHONE        = P_PHONE,
            EMAIL        = P_EMAIL,
            IS_PRIMARY   = NVL(UPPER(TRIM(P_IS_PRIMARY)), 'N'),
            UPDATED_AT   = SYSTIMESTAMP
        WHERE CONTACT_ID = P_CONTACT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20802,
                'TEACHER CONTACT NOT FOUND.'
            );
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(
                -20807,
                'TEACHER ALREADY HAS A PRIMARY CONTACT.'
            );

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20803,
                'ERROR UPDATING TEACHER CONTACT: ' || SQLERRM
            );
    END UPDATE_CONTACT;

    PROCEDURE DELETE_CONTACT (
        P_CONTACT_ID IN TEACHER_CONTACTS.CONTACT_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM TEACHER_CONTACTS
        WHERE CONTACT_ID = P_CONTACT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20804,
                'TEACHER CONTACT NOT FOUND.'
            );
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(
                -20805,
                'ERROR DELETING TEACHER CONTACT: ' || SQLERRM
            );
    END DELETE_CONTACT;

    PROCEDURE GET_CONTACTS_BY_TEACHER (
        P_TEACHER_ID IN TEACHER_CONTACTS.TEACHER_ID%TYPE,
        P_RESULT     OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                CONTACT_ID,
                TEACHER_ID,
                CONTACT_NAME,
                RELATIONSHIP,
                PHONE,
                EMAIL,
                IS_PRIMARY,
                CREATED_AT,
                UPDATED_AT
            FROM TEACHER_CONTACTS
            WHERE TEACHER_ID = P_TEACHER_ID
            ORDER BY
                CASE
                    WHEN IS_PRIMARY = 'Y' THEN 0
                    ELSE 1
                END,
                CONTACT_ID;
    END GET_CONTACTS_BY_TEACHER;

END TEACHER_CONTACT_PKG;
/
