------------------------------------------------------------
-- CREATE ACSS_MGT_PKG BODY
------------------------------------------------------------
CREATE OR REPLACE PACKAGE ACSS_MGT_PKG AS

    -- ACADEMIC YEARS
    PROCEDURE ADD_ACADEMIC_YEAR(
        P_YEAR_NAME        IN ACADEMIC_YEARS.YEAR_NAME%TYPE,
        P_START_DATE       IN ACADEMIC_YEARS.START_DATE%TYPE,
        P_END_DATE         IN ACADEMIC_YEARS.END_DATE%TYPE,
        P_IS_CURRENT       IN ACADEMIC_YEARS.IS_CURRENT%TYPE,
        P_STATUS           IN ACADEMIC_YEARS.STATUS%TYPE,
        P_ACADEMIC_YEAR_ID OUT ACADEMIC_YEARS.ACADEMIC_YEAR_ID%TYPE
    );

    PROCEDURE UPDATE_ACADEMIC_YEAR(
        P_ACADEMIC_YEAR_ID IN ACADEMIC_YEARS.ACADEMIC_YEAR_ID%TYPE,
        P_YEAR_NAME        IN ACADEMIC_YEARS.YEAR_NAME%TYPE,
        P_START_DATE       IN ACADEMIC_YEARS.START_DATE%TYPE,
        P_END_DATE         IN ACADEMIC_YEARS.END_DATE%TYPE,
        P_IS_CURRENT       IN ACADEMIC_YEARS.IS_CURRENT%TYPE,
        P_STATUS           IN ACADEMIC_YEARS.STATUS%TYPE
    );

    PROCEDURE GET_ACADEMIC_YEAR_BY_ID(
        P_ACADEMIC_YEAR_ID IN ACADEMIC_YEARS.ACADEMIC_YEAR_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_ACADEMIC_YEARS(P_RESULT OUT SYS_REFCURSOR);

    PROCEDURE DELETE_ACADEMIC_YEAR(
        P_ACADEMIC_YEAR_ID IN ACADEMIC_YEARS.ACADEMIC_YEAR_ID%TYPE
    );


    -- CLASSES
    PROCEDURE ADD_CLASS(
        P_CLASS_NAME    IN CLASSES.CLASS_NAME%TYPE,
        P_CLASS_CODE    IN CLASSES.CLASS_CODE%TYPE,
        P_DISPLAY_ORDER IN CLASSES.DISPLAY_ORDER%TYPE,
        P_STATUS        IN CLASSES.STATUS%TYPE,
        P_CLASS_ID      OUT CLASSES.CLASS_ID%TYPE
    );

    PROCEDURE UPDATE_CLASS(
        P_CLASS_ID      IN CLASSES.CLASS_ID%TYPE,
        P_CLASS_NAME    IN CLASSES.CLASS_NAME%TYPE,
        P_CLASS_CODE    IN CLASSES.CLASS_CODE%TYPE,
        P_DISPLAY_ORDER IN CLASSES.DISPLAY_ORDER%TYPE,
        P_STATUS        IN CLASSES.STATUS%TYPE
    );

    PROCEDURE GET_CLASS_BY_ID(
        P_CLASS_ID IN CLASSES.CLASS_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_CLASSES(P_RESULT OUT SYS_REFCURSOR);

    PROCEDURE DELETE_CLASS(
        P_CLASS_ID IN CLASSES.CLASS_ID%TYPE
    );


    -- ACADEMIC YEAR CLASSES
    PROCEDURE ADD_ACADEMIC_YEAR_CLASS(
        P_ACADEMIC_YEAR_ID       IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_ID%TYPE,
        P_CLASS_ID               IN ACADEMIC_YEAR_CLASSES.CLASS_ID%TYPE,
        P_STATUS                 IN ACADEMIC_YEAR_CLASSES.STATUS%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID OUT ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_CLASS_ID%TYPE
    );

    PROCEDURE UPDATE_ACADEMIC_YEAR_CLASS(
        P_ACADEMIC_YEAR_CLASS_ID IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_ACADEMIC_YEAR_ID       IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_ID%TYPE,
        P_CLASS_ID               IN ACADEMIC_YEAR_CLASSES.CLASS_ID%TYPE,
        P_STATUS                 IN ACADEMIC_YEAR_CLASSES.STATUS%TYPE
    );

    PROCEDURE GET_ACADEMIC_YEAR_CLASS_BY_ID(
        P_ACADEMIC_YEAR_CLASS_ID IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_CLASSES_BY_ACADEMIC_YEAR(
        P_ACADEMIC_YEAR_ID IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_ACADEMIC_YEAR_CLASSES(P_RESULT OUT SYS_REFCURSOR);

    PROCEDURE DELETE_ACADEMIC_YEAR_CLASS(
        P_ACADEMIC_YEAR_CLASS_ID IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_CLASS_ID%TYPE
    );


    -- SECTIONS
    PROCEDURE ADD_SECTION(
        P_ACADEMIC_YEAR_CLASS_ID IN SECTIONS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SECTION_NAME           IN SECTIONS.SECTION_NAME%TYPE,
        P_SECTION_CODE           IN SECTIONS.SECTION_CODE%TYPE,
        P_CAPACITY               IN SECTIONS.CAPACITY%TYPE,
        P_DISPLAY_ORDER          IN SECTIONS.DISPLAY_ORDER%TYPE,
        P_STATUS                 IN SECTIONS.STATUS%TYPE,
        P_SECTION_ID             OUT SECTIONS.SECTION_ID%TYPE
    );

    PROCEDURE UPDATE_SECTION(
        P_SECTION_ID             IN SECTIONS.SECTION_ID%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID IN SECTIONS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SECTION_NAME           IN SECTIONS.SECTION_NAME%TYPE,
        P_SECTION_CODE           IN SECTIONS.SECTION_CODE%TYPE,
        P_CAPACITY               IN SECTIONS.CAPACITY%TYPE,
        P_DISPLAY_ORDER          IN SECTIONS.DISPLAY_ORDER%TYPE,
        P_STATUS                 IN SECTIONS.STATUS%TYPE
    );

    PROCEDURE GET_SECTION_BY_ID(
        P_SECTION_ID IN SECTIONS.SECTION_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_SECTIONS_BY_ACADEMIC_YEAR_CLASS(
        P_ACADEMIC_YEAR_CLASS_ID IN SECTIONS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_SECTIONS(P_RESULT OUT SYS_REFCURSOR);

    PROCEDURE DELETE_SECTION(
        P_SECTION_ID IN SECTIONS.SECTION_ID%TYPE
    );


    -- SHIFTS
    PROCEDURE ADD_SHIFT(
        P_SHIFT_NAME    IN SHIFTS.SHIFT_NAME%TYPE,
        P_SHIFT_CODE    IN SHIFTS.SHIFT_CODE%TYPE,
        P_START_TIME    IN SHIFTS.START_TIME%TYPE,
        P_END_TIME      IN SHIFTS.END_TIME%TYPE,
        P_DISPLAY_ORDER IN SHIFTS.DISPLAY_ORDER%TYPE,
        P_STATUS        IN SHIFTS.STATUS%TYPE,
        P_SHIFT_ID      OUT SHIFTS.SHIFT_ID%TYPE
    );

    PROCEDURE UPDATE_SHIFT(
        P_SHIFT_ID      IN SHIFTS.SHIFT_ID%TYPE,
        P_SHIFT_NAME    IN SHIFTS.SHIFT_NAME%TYPE,
        P_SHIFT_CODE    IN SHIFTS.SHIFT_CODE%TYPE,
        P_START_TIME    IN SHIFTS.START_TIME%TYPE,
        P_END_TIME      IN SHIFTS.END_TIME%TYPE,
        P_DISPLAY_ORDER IN SHIFTS.DISPLAY_ORDER%TYPE,
        P_STATUS        IN SHIFTS.STATUS%TYPE
    );

    PROCEDURE GET_SHIFT_BY_ID(
        P_SHIFT_ID IN SHIFTS.SHIFT_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_SHIFTS(P_RESULT OUT SYS_REFCURSOR);

    PROCEDURE DELETE_SHIFT(
        P_SHIFT_ID IN SHIFTS.SHIFT_ID%TYPE
    );


    -- SECTION SHIFTS
    PROCEDURE ADD_SECTION_SHIFT(
        P_SECTION_ID       IN SECTION_SHIFTS.SECTION_ID%TYPE,
        P_SHIFT_ID         IN SECTION_SHIFTS.SHIFT_ID%TYPE,
        P_STATUS           IN SECTION_SHIFTS.STATUS%TYPE,
        P_SECTION_SHIFT_ID OUT SECTION_SHIFTS.SECTION_SHIFT_ID%TYPE
    );

    PROCEDURE UPDATE_SECTION_SHIFT(
        P_SECTION_SHIFT_ID IN SECTION_SHIFTS.SECTION_SHIFT_ID%TYPE,
        P_SECTION_ID       IN SECTION_SHIFTS.SECTION_ID%TYPE,
        P_SHIFT_ID         IN SECTION_SHIFTS.SHIFT_ID%TYPE,
        P_STATUS           IN SECTION_SHIFTS.STATUS%TYPE
    );

    PROCEDURE GET_SECTION_SHIFT_BY_ID(
        P_SECTION_SHIFT_ID IN SECTION_SHIFTS.SECTION_SHIFT_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_SHIFTS_BY_SECTION(
        P_SECTION_ID IN SECTION_SHIFTS.SECTION_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    );

    PROCEDURE GET_ALL_SECTION_SHIFTS(P_RESULT OUT SYS_REFCURSOR);

    PROCEDURE DELETE_SECTION_SHIFT(
        P_SECTION_SHIFT_ID IN SECTION_SHIFTS.SECTION_SHIFT_ID%TYPE
    );

END ACSS_MGT_PKG;
/

------------------------------------------------------------
-- CREATE ACSS_MGT_PKG SPECIFICATION
------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY ACSS_MGT_PKG AS

    -- =====================================================
    -- ACADEMIC YEARS
    -- =====================================================

    PROCEDURE ADD_ACADEMIC_YEAR(
        P_YEAR_NAME        IN ACADEMIC_YEARS.YEAR_NAME%TYPE,
        P_START_DATE       IN ACADEMIC_YEARS.START_DATE%TYPE,
        P_END_DATE         IN ACADEMIC_YEARS.END_DATE%TYPE,
        P_IS_CURRENT       IN ACADEMIC_YEARS.IS_CURRENT%TYPE,
        P_STATUS           IN ACADEMIC_YEARS.STATUS%TYPE,
        P_ACADEMIC_YEAR_ID OUT ACADEMIC_YEARS.ACADEMIC_YEAR_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO ACADEMIC_YEARS (
            YEAR_NAME, START_DATE, END_DATE, IS_CURRENT, STATUS
        ) VALUES (
            P_YEAR_NAME, P_START_DATE, P_END_DATE, P_IS_CURRENT, P_STATUS
        )
        RETURNING ACADEMIC_YEAR_ID INTO P_ACADEMIC_YEAR_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20001, 'ACADEMIC YEAR ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR CREATING ACADEMIC YEAR: ' || SQLERRM);
    END ADD_ACADEMIC_YEAR;


    PROCEDURE UPDATE_ACADEMIC_YEAR(
        P_ACADEMIC_YEAR_ID IN ACADEMIC_YEARS.ACADEMIC_YEAR_ID%TYPE,
        P_YEAR_NAME        IN ACADEMIC_YEARS.YEAR_NAME%TYPE,
        P_START_DATE       IN ACADEMIC_YEARS.START_DATE%TYPE,
        P_END_DATE         IN ACADEMIC_YEARS.END_DATE%TYPE,
        P_IS_CURRENT       IN ACADEMIC_YEARS.IS_CURRENT%TYPE,
        P_STATUS           IN ACADEMIC_YEARS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE ACADEMIC_YEARS
        SET YEAR_NAME  = P_YEAR_NAME,
            START_DATE = P_START_DATE,
            END_DATE   = P_END_DATE,
            IS_CURRENT = P_IS_CURRENT,
            STATUS     = P_STATUS,
            UPDATED_AT = SYSTIMESTAMP
        WHERE ACADEMIC_YEAR_ID = P_ACADEMIC_YEAR_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20003, 'ACADEMIC YEAR NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20001, 'ACADEMIC YEAR ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20004, 'ERROR UPDATING ACADEMIC YEAR: ' || SQLERRM);
    END UPDATE_ACADEMIC_YEAR;


    PROCEDURE GET_ACADEMIC_YEAR_BY_ID(
        P_ACADEMIC_YEAR_ID IN ACADEMIC_YEARS.ACADEMIC_YEAR_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT *
            FROM ACADEMIC_YEARS
            WHERE ACADEMIC_YEAR_ID = P_ACADEMIC_YEAR_ID;
    END GET_ACADEMIC_YEAR_BY_ID;


    PROCEDURE GET_ALL_ACADEMIC_YEARS(P_RESULT OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT *
            FROM ACADEMIC_YEARS
            ORDER BY START_DATE DESC;
    END GET_ALL_ACADEMIC_YEARS;


    PROCEDURE DELETE_ACADEMIC_YEAR(
        P_ACADEMIC_YEAR_ID IN ACADEMIC_YEARS.ACADEMIC_YEAR_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM ACADEMIC_YEARS
        WHERE ACADEMIC_YEAR_ID = P_ACADEMIC_YEAR_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20003, 'ACADEMIC YEAR NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20005, 'ERROR DELETING ACADEMIC YEAR: ' || SQLERRM);
    END DELETE_ACADEMIC_YEAR;


    -- =====================================================
    -- CLASSES
    -- =====================================================

    PROCEDURE ADD_CLASS(
        P_CLASS_NAME    IN CLASSES.CLASS_NAME%TYPE,
        P_CLASS_CODE    IN CLASSES.CLASS_CODE%TYPE,
        P_DISPLAY_ORDER IN CLASSES.DISPLAY_ORDER%TYPE,
        P_STATUS        IN CLASSES.STATUS%TYPE,
        P_CLASS_ID      OUT CLASSES.CLASS_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO CLASSES (
            CLASS_NAME, CLASS_CODE, DISPLAY_ORDER, STATUS
        ) VALUES (
            P_CLASS_NAME, P_CLASS_CODE, P_DISPLAY_ORDER, P_STATUS
        )
        RETURNING CLASS_ID INTO P_CLASS_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20101, 'CLASS ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20102, 'ERROR CREATING CLASS: ' || SQLERRM);
    END ADD_CLASS;


    PROCEDURE UPDATE_CLASS(
        P_CLASS_ID      IN CLASSES.CLASS_ID%TYPE,
        P_CLASS_NAME    IN CLASSES.CLASS_NAME%TYPE,
        P_CLASS_CODE    IN CLASSES.CLASS_CODE%TYPE,
        P_DISPLAY_ORDER IN CLASSES.DISPLAY_ORDER%TYPE,
        P_STATUS        IN CLASSES.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE CLASSES
        SET CLASS_NAME    = P_CLASS_NAME,
            CLASS_CODE    = P_CLASS_CODE,
            DISPLAY_ORDER = P_DISPLAY_ORDER,
            STATUS        = P_STATUS,
            UPDATED_AT    = SYSTIMESTAMP
        WHERE CLASS_ID = P_CLASS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20103, 'CLASS NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20101, 'CLASS ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20104, 'ERROR UPDATING CLASS: ' || SQLERRM);
    END UPDATE_CLASS;


    PROCEDURE GET_CLASS_BY_ID(
        P_CLASS_ID IN CLASSES.CLASS_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT *
            FROM CLASSES
            WHERE CLASS_ID = P_CLASS_ID;
    END GET_CLASS_BY_ID;


    PROCEDURE GET_ALL_CLASSES(P_RESULT OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT *
            FROM CLASSES
            ORDER BY DISPLAY_ORDER;
    END GET_ALL_CLASSES;


    PROCEDURE DELETE_CLASS(
        P_CLASS_ID IN CLASSES.CLASS_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM CLASSES
        WHERE CLASS_ID = P_CLASS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20103, 'CLASS NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20105, 'ERROR DELETING CLASS: ' || SQLERRM);
    END DELETE_CLASS;


    -- =====================================================
    -- ACADEMIC YEAR CLASSES
    -- =====================================================

    PROCEDURE ADD_ACADEMIC_YEAR_CLASS(
        P_ACADEMIC_YEAR_ID       IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_ID%TYPE,
        P_CLASS_ID               IN ACADEMIC_YEAR_CLASSES.CLASS_ID%TYPE,
        P_STATUS                 IN ACADEMIC_YEAR_CLASSES.STATUS%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID OUT ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_CLASS_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO ACADEMIC_YEAR_CLASSES (
            ACADEMIC_YEAR_ID, CLASS_ID, STATUS
        ) VALUES (
            P_ACADEMIC_YEAR_ID, P_CLASS_ID, P_STATUS
        )
        RETURNING ACADEMIC_YEAR_CLASS_ID INTO P_ACADEMIC_YEAR_CLASS_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20201, 'CLASS ALREADY OPENED FOR THIS ACADEMIC YEAR.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20202, 'ERROR CREATING ACADEMIC YEAR CLASS: ' || SQLERRM);
    END ADD_ACADEMIC_YEAR_CLASS;


    PROCEDURE UPDATE_ACADEMIC_YEAR_CLASS(
        P_ACADEMIC_YEAR_CLASS_ID IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_ACADEMIC_YEAR_ID       IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_ID%TYPE,
        P_CLASS_ID               IN ACADEMIC_YEAR_CLASSES.CLASS_ID%TYPE,
        P_STATUS                 IN ACADEMIC_YEAR_CLASSES.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE ACADEMIC_YEAR_CLASSES
        SET ACADEMIC_YEAR_ID = P_ACADEMIC_YEAR_ID,
            CLASS_ID         = P_CLASS_ID,
            STATUS           = P_STATUS,
            UPDATED_AT       = SYSTIMESTAMP
        WHERE ACADEMIC_YEAR_CLASS_ID = P_ACADEMIC_YEAR_CLASS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20203, 'ACADEMIC YEAR CLASS NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20201, 'CLASS ALREADY OPENED FOR THIS ACADEMIC YEAR.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20204, 'ERROR UPDATING ACADEMIC YEAR CLASS: ' || SQLERRM);
    END UPDATE_ACADEMIC_YEAR_CLASS;


    PROCEDURE GET_ACADEMIC_YEAR_CLASS_BY_ID(
        P_ACADEMIC_YEAR_CLASS_ID IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                AYC.ACADEMIC_YEAR_CLASS_ID,
                AYC.ACADEMIC_YEAR_ID,
                AY.YEAR_NAME,
                AYC.CLASS_ID,
                C.CLASS_NAME,
                C.CLASS_CODE,
                C.DISPLAY_ORDER AS CLASS_DISPLAY_ORDER,
                AYC.STATUS,
                AYC.CREATED_AT,
                AYC.UPDATED_AT
            FROM ACADEMIC_YEAR_CLASSES AYC
            JOIN ACADEMIC_YEARS AY ON AY.ACADEMIC_YEAR_ID = AYC.ACADEMIC_YEAR_ID
            JOIN CLASSES C ON C.CLASS_ID = AYC.CLASS_ID
            WHERE AYC.ACADEMIC_YEAR_CLASS_ID = P_ACADEMIC_YEAR_CLASS_ID;
    END GET_ACADEMIC_YEAR_CLASS_BY_ID;


    PROCEDURE GET_CLASSES_BY_ACADEMIC_YEAR(
        P_ACADEMIC_YEAR_ID IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                AYC.ACADEMIC_YEAR_CLASS_ID,
                AYC.ACADEMIC_YEAR_ID,
                AY.YEAR_NAME,
                AYC.CLASS_ID,
                C.CLASS_NAME,
                C.CLASS_CODE,
                C.DISPLAY_ORDER AS CLASS_DISPLAY_ORDER,
                AYC.STATUS,
                AYC.CREATED_AT,
                AYC.UPDATED_AT
            FROM ACADEMIC_YEAR_CLASSES AYC
            JOIN ACADEMIC_YEARS AY ON AY.ACADEMIC_YEAR_ID = AYC.ACADEMIC_YEAR_ID
            JOIN CLASSES C ON C.CLASS_ID = AYC.CLASS_ID
            WHERE AYC.ACADEMIC_YEAR_ID = P_ACADEMIC_YEAR_ID
            ORDER BY C.DISPLAY_ORDER;
    END GET_CLASSES_BY_ACADEMIC_YEAR;


    PROCEDURE GET_ALL_ACADEMIC_YEAR_CLASSES(P_RESULT OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                AYC.ACADEMIC_YEAR_CLASS_ID,
                AYC.ACADEMIC_YEAR_ID,
                AY.YEAR_NAME,
                AYC.CLASS_ID,
                C.CLASS_NAME,
                C.CLASS_CODE,
                C.DISPLAY_ORDER AS CLASS_DISPLAY_ORDER,
                AYC.STATUS,
                AYC.CREATED_AT,
                AYC.UPDATED_AT
            FROM ACADEMIC_YEAR_CLASSES AYC
            JOIN ACADEMIC_YEARS AY ON AY.ACADEMIC_YEAR_ID = AYC.ACADEMIC_YEAR_ID
            JOIN CLASSES C ON C.CLASS_ID = AYC.CLASS_ID
            ORDER BY AY.START_DATE DESC, C.DISPLAY_ORDER;
    END GET_ALL_ACADEMIC_YEAR_CLASSES;


    PROCEDURE DELETE_ACADEMIC_YEAR_CLASS(
        P_ACADEMIC_YEAR_CLASS_ID IN ACADEMIC_YEAR_CLASSES.ACADEMIC_YEAR_CLASS_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM ACADEMIC_YEAR_CLASSES
        WHERE ACADEMIC_YEAR_CLASS_ID = P_ACADEMIC_YEAR_CLASS_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20203, 'ACADEMIC YEAR CLASS NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20205, 'ERROR DELETING ACADEMIC YEAR CLASS: ' || SQLERRM);
    END DELETE_ACADEMIC_YEAR_CLASS;


    -- =====================================================
    -- SECTIONS
    -- =====================================================

    PROCEDURE ADD_SECTION(
        P_ACADEMIC_YEAR_CLASS_ID IN SECTIONS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SECTION_NAME           IN SECTIONS.SECTION_NAME%TYPE,
        P_SECTION_CODE           IN SECTIONS.SECTION_CODE%TYPE,
        P_CAPACITY               IN SECTIONS.CAPACITY%TYPE,
        P_DISPLAY_ORDER          IN SECTIONS.DISPLAY_ORDER%TYPE,
        P_STATUS                 IN SECTIONS.STATUS%TYPE,
        P_SECTION_ID             OUT SECTIONS.SECTION_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO SECTIONS (
            ACADEMIC_YEAR_CLASS_ID,
            SECTION_NAME,
            SECTION_CODE,
            CAPACITY,
            DISPLAY_ORDER,
            STATUS
        ) VALUES (
            P_ACADEMIC_YEAR_CLASS_ID,
            P_SECTION_NAME,
            P_SECTION_CODE,
            P_CAPACITY,
            P_DISPLAY_ORDER,
            P_STATUS
        )
        RETURNING SECTION_ID INTO P_SECTION_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20301, 'SECTION ALREADY EXISTS FOR THIS CLASS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20302, 'ERROR CREATING SECTION: ' || SQLERRM);
    END ADD_SECTION;


    PROCEDURE UPDATE_SECTION(
        P_SECTION_ID             IN SECTIONS.SECTION_ID%TYPE,
        P_ACADEMIC_YEAR_CLASS_ID IN SECTIONS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_SECTION_NAME           IN SECTIONS.SECTION_NAME%TYPE,
        P_SECTION_CODE           IN SECTIONS.SECTION_CODE%TYPE,
        P_CAPACITY               IN SECTIONS.CAPACITY%TYPE,
        P_DISPLAY_ORDER          IN SECTIONS.DISPLAY_ORDER%TYPE,
        P_STATUS                 IN SECTIONS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE SECTIONS
        SET ACADEMIC_YEAR_CLASS_ID = P_ACADEMIC_YEAR_CLASS_ID,
            SECTION_NAME           = P_SECTION_NAME,
            SECTION_CODE           = P_SECTION_CODE,
            CAPACITY               = P_CAPACITY,
            DISPLAY_ORDER          = P_DISPLAY_ORDER,
            STATUS                 = P_STATUS,
            UPDATED_AT             = SYSTIMESTAMP
        WHERE SECTION_ID = P_SECTION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20303, 'SECTION NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20301, 'SECTION ALREADY EXISTS FOR THIS CLASS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20304, 'ERROR UPDATING SECTION: ' || SQLERRM);
    END UPDATE_SECTION;


    PROCEDURE GET_SECTION_BY_ID(
        P_SECTION_ID IN SECTIONS.SECTION_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SEC.SECTION_ID,
                SEC.ACADEMIC_YEAR_CLASS_ID,
                AYC.ACADEMIC_YEAR_ID,
                AY.YEAR_NAME,
                AYC.CLASS_ID,
                C.CLASS_NAME,
                C.CLASS_CODE,
                SEC.SECTION_NAME,
                SEC.SECTION_CODE,
                SEC.CAPACITY,
                SEC.DISPLAY_ORDER,
                SEC.STATUS,
                SEC.CREATED_AT,
                SEC.UPDATED_AT
            FROM SECTIONS SEC
            JOIN ACADEMIC_YEAR_CLASSES AYC ON AYC.ACADEMIC_YEAR_CLASS_ID = SEC.ACADEMIC_YEAR_CLASS_ID
            JOIN ACADEMIC_YEARS AY ON AY.ACADEMIC_YEAR_ID = AYC.ACADEMIC_YEAR_ID
            JOIN CLASSES C ON C.CLASS_ID = AYC.CLASS_ID
            WHERE SEC.SECTION_ID = P_SECTION_ID;
    END GET_SECTION_BY_ID;


    PROCEDURE GET_SECTIONS_BY_ACADEMIC_YEAR_CLASS(
        P_ACADEMIC_YEAR_CLASS_ID IN SECTIONS.ACADEMIC_YEAR_CLASS_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT *
            FROM SECTIONS
            WHERE ACADEMIC_YEAR_CLASS_ID = P_ACADEMIC_YEAR_CLASS_ID
            ORDER BY DISPLAY_ORDER;
    END GET_SECTIONS_BY_ACADEMIC_YEAR_CLASS;


    PROCEDURE GET_ALL_SECTIONS(P_RESULT OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SEC.SECTION_ID,
                SEC.ACADEMIC_YEAR_CLASS_ID,
                AYC.ACADEMIC_YEAR_ID,
                AY.YEAR_NAME,
                AYC.CLASS_ID,
                C.CLASS_NAME,
                C.CLASS_CODE,
                SEC.SECTION_NAME,
                SEC.SECTION_CODE,
                SEC.CAPACITY,
                SEC.DISPLAY_ORDER,
                SEC.STATUS,
                SEC.CREATED_AT,
                SEC.UPDATED_AT
            FROM SECTIONS SEC
            JOIN ACADEMIC_YEAR_CLASSES AYC ON AYC.ACADEMIC_YEAR_CLASS_ID = SEC.ACADEMIC_YEAR_CLASS_ID
            JOIN ACADEMIC_YEARS AY ON AY.ACADEMIC_YEAR_ID = AYC.ACADEMIC_YEAR_ID
            JOIN CLASSES C ON C.CLASS_ID = AYC.CLASS_ID
            ORDER BY AY.START_DATE DESC, C.DISPLAY_ORDER, SEC.DISPLAY_ORDER;
    END GET_ALL_SECTIONS;


    PROCEDURE DELETE_SECTION(
        P_SECTION_ID IN SECTIONS.SECTION_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM SECTIONS
        WHERE SECTION_ID = P_SECTION_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20303, 'SECTION NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20305, 'ERROR DELETING SECTION: ' || SQLERRM);
    END DELETE_SECTION;


    -- =====================================================
    -- SHIFTS
    -- =====================================================

    PROCEDURE ADD_SHIFT(
        P_SHIFT_NAME    IN SHIFTS.SHIFT_NAME%TYPE,
        P_SHIFT_CODE    IN SHIFTS.SHIFT_CODE%TYPE,
        P_START_TIME    IN SHIFTS.START_TIME%TYPE,
        P_END_TIME      IN SHIFTS.END_TIME%TYPE,
        P_DISPLAY_ORDER IN SHIFTS.DISPLAY_ORDER%TYPE,
        P_STATUS        IN SHIFTS.STATUS%TYPE,
        P_SHIFT_ID      OUT SHIFTS.SHIFT_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO SHIFTS (
            SHIFT_NAME, SHIFT_CODE, START_TIME, END_TIME, DISPLAY_ORDER, STATUS
        ) VALUES (
            P_SHIFT_NAME, P_SHIFT_CODE, P_START_TIME, P_END_TIME, P_DISPLAY_ORDER, P_STATUS
        )
        RETURNING SHIFT_ID INTO P_SHIFT_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20401, 'SHIFT ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20402, 'ERROR CREATING SHIFT: ' || SQLERRM);
    END ADD_SHIFT;


    PROCEDURE UPDATE_SHIFT(
        P_SHIFT_ID      IN SHIFTS.SHIFT_ID%TYPE,
        P_SHIFT_NAME    IN SHIFTS.SHIFT_NAME%TYPE,
        P_SHIFT_CODE    IN SHIFTS.SHIFT_CODE%TYPE,
        P_START_TIME    IN SHIFTS.START_TIME%TYPE,
        P_END_TIME      IN SHIFTS.END_TIME%TYPE,
        P_DISPLAY_ORDER IN SHIFTS.DISPLAY_ORDER%TYPE,
        P_STATUS        IN SHIFTS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE SHIFTS
        SET SHIFT_NAME    = P_SHIFT_NAME,
            SHIFT_CODE    = P_SHIFT_CODE,
            START_TIME    = P_START_TIME,
            END_TIME      = P_END_TIME,
            DISPLAY_ORDER = P_DISPLAY_ORDER,
            STATUS        = P_STATUS,
            UPDATED_AT    = SYSTIMESTAMP
        WHERE SHIFT_ID = P_SHIFT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20403, 'SHIFT NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20401, 'SHIFT ALREADY EXISTS.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20404, 'ERROR UPDATING SHIFT: ' || SQLERRM);
    END UPDATE_SHIFT;


    PROCEDURE GET_SHIFT_BY_ID(
        P_SHIFT_ID IN SHIFTS.SHIFT_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT *
            FROM SHIFTS
            WHERE SHIFT_ID = P_SHIFT_ID;
    END GET_SHIFT_BY_ID;


    PROCEDURE GET_ALL_SHIFTS(P_RESULT OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT *
            FROM SHIFTS
            ORDER BY DISPLAY_ORDER;
    END GET_ALL_SHIFTS;


    PROCEDURE DELETE_SHIFT(
        P_SHIFT_ID IN SHIFTS.SHIFT_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM SHIFTS
        WHERE SHIFT_ID = P_SHIFT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20403, 'SHIFT NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20405, 'ERROR DELETING SHIFT: ' || SQLERRM);
    END DELETE_SHIFT;


    -- =====================================================
    -- SECTION SHIFTS
    -- =====================================================

    PROCEDURE ADD_SECTION_SHIFT(
        P_SECTION_ID       IN SECTION_SHIFTS.SECTION_ID%TYPE,
        P_SHIFT_ID         IN SECTION_SHIFTS.SHIFT_ID%TYPE,
        P_STATUS           IN SECTION_SHIFTS.STATUS%TYPE,
        P_SECTION_SHIFT_ID OUT SECTION_SHIFTS.SECTION_SHIFT_ID%TYPE
    ) AS
    BEGIN
        INSERT INTO SECTION_SHIFTS (
            SECTION_ID, SHIFT_ID, STATUS
        ) VALUES (
            P_SECTION_ID, P_SHIFT_ID, P_STATUS
        )
        RETURNING SECTION_SHIFT_ID INTO P_SECTION_SHIFT_ID;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20501, 'SHIFT ALREADY ASSIGNED TO THIS SECTION.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20502, 'ERROR CREATING SECTION SHIFT: ' || SQLERRM);
    END ADD_SECTION_SHIFT;


    PROCEDURE UPDATE_SECTION_SHIFT(
        P_SECTION_SHIFT_ID IN SECTION_SHIFTS.SECTION_SHIFT_ID%TYPE,
        P_SECTION_ID       IN SECTION_SHIFTS.SECTION_ID%TYPE,
        P_SHIFT_ID         IN SECTION_SHIFTS.SHIFT_ID%TYPE,
        P_STATUS           IN SECTION_SHIFTS.STATUS%TYPE
    ) AS
    BEGIN
        UPDATE SECTION_SHIFTS
        SET SECTION_ID = P_SECTION_ID,
            SHIFT_ID   = P_SHIFT_ID,
            STATUS     = P_STATUS,
            UPDATED_AT = SYSTIMESTAMP
        WHERE SECTION_SHIFT_ID = P_SECTION_SHIFT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20503, 'SECTION SHIFT NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20501, 'SHIFT ALREADY ASSIGNED TO THIS SECTION.');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20504, 'ERROR UPDATING SECTION SHIFT: ' || SQLERRM);
    END UPDATE_SECTION_SHIFT;


    PROCEDURE GET_SECTION_SHIFT_BY_ID(
        P_SECTION_SHIFT_ID IN SECTION_SHIFTS.SECTION_SHIFT_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SS.SECTION_SHIFT_ID,
                SS.SECTION_ID,
                SEC.SECTION_NAME,
                SEC.SECTION_CODE,
                SS.SHIFT_ID,
                SH.SHIFT_NAME,
                SH.SHIFT_CODE,
                SH.START_TIME,
                SH.END_TIME,
                SS.STATUS,
                SS.CREATED_AT,
                SS.UPDATED_AT
            FROM SECTION_SHIFTS SS
            JOIN SECTIONS SEC ON SEC.SECTION_ID = SS.SECTION_ID
            JOIN SHIFTS SH ON SH.SHIFT_ID = SS.SHIFT_ID
            WHERE SS.SECTION_SHIFT_ID = P_SECTION_SHIFT_ID;
    END GET_SECTION_SHIFT_BY_ID;


    PROCEDURE GET_SHIFTS_BY_SECTION(
        P_SECTION_ID IN SECTION_SHIFTS.SECTION_ID%TYPE,
        P_RESULT OUT SYS_REFCURSOR
    ) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SS.SECTION_SHIFT_ID,
                SS.SECTION_ID,
                SS.SHIFT_ID,
                SH.SHIFT_NAME,
                SH.SHIFT_CODE,
                SH.START_TIME,
                SH.END_TIME,
                SH.DISPLAY_ORDER,
                SS.STATUS,
                SS.CREATED_AT,
                SS.UPDATED_AT
            FROM SECTION_SHIFTS SS
            JOIN SHIFTS SH ON SH.SHIFT_ID = SS.SHIFT_ID
            WHERE SS.SECTION_ID = P_SECTION_ID
            ORDER BY SH.DISPLAY_ORDER;
    END GET_SHIFTS_BY_SECTION;


    PROCEDURE GET_ALL_SECTION_SHIFTS(P_RESULT OUT SYS_REFCURSOR) AS
    BEGIN
        OPEN P_RESULT FOR
            SELECT
                SS.SECTION_SHIFT_ID,
                SS.SECTION_ID,
                SEC.SECTION_NAME,
                SEC.SECTION_CODE,
                SS.SHIFT_ID,
                SH.SHIFT_NAME,
                SH.SHIFT_CODE,
                SH.START_TIME,
                SH.END_TIME,
                SS.STATUS,
                SS.CREATED_AT,
                SS.UPDATED_AT
            FROM SECTION_SHIFTS SS
            JOIN SECTIONS SEC ON SEC.SECTION_ID = SS.SECTION_ID
            JOIN SHIFTS SH ON SH.SHIFT_ID = SS.SHIFT_ID
            ORDER BY SEC.SECTION_ID, SH.DISPLAY_ORDER;
    END GET_ALL_SECTION_SHIFTS;


    PROCEDURE DELETE_SECTION_SHIFT(
        P_SECTION_SHIFT_ID IN SECTION_SHIFTS.SECTION_SHIFT_ID%TYPE
    ) AS
    BEGIN
        DELETE FROM SECTION_SHIFTS
        WHERE SECTION_SHIFT_ID = P_SECTION_SHIFT_ID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20503, 'SECTION SHIFT NOT FOUND.');
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20505, 'ERROR DELETING SECTION SHIFT: ' || SQLERRM);
    END DELETE_SECTION_SHIFT;

END ACSS_MGT_PKG;
/
